.gitignore
.travis.yml
README.md
app/__init__.py
app/main/__init__.py
app/main/errors.py
app/main/views.py
app/templates/404.html
app/templates/_base_page.html
app/templates/_cookie_message.html
app/templates/_footer_categories.html
app/templates/_javascripts.html
app/templates/_proposition_header.html
app/templates/_stylesheets.html
app/templates/index.html
app/templates/list_services.html
application.py
bower.json
config.py
gulpfile.js
package.json
requirements.txt
scripts/run_tests.sh
setup.cfg
tests/app/__init__.py
tests/app/helpers.py
tests/app/test_application.py

This is a basic supplier app - allows a user to enter a supplier ID number and get a list of their G6 services from the API.

Skeleton supplier app

---

README.md
application.py

For development we will want to run multiple apps, so they should each bind to a different port number.

Update to run on port 5003

---

.ebextensions/packages.config
application.py
package.json
scripts/build.sh
setup.cfg

Adds build and run_app scripts, .ebextensions and environment variable names matching the common convention

Changes for elasticbeanstalk deployment

---

.ebextensions/cwl-logs-application.config
app/main/login.py

This has been tested against an ephemeral environment.

Add metric filters for for email sent events

---

app/assets/scss/_footer.scss
app/templates/_base_page.html
app/templates/_footer_categories.html

Duplicate of https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/49

Add all the links to the footer

---

app/__init__.py
app/main/services.py
tests/app/main/test_login.py
tests/app/main/test_services.py
tests/app/test_application.py

Duplicates https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/52

No trailing slashes on URLs

---

app/templates/_base_page.html

Matched the footer in supplier app to the new buyer app footers.
Note cookie page is hosted on the buyer app.

Matched footer links with those on buyer app

---

app/assets/scss/application.scss
app/templates/macros/toolkit_forms.html
bower.json

Brings in https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/92

Add file upload pattern from the toolkit

---

config.py

Added a config for preview so we can see new features

Added config for preview to switch on feature flags

---

config.py

Reverts alphagov/digitalmarketplace-supplier-frontend#91

Revert "Added config for preview to switch on feature flags"

---

config.py

Added a config block for preview to have features on.

Added config for preview to switch on features

---

app/main/views/services.py
app/templates/frameworks/dashboard.html
app/templates/suppliers/dashboard.html

Duplicates #90, but against `master`.

Add 'Apply to G-Cloud 7…' link

---

bower.json

**Depends on: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/102**
Includes:
- https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/101 – custom underlines for browse list

Update toolkit to latest version

---

app/__init__.py
app/templates/auth/login.html
tests/app/main/test_login.py

Including
- wording of title and 'forgotten password' link
- removal of the 'you must log in to view this page' banner (which required some futzing around with Flask Login)

Make login page more consistent with Grails app

---

config.py

- turned on the supplier dashboard
- turned on edit suppliers
- turned everything else off

Updated feature flags for go-live

---

app/templates/services/list_services.html
bower.json
tests/app/main/test_services.py

Use new tables for listing existing services

---

app/templates/frameworks/dashboard.html

Use toolkit template for declaration link

---

app/templates/_javascripts.html
app/templates/_stylesheets.html
config.py
requirements.txt
tests/app/helpers.py

Brings in https://github.com/alphagov/digitalmarketplace-utils/pull/102

Add utils-based cache busting of assets

---

config.py

Staging should be identical to production.

Disable feature flags in staging

---

app/assets/scss/_footer.scss
app/templates/_footer_categories.html

Brings in work done in the buyers' app in https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/110.

Mark all external links in footer as such

---

app/templates/macros/toolkit_forms.html
bower.json

Pass through 'hint' content for all question types

---

app/templates/errors/404.html
app/templates/errors/500.html

- now match what the buyer app does

Error page titles on supplier app updated

---

app/__init__.py
tests/app/helpers.py
tests/app/main/test_services.py

The flask_login method that loads the user on every request now checks the active / locked status of the user and will log the user out if that status is invalid.
This now ensures that if some one gets disabled by an admin, they are immediately logged out.

Ensure user is logged out when their account is deactivated.

---

app/main/helpers/services.py

The 'type' of multiple choice answers is 'checkboxes' plural.
[See the schema here](https://github.com/alphagov/digitalmarketplace-ssp-content/blob/master/tests/schemas/question.json#L11)

Fix checkboxes questions

---

app/templates/macros/toolkit_forms.html

Fixes a 500 error in release-139

Fix document form rendering failing when missing previous value

---

app/assets/scss/application.scss
app/main/helpers/services.py
app/main/views/services.py
app/templates/macros/toolkit_forms.html
tests/app/main/test_services.py

This is a manual rebase of #134

[#98558456] Add pricing fields to draft service editing

---

bower.json

Includes these two tweaks:
- https://github.com/alphagov/digitalmarketplace-ssp-content/commit/05ece6f6d0b634372d20d91ba0c470dc1ef1aa2e
- https://github.com/alphagov/digitalmarketplace-ssp-content/commit/e73df9c38b9ba1e30c70774a7eab24393ac7d1be

Update content of declaration questions

---

app/main/helpers/frameworks.py
app/main/views/frameworks.py
setup.cfg
tests/app/main/helpers/test_frameworks.py
tests/app/main/test_frameworks.py

See: https://www.pivotaltracker.com/story/show/100215328
Add validation for the selection questions. Validations are hard coded in the frontend. If any validations fail the form will not be submitted to the API. Once the questions have been successfully submitted the message on the dashboard will change to "You have made the declaration".
- All required fields must be filled in (some are optional, some are optional under certain conditions).
- Character limits must not be exceeded
- Formatting rules for DUNS and VAT numbers must be followed
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/53

Selection questions validation

---

app/templates/frameworks/dashboard.html
app/templates/frameworks/updates.html

From work by @superroz and @cathrooney.

Framework content updates

---

app/templates/frameworks/dashboard.html

It should match that on https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/132.

Correct the deadline on the framework dashboard

---

app/templates/frameworks/dashboard.html
tests/app/main/test_frameworks.py

Changes for content as specified by Ralph.

Content changes for dashboard

---

app/assets/javascripts/application.js
app/assets/scss/_supplier-declaration.scss
app/templates/frameworks/edit_declaration_section.html
app/templates/macros/toolkit_forms.html
bower.json
tests/app/main/test_frameworks.py
tests/app/main/test_services.py
tests/app/main/test_suppliers.py

- Implements (and depends on) alphagov/digitalmarketplace-frontend-toolkit#141
- Implements (and depends on) alphagov/digitalmarketplace-frontend-toolkit#140

Form accessibility improvements

---

app/declaration_manifest.yml
app/main/helpers/frameworks.py
bower.json
tests/app/main/helpers/test_frameworks.py

- Brings in https://github.com/alphagov/digitalmarketplace-ssp-content/commit/6d9513da03861c08f0e783b64edd6f9549cd0545
- Request from @superroz 
- Includes: alphagov/digitalmarketplace-ssp-content#60

Declaration amends

---

app/main/views/suppliers.py
app/templates/suppliers/company_contact_details.html
app/templates/suppliers/create_your_account.html
app/templates/suppliers/duns_number.html
tests/app/main/test_suppliers.py

The copy here may need tweaking still ( @ralph-hawkins , @superroz ), but these are essentially the extra messages we need for supplier sign-up.

Additional messaging for supplier sign up

---

app/declaration_manifest.yml

As requested by @superroz 
Before:
After:

Move equality question to end of first section

---

app/templates/frameworks/edit_declaration_section.html

As described by this story: https://www.pivotaltracker.com/story/show/101502250

Correct URL of return link on declaration form

---

app/main/forms/suppliers.py
app/templates/suppliers/company_contact_details.html
app/templates/suppliers/create_your_account.html
app/templates/suppliers/duns_number.html
tests/app/main/test_suppliers.py

As requested by @superroz and @cathrooney.

Create supplier content changes

---

bower.json

Pulls in latest version of SSP content.

Add supplier declaration validation messages

---

app/main/helpers/frameworks.py
tests/app/main/helpers/test_frameworks.py

Well, that missing comma took a log time to spot!
See: https://www.pivotaltracker.com/story/show/101692098

[#101692098] Fix declaration validation bug

---

app/main/helpers/frameworks.py
app/main/views/frameworks.py

@allait - I merged too soon based on the thumbs-up; here's the final change on the split declaration stuff.

Move `get_declaration_status` to helpers

---

app/templates/macros/toolkit_forms.html
requirements_for_test.txt
tests/app/main/test_services.py

It fails if there is no existing file. I did not test this well enough, I am sorry.

Fix file upload form display

---

app/main/helpers/frameworks.py
bower.json
tests/app/main/helpers/test_frameworks.py

See: https://www.pivotaltracker.com/story/show/101692394
This uses the regex from our User JSON schema to check for valid email addresses.
Content has already been updated with messaging.

[#101692394] Email validation for supplier declaration

---

app/templates/auth/create-user.html

Missed the create page on last pull request on this.

update content on create page invalid error to match update

---

app/main/views/frameworks.py
app/main/views/services.py
app/main/views/suppliers.py
app/templates/frameworks/dashboard.html
app/templates/services/service_submission.html
app/templates/suppliers/dashboard.html
config.py

See: https://www.pivotaltracker.com/story/show/101660010
This will ensure that the date displayed is accurate and consistent in all places it is displayed.

[#101660010] Extract closing date to a config variable

---

app/templates/suppliers/company_name.html

and added a non-breaking space to between Digital and Marketplace

‘your name’ should be ‘your company’s name’

---

app/templates/emails/clarification_question_submitted.html

See: https://www.pivotaltracker.com/story/show/102242764

[#102242764] Update email copy - do not reply

---

bower.json
tests/app/main/test_services.py

Validation messages and hint text updates.
See all the content changes this will bring in here: https://github.com/alphagov/digitalmarketplace-ssp-content/compare/15adb32dbd78652de7c3b1dfdfa3cebad60e77c8...92818a67caf476da2e8ff1cd53ead632c162e1dd

Last-minute content changes

---

app/main/helpers/frameworks.py

We lost some in a bad merge yesterday, and Cath had a couple more to add for the checkboxes.
See: https://www.pivotaltracker.com/story/show/102242820

[#102242820] Validation fixes again

---

config.py

As pointed out by @pcraig3 in https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/246#issuecomment-136648789

Explain 'BST' where used in the G7 deadline

---

app/main/views/login.py
app/templates/emails/create_user_email.html
app/templates/emails/invite_user_email.html
app/templates/emails/reset_password_email.html
requirements.txt

Depends on: https://github.com/alphagov/digitalmarketplace-utils/pull/154
See: https://www.pivotaltracker.com/story/show/101873730

[#101873730] Invitations should last a week

---

app/templates/macros/assurance.html
app/templates/macros/toolkit_forms.html
bower.json

See: https://www.pivotaltracker.com/story/show/102069502
Before:
After:

[#102069502] Assertion content update

---

app/templates/suppliers/company_summary.html
app/templates/suppliers/create_your_account.html
app/templates/suppliers/create_your_account_complete.html
tests/app/main/test_suppliers.py

As per: https://docs.google.com/document/d/1E9WCFAEvXjzaPr1nF1HaLeAMamnQm3xcrh6fchBUKmU/edit#

Content changes to create account process

---

bower.json

Brings in: https://github.com/alphagov/digitalmarketplace-ssp-content/pull/76
Changes: https://github.com/alphagov/digitalmarketplace-ssp-content/compare/92818a67caf476da2e8ff1cd53ead632c162e1dd%E2%80%A6aa1b1c41b8c6872c852ed6d6f38c4e26fefc6ed1

Remove reference to ITT

---

README.md

Missed this out of https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/264

Make it clear `run_tests.sh` runs all the suite

---

app/main/views/services.py
requirements.txt

[#103403706](https://www.pivotaltracker.com/story/show/103403706)
Fixes missing request ID on error responses and logging of API
requests.

Update dmutils to 8.1.1

---

app/main/views/suppliers.py

See: https://www.pivotaltracker.com/story/show/104308518
Before:
After:

[#104308518] Prevent 500s if session expired on create-your-account-complete page

---

app/templates/frameworks/dashboard.html
app/templates/suppliers/dashboard.html

These copy amends were missed from the original changes.

Fix G-Cloud number

---

app/main/helpers/services.py
app/main/views/services.py
tests/app/main/test_services.py

Functions that are also required by the admin frontend have been moved to dmutils.

Use shared service helpers from dmutils

---

tests/app/main/test_frameworks.py
tests/app/main/test_services.py
tests/app/main/test_suppliers.py

Tests for the page states produced by this work: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/301
(The work was tested manually when merged, due to time constraints.)

Add tests for g7 content updates

---

app/main/__init__.py
app/main/views/frameworks.py
app/main/views/services.py
requirements.txt
tests/app/main/helpers/test_frameworks.py
tests/app/main/test_services.py

This contains a few [version bumps in dmutils](https://github.com/alphagov/digitalmarketplace-utils/compare/9.0.0...10.0.1).
The most significant is the 10.0.0 change https://github.com/alphagov/digitalmarketplace-utils/pull/182

Upgrade dmutils to 10.0.1

---

app/assets/javascripts/analytics/_register.js
spec/javascripts/unit/AnalyticsSpec.js

Updating Google Analytics ID

---

app/__init__.py
app/assets/scss/_supplier-declaration.scss
app/main/helpers/frameworks.py
app/main/views/frameworks.py
app/templates/frameworks/dashboard.html
app/templates/frameworks/edit_declaration_section.html
app/templates/macros/toolkit_forms.html
bower.json
gulpfile.js
package.json
requirements.txt
tests/app/test_application.py

- frameworks and utils to handle the content
- latest Node SASS to work on newest Node (for Heroku)
- implements alphagov/digitalmarketplace-utils#186
- adds a template filter for looking up questions
- this should mean that we don’t have to publish separate guidance

Add declaration content for Digital Outcomes and Specialists

---

app/templates/frameworks/agreement.html

Re-add final instruction to upload signed document

---

app/main/views/suppliers.py
app/templates/suppliers/_frameworks_coming.html
app/templates/suppliers/dashboard.html
tests/app/main/test_suppliers.py

Add message to supplier dashboard when framework is coming

---

app/main/views/frameworks.py
config.py

https://www.pivotaltracker.com/story/show/108938292

[#108938292] Update DOS closing date

---

app/main/helpers/frameworks.py
app/main/helpers/services.py
app/main/views/frameworks.py
app/main/views/services.py
app/templates/frameworks/dashboard.html
app/templates/frameworks/updates.html
config.py
scripts/run_app.sh
scripts/test_env.sh
tests/app/main/test_frameworks.py
tests/app/main/test_services.py

The new bucket layout is:
bucket name: digitalmarketplace-{bucket_short_name}-{stage}-{environment}
path structure: {framework_slug}/{bucket_short_name}/{path}

Use communications buckeet

---

app/main/helpers/services.py
app/main/views/services.py
app/templates/services/_base_service_page.html
app/templates/services/service_submission.html
scripts/run_app.sh
tests/app/main/test_services.py

See: https://www.pivotaltracker.com/story/show/107188798
NOTE: This now depends on: 
This adds a "Remove" link to subsections that have been added (e.g. specialists), but doesn't let you remove the last one.

[#107188798] Edit remove subsections

---

bower.json

Make question headings not bold

---

app/main/helpers/frameworks.py
tests/app/main/helpers/test_frameworks.py

Came out of yesterday’s content review. This is more consistent with the other lots.

Change status text for draft studios

---

app/templates/services/service_submission.html
tests/app/main/test_services.py

One for the SSFL 💩
Matches https://www.pivotaltracker.com/story/show/109371844
> **content for all lots except labs**
> button at bottom of the page: Delete
> are you sure banner:
> Are you sure you want to delete [lot name]?
> Yes, delete
> **for labs**
> button at bottom of the page: Delete
> are you sure banner:
> Are you sure you want to delete this lab?
> Yes, delete

Change delete messaging

---

app/main/helpers/validation.py

This fixes two bugs;
- Character limit fails on empty text fields
- Email validation fails when empty
This also adds default messages for character limit and invalid format. These are not ideal but we do not have any custom validation messages in the content repo for these questions so this is better than nothin.

Fix declaration validation

---

bower.json

Includes changes to UK regions.

Bump frameworks version to v0.13.0

---

bower.json

This brings in the new conditional validation messages

Bump frameworks version

---

bower.json

https://github.com/alphagov/digitalmarketplace-frameworks/compare/v0.14.1...bump-version-0.14.3

Update question content

---

requirements.txt

See: https://www.pivotaltracker.com/story/show/109632740
This will bring in the updated lab price display from the utils update that it depends on:

[#109632740] Updated lab pricing display

---

bower.json

Needed for this story: https://www.pivotaltracker.com/story/show/109270496
See: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/202

Brings in support for empty data fields

---

app/__init__.py
app/main/errors.py
app/main/helpers/frameworks.py
app/main/helpers/services.py
app/main/views/frameworks.py
app/main/views/login.py
app/main/views/services.py
app/main/views/suppliers.py
requirements.txt
tests/app/main/test_frameworks.py
tests/app/main/test_login.py
tests/app/main/test_services.py
tests/app/main/test_suppliers.py
tests/app/test_application.py

Fixes imports to use the new dmapiclient package instead of
dmutils.apiclient and dmutils.audit.

Update dmutils and add dmapiclient package dependency

---

scripts/run_app.sh

Brings it into line with Buyer app (see [the same script](https://github.com/alphagov/digitalmarketplace-buyer-frontend/blob/master/scripts/run_app.sh#L8) in the buyer app).

Build front-end code before running app

---

Makefile
README.md
config.py
scripts/run_app.sh
scripts/run_tests.sh

This way there is one place where config defaults are managed. They can still be overridden with environment variables.
This follows the lead taken in `digitalmarketplace-api`

Add makefile

---

scripts/run_app.sh
scripts/run_tests.sh

Now that we have a Makefile that captures these tasks these scripts
should be driven by that. These scripts are being left here for people
that are using them.

Drive run scripts from the Makefile

---

.travis.yml
app/main/views/frameworks.py
requirements.txt
scripts/run_tests.sh

Fixes log formatting errors in JSON logger and removes unicode
characters from supplier names to avoid Content-Disposition errors.

Fix logging and unicode errors

---

app/main/errors.py
app/main/views/briefs.py
app/main/views/frameworks.py
app/main/views/login.py
app/main/views/services.py
app/main/views/suppliers.py
app/main/views/users.py
requirements.txt

This is handled by `init_app` in utils now.
Pages look right locally and tests pass, so I believe this works.

Don't inject the template data explicitly

---

bower.json
requirements.txt

Upgrade the content loader and content repo to bring in explicitly defined IDs in the question content.

Upgrade the content loader with explicit IDs

---

app/templates/_base_page.html
app/templates/_footer_categories.html
app/templates/suppliers/companies_house_number.html
app/templates/suppliers/create_new_supplier.html

See: https://www.pivotaltracker.com/story/show/113081517
New links added look like this:

[#113081517] Two new footer links

---

bower.json

See: https://www.pivotaltracker.com/story/show/114571349
Participants locations are different from outcomes/specialists locations.
Depends on:

[#114571349] Brief locations for research participants

---

app/main/__init__.py
app/main/helpers/validation.py
bower.json

We would like to start testing G-Cloud 8 on preview.

G-Cloud 8 setup

---

app/templates/_footer_categories.html

Doing @quis's dirty work for him... see https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/25 (already merged on buyer app).

Smart quotes in footer links, to mirror those in buyer app

---

app/templates/macros/toolkit_forms.html
bower.json
requirements.txt

Adds macro support for the 'price' field for pricing questions.
Updates dmutils and frameworks to bring in new email and dayRate field types.

Pass price field value to the form template

---

app/main/helpers/validation.py
bower.json
tests/app/main/helpers/validation/test_g8_declaration.py

Depends on the following changes to declaration being merged:
This adds validation to the new DUNS number field introduced with the latest declaration content changes.

Add declaration DUNS validation

---

app/templates/emails/g-cloud-8_application_started.html

Text taken from this doc: https://docs.google.com/document/d/1rGlCOCVoTU7ryLY0hew4ZQl58_uHMGBH1aj1ko8cAZg/edit?ts=571e1601
New version looks like this when it gets sent:

Update G-Cloud 8 welcome email content

---

bower.json
requirements.txt

Depends on this getting merged first: 
Now also:

Latest content loader (questions with assertions validation bugfixes)

---

bower.json

Pull in latest content with G8 ZIP file size

---

app/templates/_footer_categories.html

As requested in https://www.pivotaltracker.com/story/show/119579917.

Fix link to DM buyers' guide

---

bower.json

Pulls in latest content version.

Pull in new G8 closing date

---

app/assets/scss/_footer.scss
bower.json
package.json

Bumps the GOVUK template and fixes the problem this brings in (see https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/338).
https://www.pivotaltracker.com/story/show/120364875

Bump govuk template

---

app/templates/frameworks/_dashboard_lede.html
tests/app/main/test_frameworks.py

We are no longer going to give letters to all suppliers, so the text here needs to be changed.

Update text about how suppliers will be notified of G8 result

---

app/templates/briefs/view_response_result.html

Final wording change before we put this page live - see the discussion this story: https://www.pivotaltracker.com/story/show/121479497

Tweak wording of message for suppliers who don't have all essential requirements

---

app/templates/_footer_categories.html

Again, also fixed some indentation in the template.
Story https://www.pivotaltracker.com/story/show/124104671

[#124104671]Change contact link to email in footer

---

config.py

To ship in the morning of 23rd

Turn on contract variation flag on production

---

app/templates/frameworks/contract_variation.html
tests/app/main/test_frameworks.py

Changes so the page will still work once API changes go in:

Contract variation countersigner keys have changed

---

bower.json

This is for the contract variation page.

Pull in latest content

---

app/main/views/services.py
app/templates/services/edit_submission_section.html
tests/app/helpers.py
tests/app/main/test_services.py

Did a little test tidying at the same time.

[#131615547]Service sumbission "continue" flow

---

app/main/__init__.py
app/main/helpers/validation.py
app/templates/emails/digital-outcomes-and-specialists-2_application_started.html
bower.json

Changes required to get DOS2 open.
With the changes here running locally I have successfully started an application, completed the declaration and completed a service in each lot.

**DOS2: Load DOS2

---

bower.json

Hopefully addresses all outstanding issues in this story: https://www.pivotaltracker.com/story/show/132749291

Pull in latest content with DOS2 tweaks

---

app/main/views/frameworks.py
app/templates/emails/digital-outcomes-and-specialists-2_application_started.html
tests/app/main/test_frameworks.py

For this story: https://www.pivotaltracker.com/story/show/131156187
Updated from the document referenced in the story.
Email looks like this when delivered (gmail):

[#131156187] Update DOS2 welcome email content

---

bower.json

Adds supplier guide URLs for all frameworks plus legal wording tweaks.

Pull in latest content changes

---

app/templates/suppliers/create_new_supplier.html

Fixes this bug: https://www.pivotaltracker.com/story/show/133592011

Update Companies House URL in new supplier flow

---

app/templates/emails/digital-outcomes-and-specialists-2_application_started.html

Completes this story: https://www.pivotaltracker.com/story/show/133332331
And this story: https://www.pivotaltracker.com/story/show/133335865
This branch is based on: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/546, which should be merged before this one.
This also depends on this being merged first:

Update DOS2 welcome email dates and link

---

tests/app/main/test_briefs.py

* ensure question contents are escaped in the emails
* ensure brief name is escaped in the header

add tests for xsses on brief clarification question page

---

app/main/__init__.py
app/main/views/briefs.py
app/templates/briefs/edit_brief_response.html
app/templates/briefs/start_brief_response.html
app/templates/services/_base_edit_section_page.html
bower.json
requirements.txt
tests/app/helpers.py
tests/app/main/test_briefs.py

We will be running a new multipage process for suppliers applying for a brief. This process will need to run in parallel to the current one for a period of two weeks. After this period we will be able to remove the current process (one page flow).
https://dm-prototype.cloudapps.digital/structure/opportunity/dos-opportunities?opportunity=0
Covers the following stories:
- https://www.pivotaltracker.com/story/show/129843611
- https://www.pivotaltracker.com/story/show/129839965
- https://www.pivotaltracker.com/story/show/131617615
We are aiming to build the prototype but this pull request only has half of the work done. This is so we can get something small(er) code reviewed/QA/merged etc rather than a massive block of work. Note, because of this, the flow will not work and validation will …

Apply for a brief multipage flow

---

Makefile
scripts/bootstrap.sh

- cleared out unused code from bootstrap.sh
- added npm_install to Makefile in line with other projects
- added npm_install to run_all directive in Makefile
- made run_app use the virtualenv python
- used DM_ENVIRONMENT to infer a GULP_ENVIRONMENT in order to build development assets on development environments and production assets in all other environments

Fix initial project setup

---

README.md
gulpfile.js

New watcher for frameworks to make framework dev nicer

Add new watcher for frameworks to make framework dev nicer

---

bower.json

Brings in these changes to frameworks:
https://github.com/alphagov/digitalmarketplace-frameworks/pull/347/files#diff-f4a4e558af4948ecec7828626f3dc8d1L22

Extra content changes for essential requirements

---

app/templates/frameworks/contract_start.html
bower.json

This will also fix the email template date for DOS2 emails.

Moar framework agreement urls

---

app/templates/emails/create_user_email.html
app/templates/emails/invite_user_email.html
app/templates/emails/reset_password_email.html

For this bug: https://www.pivotaltracker.com/story/show/136103557
Some users have had issues with clicking the link in their invitation emails. This may help alleviate the problem.

Wrap email links in anchor tags

---

app/main/views/services.py
tests/app/main/test_services.py

Story https://www.pivotaltracker.com/story/show/137344025
The first thing done here is to significantly refactor the tests around the edit & remove views.
The views are then fixed to work properly cross-framework. Frameworks without an `edit_service` content manifest will not allow editing **or** removal by a supplier. Not this latter change in behaviour - previously the removal of a e.g. dos service was not enforced by the actual remove view. The behaviour of the edit page for a dos supplier was... undefined (probably a 500). These are now 404s.

[#137344025]supplier service editing: straighten out framework-determined behaviours for edit & remove views

---

app/main/views/briefs.py
app/templates/briefs/edit_brief_response_question.html
requirements.txt
tests/app/main/test_briefs.py

For [this pivotal story](https://www.pivotaltracker.com/story/show/137359355)

Add previous page links

---

bower.json
tests/app/main/test_suppliers.py

Pull in latest toolkit version

---

app/main/views/frameworks.py
app/templates/frameworks/_framework_actions.html
app/templates/frameworks/start_declaration.html
tests/app/main/test_frameworks.py

Story: https://www.pivotaltracker.com/story/show/138322855
This PR inserts a new page into the supplier declaration journey, signposting what they are about to do and why.

[#138322855] - add 'start supplier declaration' page

---

app/main/__init__.py
app/main/views/briefs.py
bower.json
tests/app/main/test_briefs.py

For this pivotal story - https://www.pivotaltracker.com/story/show/138430483

Bump frameworks to 5.11.1 to bring in updated error messages

---

bower.json

As per this pivotal comment - https://www.pivotaltracker.com:/story/show/138430483/comments/162122003

Bump frameworks to 5.11.2 to update error message

---

app/main/helpers/briefs.py
app/main/views/frameworks.py
app/main/views/login.py
app/main/views/suppliers.py
requirements.txt
tests/app/main/test_briefs.py
tests/app/main/test_frameworks.py
tests/app/main/test_login.py
tests/app/main/test_suppliers.py

Upcoming utils upgrade changes email imports

BUGFIX-repair-email-imports

---

requirements.txt

Fix content loader import (hopefully)

---

app/main/views/frameworks.py
app/templates/frameworks/_framework_actions.html
app/templates/frameworks/declaration_overview.html
app/templates/frameworks/services.html
app/templates/frameworks/start_declaration.html
app/templates/frameworks/submission_lots.html
app/templates/services/service_submission.html
tests/app/helpers.py
tests/app/main/test_frameworks.py

Story https://www.pivotaltracker.com/story/show/138323307
Will probably add more information here soon.

[#138323307]framework declaration overview

---

app/main/helpers/frameworks.py
app/main/views/frameworks.py
app/templates/frameworks/reuse_declaration.html
tests/app/main/helpers/test_frameworks.py
tests/app/main/test_frameworks.py

* Accept 'no-reuse' instead of 0 as negative for reuse
* POST email_address instead of user object
* Update tests
See issue here for more details:
https://github.com/alphagov/digitalmarketplace-frontend-toolkit/issues/306

NO-TICKET-repair-post-bug

---

app/templates/frameworks/declaration_overview.html
tests/app/main/test_frameworks.py

* Change declaration overview page to state 'Answer question' instead of 'Answer required' when an answer still needs to be provided.

NO-TICKET-AR-AQ As per request from RH

---

app/main/forms/frameworks.py
app/main/views/frameworks.py
app/templates/frameworks/reuse_declaration.html
tests/app/main/test_frameworks.py

* New form `ReuseDeclarationForm`
* Have view use form
* Have template accept form and display validation

NO-TICKET-implement-validation

---

app/assets/scss/application.scss
app/templates/frameworks/declaration_overview.html

Followup to story https://www.pivotaltracker.com/story/show/138323307

[#138323307]declaration overview: use secondary action link for "Return to Application" link

---

app/templates/frameworks/dashboard.html
tests/app/main/test_frameworks.py

* New banner on framework overview page
* https://preview.development.digitalmarketplace.service.gov.uk/suppliers/frameworks/g-cloud-9
* Tests

140124261-confidence-banner-on-framework-overview-2

---

app/main/views/services.py
tests/app/main/test_services.py

Fixes this bug: https://www.pivotaltracker.com/story/show/138050747
Previously it was possible for a supplier user to enter the "create draft" url directly and begin submitting drafts without ever having registered interest in the framework.
Changes here make it impossible to do the following things to draft services if no supplier_framework entry exists for the current supplier:
* create
* copy
* complete
* edit
* delete
* remove subsection

Bugfix: require supplier_framework entry to create and edit drafts

---

app/main/views/frameworks.py
app/templates/frameworks/declaration_overview.html
tests/app/main/test_frameworks.py

For this story: https://www.pivotaltracker.com/story/show/140924619
Changes:
* `/start-declaration` --> `/declaration/start`
* `/declaration/<section>` --> `/declaration/edit/<section>`
* `framework_supplier_declaration` --> `framework_supplier_declaration_edit`

Update declaration urls

---

app/templates/frameworks/declaration_overview.html

https://www.pivotaltracker.com/n/projects/904880/stories/140919347

140919347-non-breaking-time-on-declaration-overview

---

app/templates/frameworks/declaration_overview.html

Have space between "before" and the date

---

app/assets/scss/_framework-application.scss
app/templates/frameworks/submission_lots.html
bower.json

* Adds CSS to style the framework lots page correctly.
* Pulls in latest frameworks 6.4.2 for lot descriptions.

Add support for formatted content in lot descriptions

---

bower.json

* As stated, pull in frameworks 6.4.4 and frontend-toolkit 22.1.0
* Won't pass until other PRs are in.

Pull in latest frameworks and frontend-toolkit

---

bower.json

Pull in 6.4.5 frameworks and 21.1.1 frontend-toolkit

---

tests/app/main/test_frameworks.py

This test was the result of a wild goose chase chasing a phantom bug (https://www.pivotaltracker.com/story/show/141116685). it's still a valid test though, so it's probably worth adding anyway.

framework_supplier_declaration_edit: add extra test, testing validation works properly on re-submit of a previously valid declaration section

---

bower.json

This has the lot numbering fix for one declaration question.

Fix lot numbering

---

app/main/views/briefs.py
app/templates/briefs/view_response_result.html
tests/app/main/test_briefs.py

* Add result=success param to url on successful brief submission (for analytics)
* Update tests
https://www.pivotaltracker.com/story/show/140921547

140921547-Measure-how-people-are-using-the-new-evidence-flow

---

app/main/views/frameworks.py
tests/app/main/test_frameworks.py

Improve the validation message when users submit blank clarification questions on frameworks.

Better validation message

---

app/templates/briefs/view_response_result.html
tests/app/main/test_briefs.py

140921547-Measure-how-people-are-using-the-new-evidence-flow-change-url

---

app/main/views/frameworks.py
tests/app/main/test_frameworks.py

Story: https://www.pivotaltracker.com/story/show/142242977

[#142242977]fixes bug when the declaration is None instead of empty dict

---

app/main/forms/auth_forms.py
app/main/forms/suppliers.py
bower.json

Story: https://www.pivotaltracker.com/story/show/122035455
* Changes WTForm validators to the same Regexp used in the buyer app.
* Bump frontend toolkit version to latest one.

Fix email validation

---

.gitignore
app/assets/javascripts/analytics/_virtualPageViews.js
app/templates/suppliers/dashboard.html
spec/javascripts/unit/AnalyticsSpec.js
tests/app/main/test_suppliers.py

Trello: https://trello.com/c/nJS459VK/256-consistent-naming-for-virtual-page-views

Add consistent naming for virtual page views

---

bower.json

Pull in latest frameworks to allow editing features and benefits

---

app/main/views/suppliers.py

https://trello.com/c/MD0JKN5Q/41-2-create-organisation-details-page
To satisfy QA

supplier details editing: redirect old route for this view

---

app/templates/suppliers/details.html

Placate QA https://trello.com/c/MD0JKN5Q/41-2-create-organisation-details-page

supplier details page: use a smaller heading style

---

app/templates/suppliers/_frameworks_live.html
tests/app/main/test_suppliers.py

Story https://trello.com/c/5jTvXMoA/42-1-implement-new-layout-for-supplier-dashboard

supplier dashboard: change order of framework links, add test ensuring this behaviour

---

app/templates/suppliers/_frameworks_coming.html
app/templates/suppliers/companies_house_number.html
app/templates/suppliers/company_contact_details.html
app/templates/suppliers/company_name.html
app/templates/suppliers/company_summary.html
app/templates/suppliers/create_new_supplier.html
app/templates/suppliers/create_your_account.html
app/templates/suppliers/create_your_account_complete.html
app/templates/suppliers/duns_number.html

For this ticket on Trello: https://trello.com/c/wHRA6ScY/74-update-the-sign-up-journey-content-development-1
The working document has got pretty messy, but final changes here are cleared with Constance and I've shown the updated flow to @laurenceberry and he's happy with how it all looks and reads. I've attached screenshots of the full flow below - not all of the pages have been changed, but you can see how it all hangs together better with it all there I think.
There is a corresponding legacy functional tests update here, which should be merged at the same time as this: 
## Page 1
## Page 2
## Page 3
## Page 4
## Page 5
## Page 6
## Page 7
## Page 8

Update content in sign up flow

---

app/templates/suppliers/create_new_supplier.html

Late-breaking update on https://trello.com/c/wHRA6ScY/74-update-the-sign-up-journey-content-development-1 (everything else for that ticket is on Staging already).
## Before

Final_final_FINAL_v2 content changes

---

app/main/helpers/frameworks.py
app/main/views/suppliers.py
app/templates/suppliers/become_a_supplier.html
bower.json
tests/app/main/helpers/test_frameworks.py
tests/app/main/test_suppliers.py

This depends on this frameworks PR being merged before tests will pass: 
For this Trello ticket: https://trello.com/c/kMYuzoge/75-create-the-become-a-supplier-page-2

Become a supplier page

---

app/templates/suppliers/become_a_supplier.html
bower.json
tests/app/main/test_suppliers.py

Closely pack "Become a supplier" paragraphs

---

app/templates/emails/invite_user_email.html

For this ticket: https://trello.com/c/1LYD8OUv/82-redesign-the-content-of-the-welcome-email-to-collaborators-on-the-marketplace-1

Update invitation email text to remove "contributor"

---

app/templates/frameworks/contract_variation.html
app/templates/macros/toolkit_forms.html
bower.json

Story https://trello.com/c/W3d7VMrO/72-supplier-app-use-frontend-toolkit-macros-3
Depends on https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/375
Don't know how much more I need to say.

form macros: base most of these on the upstream toolkit's copy

---

app/templates/services/service.html

Trello ticket: https://trello.com/c/SYdzzA0K/3-add-in-app-content-to-gcloud-edit-service

Add content about editing to GCloud service description

---

app/main/helpers/validation.py
app/templates/emails/digital-outcomes-and-specialists-3_application_started.html
app/templates/emails/g-cloud-10_application_started.html

This is everything else needed to make G10 and DOS3 applications work.

Add DOS3 G10 validators & email templates

---

tests/app/main/test_frameworks.py

Add parametrize instead of for loops for better output
Refactor lines that will fit within character line limit

Refactor framework tests

---

app/templates/_footer_categories.html
requirements-app.txt
requirements.txt

requires:
https://github.com/alphagov/digitalmarketplace-utils/pull/346

Adds in /help page

---

app/templates/suppliers/duns_number.html

I didn't update the content on the button as per the prototype.
https://trello.com/c/ae5UzOAn/39-sign-up-flow-update-copy-on-duns-number-page

Update content on duns number button

---

package.json
yarn.lock

Required PR:
https://github.com/alphagov/digitalmarketplace-frameworks/pull/494
Ticket: https://github.com/alphagov/digitalmarketplace-frameworks/pull/494

update framework to 10.4.0

---

app/main/forms/frameworks.py
app/templates/emails/digital-outcomes-and-specialists-2_variation_1_agreed.html
app/templates/emails/g-cloud-9_variation_1_agreed.html
app/templates/frameworks/contract_variation.html
package.json
tests/app/main/test_frameworks.py
yarn.lock

Ticket: https://trello.com/c/lUuiyoWE/114-prepare-contract-variation-for-dos2

Changes to support DOS2 GDPR contract variations

---

app/main/forms/suppliers.py

Fixes the QA issue raised on this ticket: https://trello.com/c/nToxBmYI/48-new-one-time-page-build-registered-with-companies-house-page
There was an issue where previously entered "bad" data in one company number field could prevent successful submission of valid data in the other company field, even though the "bad" field wasn't visible on the page when the form was submitted.
This fixes the validator to clear any data in fields that were not visible when the form was submitted.  (Or, in the case of no-Javascript users, clearing data from fields that were not associated with the selected "Yes/No" radio button.

Tweak validation of company number form

---

app/main/views/suppliers.py
app/templates/suppliers/details.html
package.json
tests/app/main/test_suppliers.py
yarn.lock

Trello ticket: https://trello.com/c/x5mzD7bS/49-supplier-add-links-to-all-the-new-change-pages

Add links to all the new detail edit pages

---

app/templates/suppliers/registered_address.html

All other supplier details questions used 'Save and continue', so updating here to be
consistent.

Edit submit button content for registered address

---

package.json
yarn.lock

Pull in latest content changes from frameworks v11.4.0
https://trello.com/c/6reJHmEm/9-update-declaration-and-service-questions-on-dm

Bump frameworks to 11.4.0

---

package.json
yarn.lock

See this PR on the frameworks repo: https://github.com/alphagov/digitalmarketplace-frameworks/pull/519

Don't copy questions that depend on other questions

---

app/templates/suppliers/already_completed.html
app/templates/suppliers/details.html
tests/app/main/test_suppliers.py

Some suppliers didn't realise the gravity of changing these details.
This updated content should help to clarify.

Update content on supplier details page

---

requirements-app.txt
requirements.txt

https://trello.com/c/M0hAGLYT/303

Update utils for external call logging

---

app/main/__init__.py
app/main/forms/frameworks.py
app/main/helpers/frameworks.py
app/main/helpers/services.py
app/main/views/frameworks.py
app/main/views/services.py
app/templates/frameworks/services.html
app/templates/services/previous_services.html
package.json
requirements-app.txt
requirements.txt
tests/app/helpers.py
tests/app/main/helpers/test_frameworks.py
tests/app/main/helpers/test_services.py
tests/app/main/test_frameworks.py
tests/app/main/test_services.py
yarn.lock

For [this trello ticket.](https://trello.com/c/QhfXDVjt)
Adds the logic to allow suppliers to copy previous services for single service lots. Uses a similar pattern to declaration copying, with a single page boolean question.
I'm not convinced by the content in this PR as it stands. Need to go over with a content person.

Digital Outcomes and Specialists - Copying services

---

app/templates/services/previous_services.html
tests/app/main/test_services.py

For [this trello ticket.](https://trello.com/c/QhfXDVjt)

Remove unnecessary bullet points

---

app/main/views/services.py
app/templates/services/service.html
config.py

This feature has been live since October 2017 so the flag is no longer required.

Remove edit sections feature flag

---

package.json
yarn.lock

For [this trello ticket](https://trello.com/c/uRNZWEVm)
Includes new content and a new question for DOS3 declaration.

Bump frameworks version to 12.3.0

---

app/main/views/frameworks.py
app/main/views/login.py
app/main/views/services.py
app/main/views/suppliers.py
app/main/views/users.py
requirements-app.txt
requirements.txt

This should allow us better insight into slowness during the signup journey.

digitalmarketplace-utils dependency: bump to 40.6.1, use new timed_render_template in views

---

package.json
yarn.lock

It adds dates to the DOS3 declaration questions.

Pull in Frameworks v 13.3.0

---

package.json
yarn.lock

For [this trello ticket.](https://trello.com/c/yYTrmIk3)
See [this frameworks PR](https://github.com/alphagov/digitalmarketplace-frameworks/pull/535)
Fixes a few questions not opening in new tabs and a couple of stale links.

Fix bugs in DOS3 declaration questions

---

app/main/views/frameworks.py
requirements-app.txt
requirements.txt
tests/app/main/test_frameworks.py

* Upgrade to flask 1.0.2
* http://flask.pocoo.org/docs/1.0/changelog/#version-1-0-2
* https://trello.com/c/bBDir2Gp/18-flask-1x-upgrade
* Update the send_email methods of `DMMandrillClient` and `DMNotfyClient` to use new function signatures

upgrade to flask 1.0.2

---

package.json
yarn.lock

It updates the URL to the DOS3 pdf framework agreement.

Pull in v13.6.1 of frameworks

---

requirements-app.txt
requirements.txt

See:
https://github.com/alphagov/digitalmarketplace-utils/pull/469

Bump utils to bring in v44.8.2 changing mailchimp reaction to "already on list" error

---

app/main/views/frameworks.py
requirements-app.txt
requirements.txt
tests/app/main/test_frameworks.py
tests/app/main/test_services.py

New utils for file type checking

169-file-upload-sniffing-type-restrictions

---

requirements-dev.txt
tests/app/main/test_frameworks.py
tests/app/main/test_services.py

Will fail until https://github.com/alphagov/digitalmarketplace-test-utils/pull/11/files is merged

 Use new testutils document fixtures in tests

---

.pyup.yml

Making this the next repo to get pyup'd

Add pyup config file

---

app/main/helpers/validation.py
app/main/views/frameworks.py
app/templates/frameworks/edit_declaration_section.html
package.json
requirements-app.txt
requirements.txt
tests/app/main/test_frameworks.py
yarn.lock

Trello: https://trello.com/c/x5GVLSkq/384-implement-changes-for-legislation-changes-in-application-questions
- Optional and dependent fields for G11 declaration validation
- Content changes (see https://github.com/alphagov/digitalmarketplace-frameworks/pull/548)
- FE toolkit changes for the file upload form (see https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/464)
- Utils changes for the file upload function (see https://github.com/alphagov/digitalmarketplace-utils/pull/496)
- Changes to the declaration edit view to allow file uploads

G11 validation declaration fields

---

app/main/views/frameworks.py
tests/app/main/test_frameworks.py

Trello: https://trello.com/c/hLraF3nS/397-ga-custom-dimensions-instrumentation-to-map-supplier-submission-journey
Adds a `data-value` according to each stage of the supplier framework application:
1/. `application_started` (no company details, declaration or services yet)
2/. `company_details_confirmed` (different from `company_details_complete` - in that case the supplier has to confirm they're still correct from the last framework iteration)
3a/. `declaration_confirmed` and 
3b/. `services_confirmed` (can happen in either order after company details are confirmed, but Ash is fine with this)
4/. `application_confirmed` (all done)
Ash has confirmed the dimension value will be 29.

GA custom dimension values for each stage of framework applications

---

package.json
yarn.lock

I thought we'd done this already but it seems not.

Upgrade country auto-complete package

---

app/assets/javascripts/application.js
app/assets/scss/application.scss
app/main/views/frameworks.py
app/main/views/services.py
app/templates/frameworks/_session_timeout.html
app/templates/frameworks/edit_declaration_section.html
app/templates/services/_base_edit_section_page.html
gulpfile.js
package.json
requirements-app.txt
requirements-dev.txt
requirements.txt
tests/app/main/test_frameworks.py
tests/app/main/test_services.py
yarn.lock

We want our users to be aware when filling out long forms that they may be logged out if they do not interact with the website for longer than an hour.
This PR adds a simple text message at the top of framework application forms.
See the [ticket] for more details.
[ticket]: https://trello.com/c/92nGYty4/

Add display session timeout message during applications

---

app/templates/frameworks/updates.html

https://trello.com/c/gYChLact/198-link-to-guidance-on-g-cloud-updates-page

Added link to G-Cloud guidance

---

package.json
yarn.lock

Trello: https://trello.com/c/1YUXLv7P/473-remove-unnecessary-clause-from-declaration-question
Pulls in https://github.com/alphagov/digitalmarketplace-frameworks/pull/564 with amended declaration question.

Pull in frameworks content

---

app/main/views/frameworks.py

This should help us narrow down the poor performance of this view.

 framework_submission_services: add logged_duration around draft detail calculation

---

.pyup.yml

https://trello.com/c/mBmxDwfC/823-make-pyup-prs-appear-in-the-morning

Move PyUp to Sundays

---

default.nix

Fixes things given new pytest churn.

default.nix: add sitecustomize.py to prioritize non-nix python paths (i.e. the venv ones) over nix ones

---

app/main/helpers/frameworks.py
requirements-dev.txt
tests/app/main/helpers/test_frameworks.py

https://trello.com/c/V7cUDIRW
The required frontend changes _appear_ to be minimal.

get_framework_for_reuse: respect supplierFramework.allowDeclarationReuse

---

package.json
yarn.lock

Bring in updated G-Cloud 11 urls.

Update digitalmarketplace-frameworks from 16.0.1 to 16.0.2

---

app/main/forms/frameworks.py
app/templates/frameworks/updates.html
package.json
tests/app/main/test_services.py
yarn.lock

https://trello.com/c/nhi1PRi4/579-i-dont-adhere-to-open-standards-causes-400
https://trello.com/c/YjM40CZ8/117-review-ask-a-question-text-for-clarification-questions
- Fixes the bug where editing a copied DOS3 specialist service wouldn't pass validation (thanks Laurence!)
- Changes the content on the copy form (for the specialists lot only) to make it clear that roles with new questions won't be copied (approved by Stefan)
- Minor edits to the clarification question page content (approved by Stefan - thanks again!)

DOS4 fixes: copy service bug, content updates

---

package.json
yarn.lock

See https://github.com/alphagov/digitalmarketplace-frameworks/pull/585

Pull in DOS specialists fix

---

package.json
yarn.lock

See https://github.com/alphagov/digitalmarketplace-frameworks/pull/586

Pull in Modern Slavery error message fix

---

package.json
yarn.lock

Includes a small tweak to the openStandardsPrinciples question for DOS4.

Update digitalmarketplace-frameworks from 16.0.9 to 16.0.10

---

app/main/views/frameworks.py

trello: https://trello.com/c/8UTKwTO0/218

Use API's slug instead of the one captured by Flask's route

---

Dockerfile

https://trello.com/c/pXed0zB5/

docker base image: bump to 7.0.0

---

app/assets/javascripts/application.js
package-lock.json
package.json

Ticket: https://trello.com/c/lXpy2vZH/142-3-change-footer-to-use-two-column-layout-in-digitalmarketplace-frontend-toolkit-and-all-frontend-apps
http://localhost/suppliers

Change footer layout

---

app/templates/services/_base_edit_section_page.html

trello: https://trello.com/c/k6MF0QE2/196-1-link-position-on-supplier-fe-edit-services-page

fixing the display block bug in edit services parent template

---

app/assets/javascripts/application.js
tests/app/main/test_application.py

https://trello.com/c/Eth9oZbJ/203-disable-ga-cookies-temporarily
Temporarily switching off GA functionality while we review our cookie policy.
See equivalent Buyer FE PR: alphagov/digitalmarketplace-buyer-frontend#970

Exclude analytics from application.js

---

app/main/helpers/services.py
app/main/views/frameworks.py
app/main/views/services.py
requirements-app.txt
requirements.txt

This function got moved to `dmcontent` in the course of https://trello.com/c/g5P0RxQn

count_unanswered_questions: use implementation from dmcontent

---

app/main/forms/suppliers.py
app/main/views/suppliers.py
app/templates/suppliers/create_company_details.html
app/templates/suppliers/create_duns_number.html
app/templates/suppliers/create_your_account.html
tests/app/main/test_suppliers.py

https://trello.com/c/6vSysI7W/248-update-content-on-duns-number-page
* Update create_duns_number.html with content suggestions
* https://docs.google.com/presentation/d/1sukhMNNbGTl3KDYYVedtBcNT5gQliaXjbrGW5Mrf2ak/edit#slide=id.g759a4b2e43_0_2
* Discussion with Nora
* Update error messages on supplier registration forms as per:
* Content guidlines here:
* https://design-system.service.gov.uk/components/error-message/
* Discussion with Nora:
* https://docs.google.com/presentation/d/1sukhMNNbGTl3KDYYVedtBcNT5gQliaXjbrGW5Mrf2ak/edit#slide=id.g759a4b2e43_0_2

248-update-content-on-duns-number-page

---

app/main/__init__.py
package-lock.json
package.json

https://trello.com/c/6UoFALol/266-bring-in-content-to-apps
* Bring G12 content in to supplier frontend

266-bring-in-content-to-apps

---

app/main/views/suppliers.py
tests/app/main/test_suppliers.py

Add the duns number to the suppliers session if skipping the duns flow

BUGFIX-add-duns-to-session-if-skipping-duns-flow

---

app/templates/suppliers/create_confirm_company.html

* Change main_content to mainContent on confirm company page for new govuk template integration

BUGFIX-main_content-to-mainContent-confirm-company-page

---

app/main/helpers/validation.py
app/main/views/frameworks.py
package-lock.json
package.json
tests/app/main/helpers/validation/test_g12_submission.py

https://trello.com/c/EoMme9Md/258-update-questions-in-frameworks-repo-2
See commits
https://github.com/alphagov/digitalmarketplace-frameworks/pull/605/files

258 update questions in frameworks repo 2

---

package-lock.json
package.json

https://trello.com/c/feRizfhu/326-analytics-tracking-id-fix
Pulls in the fix for the Analytics tracking ID: alphagov/digitalmarketplace-govuk-frontend#71

Pull in fix for Analytics tracking ID

---

app/templates/suppliers/dashboard.html

trello: https://trello.com/c/TQ0ZHfSX/328-user-dashboard-side-links-p-to-li

change lists of user action tags from paragraphs to list items

---

config.py
requirements-app.txt
requirements.txt

Simple https://trello.com/c/AVadfnPO

config: rename *_SALT variables to the newer more accurate *_TOKEN_NS

---

app/templates/frameworks/updates.html

trello: https://trello.com/c/ZabEvfWC/337-1-clarification-question-submit-form-link-spacing

enclosing button and anchor in paragraphs

---

README.md
app/main/views/frameworks.py
app/templates/frameworks/services.html
package-lock.json
package.json
tests/app/main/test_frameworks.py

Perform loading of content for lot services outside of loop
Lot is always the same in this view
Benchmarking results show improvement:
https://docs.google.com/spreadsheets/d/1yqdHPAxG1WmXMnAP6BF44jt-vlF_q8PxVsKmBuGhqMs/edit#gid=0

1480-benchmark-suppliers-frameworks-g-cloud-12-submissions-cloud-hosting

---

package-lock.json
package.json

https://trello.com/c/sDLpkbEY/371-declaration-question-mentioning-electronic-signing
See https://github.com/alphagov/digitalmarketplace-frameworks/pull/612

Pull in declaration question change

---

app/main/views/frameworks.py

https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1202 Didn't quite fix the guidance link 🤦‍♀ This is why you shouldn't rush things, folks...

Pass guidance url content to view context

---

Dockerfile

BUGFIX-add-extra-mimetypes-to-docker-image

---

Makefile
requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt

https://trello.com/c/2GcrMr2g/401-ensure-all-repos-have-pip-and-pip-tools-setup-similarly

Pip tools in requirements dev

---

package-lock.json
package.json

https://trello.com/c/hCkxDaNf/1555-change-content-on-providing-suitable-services-page

Update digitalmarketplace-framework from 17.7.4 to 17.8.1

---

package-lock.json
package.json

trello: https://trello.com/c/UFso5MDk/1608-jquery-security-fix

upgrading jquery

---

requirements-dev.in
requirements-dev.txt
tests/app/main/test_services.py

as per suggestion in: https://trello.com/c/l1pT6uUi/92-2-functional-test-for-odt#comment-5eba8aabcd95f253f0ba445a

test ODT file upload

---

app/main/views/frameworks.py

Add missing inline error to legal authority form

add inline error message

---

app/main/views/frameworks.py

https://trello.com/c/Y8E1lAQM/339-update-g-cloud-12-framework-metadata-govuk-links
https://www.gov.uk/government/publications/g-cloud-12-framework-agreement

Update metadata for the framework agreement PDF

---

app/main/__init__.py
app/templates/suppliers/already_completed.html
app/templates/suppliers/create_company_details.html
app/templates/suppliers/dashboard.html
app/templates/suppliers/details.html
app/templates/suppliers/edit_company_registration_number.html
app/templates/suppliers/edit_registered_name.html
app/templates/suppliers/edit_supplier_organisation_size.html
app/templates/suppliers/edit_supplier_trading_status.html
app/templates/suppliers/edit_what_buyers_will_see.html
app/templates/suppliers/registered_address.html
tests/app/main/test_suppliers.py

Trello: https://trello.com/c/WlpUAQZe/327-1-update-supplier-fe-content-for-dos5-application-journey
DOS 5 will soon be upon us. We need to start preparing for it. This includes improving accessibility.
Start applying the suggestions from the accessibility review. Load the DOS 5 manifests so that we can view and test the changes.

Add DOS 5 and start applying accessibility improvements

---

app/templates/suppliers/already_completed.html
app/templates/suppliers/create_company_details.html
app/templates/suppliers/dashboard.html
app/templates/suppliers/details.html
app/templates/suppliers/edit_company_registration_number.html
app/templates/suppliers/edit_registered_name.html
app/templates/suppliers/edit_supplier_organisation_size.html
app/templates/suppliers/edit_supplier_trading_status.html
app/templates/suppliers/edit_what_buyers_will_see.html
app/templates/suppliers/registered_address.html
tests/app/main/test_suppliers.py

Trello: https://trello.com/c/WlpUAQZe/327-1-update-supplier-fe-content-for-dos5-application-journey
DOS 5 will soon be upon us. We need to start preparing for it. This includes improving accessibility.
This PR was originally https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1248, which was reverted due to breaking the build.
This PR must be merged at the same time as https://github.com/alphagov/digitalmarketplace-functional-tests/pull/798 to avoid breaking the tests again.

Start applying accessibility improvements

---

config.py

For now we need to update this allow-list to add new e-signature frameworks.

update e-signature allowed list

---

.secrets.baseline
app/templates/frameworks/_agreement_returned_legal.html
tests/app/main/test_frameworks.py

https://trello.com/c/NutOcwCP/342-2-placeholder-triage-and-fix-e-signature-issues
We were using a Frontend Toolkit summary table on this page - let's replace it with a [Design System Summary List](https://design-system.service.gov.uk/components/summary-list/)!

Replace Legal Documents Summary Table with Summary List

---

app/main/views/frameworks.py
app/templates/frameworks/_agreement_returned_legal.html
app/templates/frameworks/_submitted_services.html

https://trello.com/c/NutOcwCP/342-2-placeholder-triage-and-fix-e-signature-issues
Update text and logic for legal documents section to reflect e-signature. Text agreed with @NoraGDS

changes to legal document section to reflect e-signature

---

package-lock.json
package.json

Trello: https://trello.com/c/yWkgqyPL/325-2-update-dos5-application-content-in-the-frameworks-repo
From https://github.com/alphagov/digitalmarketplace-frameworks/pull/636
Must be merged at the same time as https://github.com/alphagov/digitalmarketplace-api/pull/1058

Pull in updated DOS 5 service questions

---

app/main/views/frameworks.py
config.py
tests/app/main/test_frameworks.py

https://trello.com/c/q5k7renU/435-combine-two-you-have-started-an-application-emails-05
Combine these two emails into one generic one

use generic template for started framework application

---

package-lock.json
package.json

Trello: https://trello.com/c/KZSxuTf1/476-last-minute-dos-5-content-updates
https://github.com/alphagov/digitalmarketplace-frameworks/pull/648

Take updated DOS 5 framework content

---

Procfile
application.py
requirements.in
requirements.txt

https://trello.com/c/kbhJdTm3/567-remove-flaskscript-from-dmutils

Remove Flask-Script

---

app/main/helpers/validation.py

Use set literals and add type hints where I can.

Tidy up validators

---

app/templates/_base_page.html
package-lock.json
package.json

https://trello.com/c/N0tUjqnr/265-2-set-active-styles-on-header-nav-links

Add active links to header

---

app/main/helpers/frameworks.py
app/main/views/frameworks.py
app/main/views/services.py
tests/app/main/helpers/test_frameworks.py
tests/app/main/test_frameworks.py
tests/app/main/test_services.py

Ticket: https://trello.com/c/ex2Bkn90

G12 recovery ticket 3

---

app/main/__init__.py
app/main/views/frameworks.py
package-lock.json
package.json

https://trello.com/c/75hbcRW8/607-3-implement-dos-5-e-signature
Refactor to get contract title from Content Loader rather than hard-coding it.

Get Contract title from content loader

---

app/main/views/frameworks.py
app/templates/frameworks/_agreement_returned_legal.html

https://trello.com/c/75hbcRW8/607-3-implement-dos-5-e-signature
Use contract title variable on dashboard

Use contract title variable in dashboard

---

app/main/views/frameworks.py
app/templates/frameworks/sign_framework_agreement.html

https://trello.com/c/75hbcRW8/607-2-implement-dos-5-e-signature
make less generic to handle different filetype for DOS5

update e-signature file metadata

---

.github/workflows/test.yml

Optimise python caching, based on template https://github.com/alphagov/.github/blob/master/workflow-templates/digitalmarketplace-python-ci.yml

optimise caching

---

package-lock.json
package.json

https://trello.com/c/Hey9OS9t/473-mitigate-registers-switch-off
As part of mitigating registers switch off we want to make sure associated dependencies are up to date.

bump country and territory autocomplete version

---

package-lock.json
package.json

Reverts alphagov/digitalmarketplace-supplier-frontend#1353
Revert this whilst I investigate functional test failure

Revert "bump country and territory autocomplete version"

---

app/templates/suppliers/become_a_supplier.html
app/templates/suppliers/create_company_details.html
app/templates/suppliers/create_your_account.html
app/templates/suppliers/create_your_account_complete.html
package-lock.json
package.json
requirements.txt
tests/app/main/test_suppliers.py

Ticket: https://trello.com/c/Ajssa0oq/890-3-update-content-for-create-a-supplier-account-journey

Update content for create a supplier account journey

---

app/templates/suppliers/create_company_summary.html
app/templates/suppliers/create_confirm_company.html
app/templates/suppliers/create_your_account.html
app/templates/suppliers/registered_address.html

Noticed these while trying to list all outstanding frontend changes in this app.

Remove unused template imports

---

app/main/forms/frameworks.py

Found this while populating the frontend backlog.

Remove unused WTForms forms

---

app/assets/javascripts/category-picker.js

Spotted this unused variable during the course of another story.
There are no references to it in the rest of the codebase.

remove unused variable
