Crown-Commercial-Service/digitalmarketplace-supplier-frontend

- app/status/utils.py
- app/status/views.py
- requirements.txt
- tests/app/status/test_status.py
API Client now handles exceptions and errors, meaning that _status routes for our frontend apps need less logic.  Removed the try/catch stuff.
Also updated dmutils tag.
> Pull out `_status` error handling into dmutils

- app/main/login.py
Where the API client has changed the format it returns users in this
method should have changed to not try to dereference the ["users"] element here.
> Fix user login bug

- config.py
This is in an attempt to get login working. Flask should use the host
name instead.
> Remove SESSION_COOKIE_DOMAIN

- app/__init__.py
- app/main/helpers/email.py
Addresses this bug: https://www.pivotaltracker.com/story/show/94091430
By adding ProxyFix the headers are correctly passed through to the app, so that it will know
if the original request was from an http or https context.
This is the same way it is done in the data API project for generating URLs.
> Make `url_for` use the correct scheme (http/https)

- app/assets/scss/application.scss
- app/templates/macros/_breadcrumbs.html
- app/templates/services/dashboard.html
- app/templates/services/services.html
- gulpfile.js
- tests/app/main/test_services.py
This commit adds our standard breadcrumbs, with placeholder text where the real data is not yet available in the app.
> Add breadcrumbs to supplier app

- app/templates/services/dashboard.html
On the dashboard, make the services link relative so that it points to
the correct environment.
Fixes: [94162812](https://www.pivotaltracker.com/story/show/94162812)
> Make service link relative

- requirements.txt
https://github.com/alphagov/digitalmarketplace-utils/compare/0.7.0...0.10.2
Changes are mostly bug fixes or for the buyers app.
> Bump DM utils to 0.10.2

- app/__init__.py
- config.py
- requirements.txt
AWS ELBs set the X-Forwarded-Proto to HTTP if they're configured port
80 -> 80. Because the apps are now internal and served over HTTP we lose
the X-Forwarded-Proto that is sent by Nginx. This change allows the HTTP
protocol to be configured per environment while still making use of
flasks ProxyFix middleware.
> [#94292928] Integrate custom proxy fix

- .travis.yml
- app/assets/javascripts/_analytics.js
- bower.json
- gulpfile.js
- package.json
- tests/app/main/test_application.py
Part two of this story to add the tags to both buyer and supplier apps
(paired with https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/59):
https://www.pivotaltracker.com/story/show/94570480
Uses the new Google Analytics API from the govuk front-end toolkit:
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/analytics.md
> Tag buyer apps with analytics tags

- app/main/services.py
- app/templates/services/dashboard.html
- tests/app/main/test_services.py
Talked with Cath and Nicole and @minglis today; everyone agreed to go ahead with this this time.
Basically, this request:
* Removes 'Edit' / 'Details' links on the Supplier dashboard
* Disables routes to view/change a Service's status in the app
* Refactors the tests
[Last pull request has all the details, including a screenshot.](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/37)
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/94826380)
> Remove ability for Suppliers to edit status of their Services

- app/templates/errors/404.html
- app/templates/errors/500.html
- tests/app/helpers.py
- tests/app/main/test_services.py
- tests/app/test_application.py
Bringing the error pages into line with those on the buyer app.
- Please note there is an issue currently where API errors cause an internal server error to be displayed NOT the error template.
- This is because whilst rendering a template Flask-Login tries to confirm the user - fails (API error) and throws an error - preventing the template rendering.
- Propose we merge this (as this issue is preexisting) and I'll add a story to fix in another way.
> Error pages

- tests/app/test_application.py
The services/{:id} one is deprecated
Using dashboard instead
> Use different endpoint for 500 tests

- app/templates/_proposition_header.html
Currently "Logout" link is shown on all pages, whether or not there is any user logged in.
This only shows "Logout" if there is a user logged in, or the "Supplier login" link (same as the buyer app) otherwise.
> Show log-in for logged-out users and log-out for logged-in users

- requirements.txt
`get_version_label` in dmutils tries to call the wrong file because it's looking for a local path. 
Refactored so that each app passes its path as a parameter to `get_version_label` in dmutils.  
Should work, but currently breaking until pending pull request in [digitalmarketplace-utils](https://github.com/alphagov/digitalmarketplace-utils/pull/51) gets merged.
> Pass pathname to `get_version_label` in dmutils

- app/status/views.py
- config.py
- requirements.txt
Instead of reading the file each time in the /_status endpoint, we can just initialise it when the app starts and then reference it later.
Removed `basedir` variable because it wasn't being used anywhere.
Depends on [open pull request in digitalmarketplace-utils](https://github.com/alphagov/digitalmarketplace-utils/pull/53)
> Set version in config.

- README.md
- app/assets/scss/application.scss
- app/templates/_stylesheets.html
- application.py
A fix for this bug:
https://www.pivotaltracker.com/story/show/96536196
The stylesheets weren't being included in the page so it was breaking in IE8 and down.
It now looks like this:
> Fix ie8 alignment

- .gitignore
- app/assets/scss/application.scss
- app/templates/services/dashboard.html
- application.py
- bower.json
- gulpfile.js
- package.json
This pull request gives the app the ability to use templates from the Digital Marketplace frontend toolkit.
--
Dependency management is handled by Bower (for now).
The template files are copied into the `app/templates/` folder (and I've done some refactoring of how we copy files with Gulp).
Using the templates required turning on [Jinja's with extension](jinja.pocoo.org/docs/dev/extensions/#with-extension).
One example (using the `page-heading` design pattern) is implemented on the dashboard page.
> Use templates from the Digital Marketplace frontend toolkit

- requirements.txt
New version of digitalmarketplace-utils requires FeatureFlags in a more normal fashion and so we can lose the dependency on a custom forked FeatureFlags repo.
> Require new version of digitalmarketplace-utils

- gulpfile.js
- Gulp was trying to compile the CSS before it had copied the files from the toolkit
- Make sure that the order of tasks is always
- clean (delete the old stuff from `app/static`)
- copy (stuff from the toolkit into the app)
- compile (put munged stuff in `app/static`)
> Fix CSS not getting generated on clean checkout

- README.md
- application.py
- scripts/run_app.sh
It's not needed as explained in alphagov/digitalmarketplace-buyer-frontend#74 but it's useful to be able to specify the host when running the `scripts/run_app.sh` script so this also adds that.
> Remove DM_HOST variable

- app/main/forms/auth_forms.py
- app/main/login.py
- app/templates/auth/reset-password.html
- tests/app/main/test_login.py
The reset-password form was wrongly including the email address and user ID as hidden form fields.  They are now only encoded in the token, so that it can't be hacked.
> Fix reset password flow

- app/__init__.py
- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- app/main/__init__.py
- app/main/errors.py
- app/main/forms/suppliers.py
- app/main/views/login.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/macros/forms.html
- app/templates/services/list_services.html
- app/templates/services/service.html
- app/templates/suppliers/dashboard.html
- app/templates/suppliers/edit_supplier.html
- bower.json
- config.py
- gulpfile.js
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
- tests/app/test_application.py
Pivotal: [#95432162](https://www.pivotaltracker.com/story/show/95432162)
Includes supplier and account information and links to service list and supplier info edit pages.
There's no service counts since API doesn't return them with supplier data yet.
Renames services.dashboard view and template to list_services.
Adds a breadcrumb link to the new supplier dashboard.
Allows editing supplier and main contact details. There's no validation apart from form field limits, data is sent to the API and the response "error" message is displayed if the request fails or returns 400.
Things that are missing compared to dm-prototype design: last edit date, since it's not returned by the API yet
Missing SECERET_KEY env variable should always prevent the app from working, otherwise errors in production …
> Edit supplier and contact information page

- config.py
- tests/app/main/test_login.py
Instead of having our secure cookies set to `False` and then explicitly set as `True` in a Live environment, it's better to assume secure cookies and explicitly unset them where needed.  
This is how it's been done [in the admin app](https://github.com/alphagov/digitalmarketplace-admin-frontend/pull/66/files), at any rate.
Also added a test to confirm secure cookies are enabled.
> Sync secure cookie config with admin app

- .gitignore
- app/assets/javascripts/application.js
- app/templates/_base_page.html
- bower.json
- config.py
- gulpfile.js
- scripts/build.sh
- scripts/run_tests.sh
This commit uses Gulp to copy the GOV.UK template HTML file into `app/templates` as part of the frontend build process.
The main reason to do this is so that we don't have to package up the `bower_components` folder when deploying to AWS.
> Copy GOV.UK template into the project folder

- app/templates/auth/reset-password.html
Fixes this bug: https://www.pivotaltracker.com/story/show/96536526
Previously if there were errors on both fields (i.e. "Password" and "Confirm password") the messages were in the wrong order (alphabetical ordering made them the opposite way round from on the page).  By reversing the alphabetical ordering we can guarantee that two errors will be displayed in the same order as the fields on the page.
> Put validation errors in the right order

- gulpfile.js
This copies the Gulpfile from [the admin frontend](https://github.com/alphagov/digitalmarketplace-admin-frontend/pull/67) to keep all the Gulping synchronized.
> Name things more clearly in Gulpfile

- requirements.txt
- tests/app/main/test_login.py
- tests/app/test_application.py
Upgrading to new verison of dmutils which initiates each app with the `X-Frame-Options` header set to `DENY`.
Also added test to confirm.
> Deny third-party sites from embedding in an iframe

- app/assets/scss/application.scss
- gulpfile.js
- scripts/run_tests.sh
We have had problems with builds going through and getting deployed without any stylesheets.
This commit addresses that issue by causing `./scripts/run_tests.sh` to fail if the SASS compilation doesn't complete.
This means that problems will be picked up locally or on Travis before they reach deployment.
--
> Fail the build if SASS doesn't compile

- app/main/views/services.py
Previously, the content was sourced from the `bower_components` folder. It is now copied to `app/content`, and `bower_components` is no longer packaged when deploying to AWS.
> Stop relying on presence of bower_components

- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- requirements_for_test.txt
- tests/app/main/test_login.py
Login forms and (non-hidden) input elements belonging to them are checked for `autocomplete=off` attribute, which, somewhat intuitively, prevents browsers from autofilling their content.
Demoed to Martyn and I'll have to do the same thing for the Admin App, so let me know if you have any suggestions for improvements before I do the other one.
[>> Comment ("5.21 disable autocomplete on logins") in story on Pivotal](https://www.pivotaltracker.com/story/show/96550136)
> Disable autocomplete on logins.

- app/main/views/services.py
- app/section_order.yml
- app/templates/macros/toolkit_forms.html
- app/templates/services/edit_section.html
- app/templates/services/service.html
- bower.json
- requirements.txt
- tests/app/main/test_services.py
_Fulfills [95430642](https://www.pivotaltracker.com/story/show/95430642)_
This pull request, [using the new dmutils features](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/71) and templates from the toolkit:
- adds a `GET` endpoint for `/services/<id>/edit/<section>`
- renders form fields with prefilled values for the above four questions, using templates from the toolkit
- adds a `POST` endpoint for the same, which takes the edited values and
- if the API returns successfully redirects back to the service summary page
- if the API returns an error then it will be displayed back to the user
It doesn't, yet, do any per-field validation of edits.
> Edit existing service

- app/templates/suppliers/dashboard.html
[#97275278](https://www.pivotaltracker.com/story/show/97275278)
Requires alphagov/digitalmarketplace-api#150 
Displays the service counts as reported by the API.
There are no framework dates since we don't return them from the API yet
G-Cloud 7 "now open" block will be a part of @robyoung's pull request.
> Add framework service counts to the supplier dashboard

- app/main/helpers/email.py
- app/main/views/login.py
- app/templates/auth/request-password-reset.html
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_login.py
Password reset tokens, once issued, would be valid for 24 hours.
This meant that all generated tokens could be used for the full 24 period without discrimination.
Added some logic to disallow tokens that were created _before_ a user's password was last changed and added a test to check.
Also created a new method that isolates token verification logic.
Also also replaced calls to `Mock` with mock.patched objects for our login tests because apparently that's a better way to go.
[>> Task ("Password reset tokens can be used multiple times") in story on Pivotal](https://www.pivotaltracker.com/story/show/96550136)
> Prevent unwanted reuse of password reset tokens.

- app/main/views/suppliers.py
- app/templates/suppliers/dashboard.html
- config.py
[#97275278](https://www.pivotaltracker.com/story/show/97275278)
Enables dashboard edit in preview, staging and production.
Hides the "Edit" button next to the "Supplier information" and disables the /suppliers/edit page.
> [#97275278] Enable supplier dashboard

- app/main/views/services.py
- app/templates/services/_edit-status.html
- bower.json
- tests/app/main/test_services.py
Our public/private service status update form was just plain HTML, which meant that it risked becoming outdated as the toolkit evolved.
Also changed the `service_status` name to `status` as it would appear in the JSON response for a service.
Also resolved a bug where if you caused an error while trying to update your status, you wouldn't get the correct page back.
> Swap out HTML service status update form for toolkit-generated form.

- README.md
- app/main/helpers/email.py
- config.py
This adds an environment variable for the S3 bucket we want to use for uploading draft documents. It does not actually do any uploading yet because that will use the existing S3 upload from dmutils.
When adding the config I noticed a few old configs that could be cleaned up as well.
> [# 97631008] Add draft documents S3 and prune config

- app/new_service_manifest.yml
- app/templates/macros/answers.html
- bower.json
This pull request:
- matches [the order and groupings used in the Grails app](https://github.gds/gds/digitalmarketplace-frontend/blob/c7a901c6cd9b7c53db21b4dbe3b6717c62e1e7b4/grails-app/views/marketplace/listing/_G6Listing.gsp) for displaying services
- does just enough to stop the above throwing template exceptions when viewing a service
--
It does not:
- display all the service data perfectly (it especially has trouble with questions that have an assurance component)
- do any integration with the draft services stuff
--
> Put all service attributes in the manifest for new services

- app/main/views/services.py
- app/templates/macros/toolkit_forms.html
- app/templates/services/edit_section.html
**NOTE**: This requires validation error responses from the API, which are added in this pull request: https://github.com/alphagov/digitalmarketplace-api/pull/159
This prevents updates with validation errors from being saved, and displays validation errors on the form.
In-line messages are no properly mapped to all possible validation errors - it could be easily done for this small set of fields, but it will be better to harmonise with the messaging mechanism used for SSP flow once it exists.
For now the validation message shown is the last in the list of `validations` for the question in SSP content.
There seems to be some issue with the width of the "Edit service" form - @quis can you help with that at all?
> [#97502388] Service updates: Respond to validation errors returned by the API

- config.py
Requested by Cath for preview, but is turned on for all live
environemnts. We'll need to go through the list of feature flags as
part of the go-live plan.
> Enabled supplier service edits in Live

- app/templates/suppliers/dashboard.html
- tests/app/main/test_suppliers.py
This commit does two things:
- changes 'Services' to 'Current services', to make it clear that this is not where G-Cloud 7 services will appear
- adds a message for the case where a supplier doesn't have any current services (preferable to hiding this section entirely because it shows where new services will, eventually, appear)
> Make dashboard handle supplier with no services

- app/assets/scss/_framework-application.scss
- app/assets/scss/_text.scss
- app/assets/scss/application.scss
- app/templates/_proposition_header.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/declaration.html
- app/templates/services/create_new_draft_service.html
- app/templates/services/edit_section.html
- app/templates/services/list_services.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
- app/templates/suppliers/dashboard.html
- app/templates/suppliers/edit_supplier.html
- bower.json
This pull request:
- rationalises breadcrumbs based on observations in the lab (mostly replacing _supplier name_ with _your account_)
- adds page `<title>`s to pages that didn't have them
- adds some extra UI elements to the 'Apply to G-Cloud 7' page, without hooking them up to any functionality (or any references to real dates!)
Before | After
--- | ---
> Various UI tweaks ahead of submissions

- app/main/views/services.py
- app/new_service_manifest.yml
- app/templates/macros/toolkit_forms.html
- app/templates/services/edit_section.html
- bower.json
- config.py
NOTE: This depends on code in the following two pull-requests to work: https://github.com/alphagov/digitalmarketplace-api/pull/166 and https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/99
It will need an update to the frontend toolkit version number, once the toolkit PR has been merged.
This pull-request is another step on the way to completion of: https://www.pivotaltracker.com/story/show/97275662 and https://www.pivotaltracker.com/story/show/96551096
What this PR does:
* move all service creation endpoints under the single feature flag GCLOUD7_OPEN
* starting from `/suppliers/submission/g-cloud-7/create` you can choose Lot 4 (SCS) and it will create a new draft service for the logged-in supplier.
* You can add details for each of the pages right through the flow up to …
> [#97275662] Create SCS draft services

- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- app/templates/suppliers/dashboard.html
**This pull request is based off #89. It will need rebasing against master once #89 is merged.**
This adds a link to the supplier's homepage when the framework is open.
The type size of the link is a touch too big, but there's some rationalisation of the browse list pattern to be done at a later date.
--
It also adds links between the _Apply to G-Cloud 7_ page and the _Add service_ page.
> [WIP] Add 'Apply to G-Cloud 7…' link

- app/main/views/services.py
- app/new_service_manifest.yml
Now we have more than one possible lot we need to use the specific `serviceTypes` for each lot.
Once this and the corresponding API pull-request is merged we'll be able to create drafts for any lot and work through the flow up as far as questions with assurance, which will not validate yet (as the assurance questions don't yet exist on the pages).
> [#97631082] Use specific serviceTypes for SaaS, IaaS, SCS

- app/assets/scss/_framework-application.scss
- app/templates/frameworks/dashboard.html
The intention of this is to add the following semantics:
- the help section being identified as content [tangental](http://www.w3.org/TR/html5/sections.html#the-aside-element) to that in the main block
- the information about the need for a declaration being its own section
- emphasis around the need for a declaration
It also breaks the information about the deadline into 2 lines to allow its date to sit on it's own.
> Refactor the framework summary HTML

- app/templates/_footer_categories.html
Crown Commercial Service's (CCS) website has transitioned to GOV.UK, and
uses Bouncer - a GOV.UK project - to redirect users from the old URL to the
new GOV.UK one. In this instance, Bouncer responds to requests for
https://ccs.cabinetoffice.gov.uk by sending a HTTP 301 in the response to
send users to
https://www.gov.uk/government/organisations/crown-commercial-service.
One thing that Bouncer explicitly doesn't do is hold SSL/TLS certificates
for domains external to GOV.UK, because that adds additional burden on to
the whole notion of URL redirection. As such, users will get an SSL
certificate error when they click the link to go to the CCS website in the
Digital Marketplace because the SSL certificate presented is for GOV.UK, not
the Common Name of the host header value - …
> Update links to CCS

- app/status/views.py
- tests/app/status/test_status.py
This is too alllow a check simply on the status of this app without hitting it's dependecies
- supply query param of ignore-dependencies
/_status?ignore-dependencies
And the app will return a simply 200 JSON response. Allows us to use this with amazon load balancers, without impacting DB/Search performance on the periodic checks.
> Added ignore dependencies option to status

- .ebextensions/apache_log.config
- .ebextensions/cwl-logs-apache-access.config
- .ebextensions/cwl-logs-application.config
Create a new Apache access log with type and application information in
so that we can distinguish where a log message has come from. The
CloudWatch metric filters are applied to all messages in a log group and
seeing as we put all our log streams in the same group so that we can
easily search over them this means our alarms do not work properly.
This change also updates the alarm descriptions to be a bit more
helpful. They now say which application and environment the alarm came
from and link to the manual explaining what should be done.
This adds an alarm that fires if there are more than 10 failed logins in
a 5 minute period. This may not be ideal but after discussion @minglis
and I decided that this would be good enough as first stab.
> Fix http status monitoring

- app/assets/javascripts/_analytics.js
This commit makes the app select different Google analytics properties to track
against depending on which domain the user is browsing.
This will ensure continuity of analytics when we switch the DNS.
Sister of https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/101
> Use correct analytics properties for live/other

- app/templates/_cookie_message.html
- tests/app/test_application.py
- seen cookie message pointed to GOV.UK
- changed to use /cookies
- note on local builds this will not work as cookie pages served from buyer app
> Ensure cookie page uses local cookie page

- bower.json
Updates GOV.UK template to bring in https://github.com/alphagov/govuk_template/pull/164
Depends on https://github.com/alphagov/govuk_template/pull/165
Addresses [story 98957756](https://www.pivotaltracker.com/story/show/98957756)
> Fix &copy; in footer (should be ©)

- requirements.txt
We're making an API change that would cause an error.
But if we have the we have the new version of dmutils, there won't be an error.
> Update dmutils so that underlying API change doesn't break anything.

- app/templates/services/list_services.html
Currently the "view service" link in the admin app always points at live. It should be relative to the environment that the app is being used it (so that it can be tested).
Actual: https://www.digitalmarketplace.service.gov.uk/service/5126395806089216
Expected: https://preview.development.digitalmarketplace.service.gov.uk/service/5126395806089216
Similar to: https://www.pivotaltracker.com/story/show/94162812
> Make link to service relative to environment

- app/assets/scss/application.scss
- app/templates/suppliers/dashboard.html
- bower.json
Brings in: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/116
Brings in: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/118
Requires merging before https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/112 can be deployed.
> Make supplier account page use new tables

- gulpfile.js
To answer a request for the gulpfile to be aligned across our front-end apps.
https://github.com/alphagov/digitalmarketplace-buyer-frontend/commit/fd86738d38240e825ba40011f678e0112a0473cc#commitcomment-12323019
> Add Gulp task to copy over GOVUK toolkit images

- app/templates/services/service.html
- app/templates/services/service_submission.html
Replaces `<table>` with summary-tables macro call.
This still uses the local `answers` macros for the field types, but
wraps them with the `summary.field` `<td>`s.
`answers` macros could be moved to the summary pattern so that the
`<td>` wrapping is built-in in the macros.
> Update service and submission sections views to use the summary pattern

- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Requires https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/114
[#97536644](https://www.pivotaltracker.com/story/show/97536644)
"Make a copy" copies a draft using the API copy endpoint.
Draft is requested first to check that the draft supplier matches
the currently logged in user.
> Add G7 drafts list with "Make a copy" button

- app/templates/services/list_services.html
- Service IDs are stored as uppercase
- Old URLs may be in lower case but they are in the `/services/x-xxx-xxx` format,
and the redirect uppercases them to `/g-cloud/services/X-XXX-XXXX`
> Don't lowercase service IDs

- app/main/views/services.py
- app/templates/macros/toolkit_forms.html
- app/templates/services/edit_section.html
- app/templates/services/service_submission.html
- bower.json
- tests/app/main/test_services.py
See: https://www.pivotaltracker.com/story/show/97631142
This adds a hidden field to `edit section` pages that lists all the questions on the page.  This way the API can check if there were required fields on the page that have not been submitted with the form, and if so return a validation error for the page.
It also adds a `percentage` macro to display the percentage box for the "service uptime" question.
> [#97631142] Validate required questions per page

- app/templates/services/service.html
The URL parameter was changed from section to section_id.
> Fix URL parameter name in link generation

- app/main/views/services.py
- app/templates/services/_base_edit_section_page.html
- app/templates/services/_base_service_page.html
- app/templates/services/edit_section.html
- app/templates/services/edit_submission_section.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
Refactor the service overview and edit section templates for services and service submissions so that they inherit from common base templates. This means that we have less duplication and can avoid passing configuration variables into the templates. It does add a bit of indirection that may make the templates less obvious.
> Service use template inheritance

- app/templates/macros/forms.html
- app/templates/suppliers/edit_supplier.html
Fixes `"None"` strings in address/contact input fields by setting
`value=value or ''`. Jinja renders missing variables as empty
strings, but "None" gets converted to string. We've only seen this
happen with contact details since other fields shouldn't have `None`
values.
There's an interesting interaction between macros and the context of
variable-based pattern templates: macro arguments are visible to the
included template as normal variables, so as long as macro argument
name matches the variable name used by the pattern template there's
no need to set it using `{% with name=name %}`.
> Rewrite supplier edit forms with toolkit form patterns

- app/main/views/suppliers.py
- tests/app/test_application.py
The 503 test needed to stub out the `get_supplier` method because it is the only method of the API client the view code for the base ('/') suppliers route calls.
In addition to that, failed requests handled by the API Client return instances of the `HTTPError` class, not its derived class, `APIError` so the existing code behaved unpredictably.
> Updated 503 tests

- bower.json
Dashboard was throwing a 500 for suppliers with clients.
This was because of a mis-named variable in one of the toolkit templates, fixed in:
https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/127/files
This commit updates the toolkit version to include the fix.
> Include fix for bug with toolkit summary tables

- app/templates/users/list_users.html
Accidentally a word in the `list_users` template.
It doesn't cause any practical problems at the moment, but it could eventually.
> Fix variable name in template

- app/__init__.py
- app/main/helpers/services.py
- app/main/views/services.py
- app/new_service_manifest.yml
- app/templates/frameworks/dashboard.html
- app/templates/services/_base_edit_section_page.html
- app/templates/services/submission_document.html
- config.py
- requirements.txt
- requirements_for_test.txt
- scripts/run_app.sh
- tests/app/main/test_services.py
Validates files using dmutils to check file size and document type
and uploads to S3 if there were no errors.
Uploaded file URLs are sent to the API with the rest of form data
for validation.
If other fields fail validation the form is displayed again with
errors.
If other form fields on the same page fail validation the file
has to be attached again, so file URLs shouldn't be added to the
form data.
File URLs shouldn't be submitted directly since there's no validation
that the URL matches the file uploaded to S3.
Draft bucket is intended for drafts that don't yet have a service ID.
Since the documents will have to be copied when the draft gets a
service ID storing them separately makes it easier to clean up
unused files after the framework goes live and makes sure the files
are not …
> Documents upload

- app/assets/scss/_assurance-question.scss
- app/assets/scss/application.scss
- app/main/helpers/services.py
- app/main/views/services.py
- app/templates/macros/assurance.html
- app/templates/services/_base_edit_section_page.html
- app/templates/services/_base_service_page.html
- app/templates/services/edit_submission_section.html
- bower.json
- requirements.txt
_Depends on https://github.com/alphagov/digitalmarketplace-utils/pull/121_
--
For each applicable SSP question this pull request:
- displays the correct set of radio buttons for the user to choose their assurance approach
- `POST`s the users selected assurance approach back to the API
_The UI and markup aren't ideal at the moment, especially because the red validation border isn't scoped properly. But it's at least something we could put in front of users tomorrow._
It also fixes a problem where 'Service availability' couldn't be saved because it wasn't getting coerced to a number before being posted to the API.
This pull request also implements the 'Answer required' message for a draft service:
> Allow editing of assurance questions

- app/templates/frameworks/dashboard.html
- app/templates/macros/answers.html
- app/templates/macros/toolkit_forms.html
Ralph suggested that document upload and draft section view pages
should show "A document was uploaded" instead of the info URL for
uploaded G7 documents.
Since we use the same macros and toolkit templates for both live
and submission services (and there's no easy way to split them
that I can think of) this adds an additional check to the `upload`
macros that checks if the document is attached to a submission
draft (by checking that the URL starts with an "info" URL prefix).
Also removes quotes from the "service copied" message
> Hide submission document urls

- app/new_service_manifest.yml
- tests/app/main/test_services.py
We don't want users to be blocked part-way through completing details of a service because they don't have the right document to hand.  By putting documents at the end of the question flow they can answer all questions without having the documents to upload.
> Move file uploads to the end of the question sequence

- app/templates/suppliers/dashboard.html
Works better with account creation to show information we’ve asked for first.
> Order of supplier details on supplier account

- app/assets/scss/application.scss
- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- app/templates/services/_base_service_page.html
- app/templates/services/service_submission.html
- tests/app/main/test_services.py
See: https://www.pivotaltracker.com/story/show/100216314
This adds a "Delete this service" button at the bottom of draft service pages.
When clicked the page is reloaded with an "Are you sure?" button at the top of the page.
When this second button is clicked the draft is deleted and the user redirected to the G-7 dashboard.
The story specifies that deleting drafts should be audited - this is already taken care of in the API endpoint so no further work needs to be done on that - see screenshot for example audit events:
> [##100216314] Delete draft service button

- .buildpacks
- Procfile
- README.md
- application.py
- package.json
This adds the changes @minglis put together for running frontend apps in heroku. The intention is to separate it out from the pull request on supplier declarations.
Other than adding heroku specific things like buildpacks, Procfile and README changes this also includes;
- Allow the port the app runs on to be controlled by an environment
variable
- Bind to 0.0.0.0 rather than the default 127.0.0.1
- Change how the npm post install is called
> Make Heroku-friendly

- app/templates/services/_base_edit_section_page.html
Used to say ‘Return to service’ now says ‘Return to service summary’.
> Back link from editing a service

- app/templates/suppliers/dashboard.html
Markup for the 'contributors' section of the dashboard didn't have the same `column-one-whole` tags as the rest of the sections.
Upon further discussion, all of those tags were unnecessary.
> Standardise markup for supplier dashboard.

- app/templates/suppliers/dashboard.html
One of the tables had the wrong caption.
Probably the first time CPDD has proved to be problematic.
> Fix caption on supplier dashboard

- app/main/helpers/services.py
This was causing a KeyError on the Service type page because the field name `serviceTypes` isn't really a question. There are specific question types for each of the different lots.
> BUGFIX: serviceTypes isn't a real question

- app/assets/scss/_framework-application.scss
- app/assets/scss/_grids.scss
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- bower.json
The changes in this pull request mostly follow [Ralph's prototype](http://dm-prototype.herokuapp.com/new-framework-service-complete).
It passes some extra information to the templates, for trying out the different combinations.
They are:
- whether the declaration has been made <sub>mocked</sub>
- count of complete services <sub>mocked</sub>
- count of draft services <sub>real</sub>
--
--
--
--
--
:phone: | :phone: |
--- | ---
--
[#100515606](https://www.pivotaltracker.com/story/show/100515606)
> Change design of "Apply to G-Cloud" page

- app/templates/frameworks/services.html
- app/templates/services/_base_service_page.html
- app/templates/services/edit_section.html
- app/templates/services/edit_submission_section.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
- Finish removal of supplier name in favour of "Your account"
- Show hierarchy of where you are in the G-Cloud 7 application process
> Tidy breadcrumbs and nameless services

- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- tests/app/main/test_services.py
Previously all services were on the dashboard.
Now that they are on a separate page it makes sense for said page to be where the user sees the messages for 'deleted' and 'copied'.
It also feels like the next thing they do after deleting or copying a service would be accessible from the services page.
> Go to services page after 'delete' and 'copy'

- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- config.py
- scripts/run_app.sh
- scripts/run_tests.sh
- tests/app/main/test_services.py
[#100213582](https://www.pivotaltracker.com/story/show/100213582)
Similar to submission service documents, /download-supplier-pack
generates a temporary signed S3 link for the supplier pack.
Supplier pack S3 path is always set to `g-cloud-7-supplier-pack.zip`.
`g-cloud-7` prefix allows to use a single location prefix in assets
nginx to redirect all relevant G7 URLs to the draft bucket.
Versioning is not implemented, but could achieved by relying on
`dmutils.s3.S3.move_existing` during service pack uploads, although
copied file name should use suffix instead of prefix to keep the
`g-cloud-7-...` name/location pattern if old versions need to be
accessible through the assets domain.
Supplier pack "last updated" date is static, but could be wired to
the S3 object "last modified" timestamp in …
> Add ITT supplier pack link endpoint

- app/declaration_manifest.yml
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/edit_declaration_section.html
- bower.json
> 1. Could we add in some (slightly edited) introductory copy at the top of the supplier declaration page that says:
>
> You must complete this declaration for your services to be eligible for G-Cloud 7 submission.
>
> ~~2. The links aren't working in the hint text. If we can't fix, let me know and I'll change the format in the hints.~~
>
> 3. Can we change the link at the bottom to say 'Return to G-Cloud 7 application'?
>
> 4. ‘Terms of participation’ header => G-Cloud 7 essentials
>
> 5. Exactly the same as current q56, we need to add a why box for questions 41-53
> If you responded yes to any of questions 41-53, please provide details of any mitigating factors that you think should be taken into consideration.
>
> 6. Change order of questions 3-5
> 5 => 3
> 3 => 4
> 4 => 5
>
> 7. Move …
> Changes to declaration from John Willams

- app/assets/scss/_updates.scss
- app/assets/scss/application.scss
- app/main/views/frameworks.py
- app/templates/emails/clarification_question.html
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/updates.html
- config.py
- tests/app/main/test_frameworks.py
**Still waiting on Roz's copy edits, but feel free to code review in the meanwhile.**
This pull request adds in an 'G-Cloud 7 updates' page from which a logged-in supplier can ask a tender question.
Empty questions are prohibited, as are questions that are too long (500+ words or 5000+ characters), but anything else is allowed.
The actual email address we're sending to is stored behind a new `DM_CLARIFICATION_QUESTION_EMAIL` config variable so that we don't have any meddlesome troublemakers asking lots of questions illicitly.
Needs the Mailchimp API key before it properly sends emails.
Lists of documents (based on [Ralph's prototype](http://dm-prototype.herokuapp.com/updates)) are quite rough still, but the skeleton is more or less in place.
<sup>Anyway, @quis said he'd look at it.</sup> …
> [#100214390] Email Clarification Questions from "updates" page

- app/assets/scss/_service-status.scss
- app/assets/scss/application.scss
- app/templates/services/list_services.html
- app/templates/services/service.html
- bower.json
Add a 'view service' button from the admin app to the page for editing a current service
--
Add a 'view service' link to the table of current services and changes the name-of-service link to point to the edit page and simplifies the table of current services to show either the 'bad' status (private/removed) _or_ the link to view the service
> Align current service editing with SSP

- app/declaration_manifest.yml
- app/main/helpers/frameworks.py
- bower.json
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
Based on feedback this morning from CCS.
- **CCS edits 12/08/15**
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/56
- **Add missing questions**
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/57
(this involves additional Python to include these extra questions in validation and tests)
- **Fix spelling mistake**
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/58
**Allow users to not answer checkbox questions**
For cetain questions users are supposed to tick all the checkboxes that apply. It may be the case that none of the checkboxes apply, therefore to not tick them is a valid response (even though it will bar them from getting on the framework).
We may, at a later stage, change the validation to give an error if the user _doesn't_ tick …
> Updates to content of declaration questions

- app/templates/suppliers/dashboard.html
All of our other summary tables have the table header as the caption.
The "Contributors" table should too.
This change affects the [functional tests](https://github.com/alphagov/digitalmarketplace-functional-tests/pull/53) I've written, so I've labeled that PR as `[WIP]` until this goes through.
> Fix summary table caption on supplier dashboard

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/suppliers/dashboard.html
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
When a user clicks the 'Apply to become a G-Cloud 7 supplier' link on the supplier dashboard this registers their interest in the framework. This in turn will result in them going on an email list for framework information and changes the dashboard link.
> Register interest in framework

- app/assets/scss/_service_submission.scss
- app/assets/scss/application.scss
- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/new_service_manifest.yml
- app/templates/frameworks/services.html
- app/templates/services/_base_edit_section_page.html
- app/templates/services/edit_submission_section.html
- app/templates/services/service_submission.html
- bower.json
- tests/app/main/test_services.py
Sends the service id to the API to mark the service as "completed"
and redirects to the draft services page.
Shows "service was completed" message on the services page.
Since services without names are not shown in the service list
saving the service name should be as simple as possible and
shouldn't require a value for the service summary.
Drafts without a name won't appear in the drafts list, so it shouldn't
be possible to input any other data until the draft name is set.
Hiding the links for unnamed drafts means there's no way to get to
the draft sections page before entering the service name.
Section editable flag affects whether section "Edit" link is visible.
But it was still possible to open the section edit page for non-editable
sections and the changed data was validated and …
> Complete draft

- app/templates/services/service_submission.html
@quis:
Need to speak to @ralph-hawkins about this, but I think we need a line under the complete button
that says something like "You can still edit services once they're complete".
Otherwise we'll probably have a situation where everyone waits until the last minute to complete
their services, just in case they want to make changes.
> Add a "you can still edit" hint after "Move to complete" button

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
- Supplier creation only provides name, duns, email and phone.
- Current edit page expects a description
- Also expects postcode to be present
This removes those requirements.
> Ensure edit page can handle the reduced data from create supplier

- app/main/views/frameworks.py
Using an empty iterator in the summary-table renders an empty table
instead of empty message text since `{% if items %}` returns True
even for empty iterators.
> Fix empty drafts list layout bug

- app/assets/scss/_service_submission.scss
- app/templates/services/service_submission.html
Overwrite the new .button-save "margin-top: 45px" for the "Move to
complete" button on the service submission page.
> Fix margin-top on the "Move to complete" button

- tests/app/helpers.py
- tests/app/main/test_login.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Refactor the login method method that it only mocks the login `data_api_client` for the duration of the login so that other tests on the same views module are not affected. The mocking of get_user method in a more aggressive way stays the same because it is needed for subsequent
requests. However, it is now cleaned up in the teardown.
This change also updates all the tests to use the same login method. Some tests had replaced the core one in an attempt to allow testing of the things it was mocking. This should no longer be necessary.
> Refactor tests login method

- app/main/views/login.py
- requirements.txt
- tests/app/main/test_login.py
See: https://www.pivotaltracker.com/story/show/100210316
This covers invitations sent from the supplier frontend.
> [#100210316] Add audit logging for invite-user

- app/main/views/login.py
- tests/app/main/test_login.py
See: https://www.pivotaltracker.com/story/show/101485630
The API client expects a string rather than an Enum object.
> [#101485630] Fix bug in invite audit events

- bower.json
Implements: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/142
--
Ensure list entries keep their 'name' attribute
Any changes made to features and/or benefits are not being persisted on a save.
Replication:
- Navigate to the edit features and benefits page of a service.
- Edit features and/or benefits and click "Save and return to service"
Actual:
- Changes made are not persisted
Expected:
- Changes to either features and/or benefits should be persisted.
Reason:
- `name` parameter of each feature is getting changed by the JS from
`serviceFeatures` to `input-serviceFeatures`
> Fix bug with features, benefits, client list

- app/templates/services/list_services.html
Previous feature flag check removed the "View service" link if the
service editing was turned off, but there's still a service name link
to the "edit" page.
Instead, we keep the "View service" links and remove the service name
link if the editing is disabled.
> Remove service name links to edit page if editing services flag is False

- bower.json
Brings in content changes from the following pull requests on the SSP repository:
1. https://github.com/alphagov/digitalmarketplace-ssp-content/pull/61 (number fixes & CCS changes)
2. https://github.com/alphagov/digitalmarketplace-ssp-content/pull/62 (change lead-in paragraphs on multi-option questions to confirmation ones)
> Content changes for the supplier declaration form

- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/frameworks/services.html
- app/templates/macros/submission.html
- app/templates/services/service_submission.html
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Adds optional questions to the progress counters.
Possible progress messages:
* Services with missing answers for required questions show
total unanswered questions count: `x questions unanswered`
* Services with all required questions answered show:
Service  can be moved to complete  
x optional questions unanswered
* Services with all questions answered show
`Service can be moved to complete`
* Complete services show either `x optional questions unanswered`
or an empty field if all optional questions are answered.
> Optional questions count on service submission

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/login.py
- app/main/views/suppliers.py
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_login.py
They were pointing at create-user and were not giving any data so the failure was actually coming from the form validation. I couldn't find anything useful to test in the response to distinguish them so I've added an assertion on get_user being called which will at least confirm that the right view is being requested.
See: https://www.pivotaltracker.com/story/show/101415342
See: https://www.pivotaltracker.com/story/show/101414610
> [#101414610] Add more audit logging

- scripts/run_tests.sh
- scripts/test_env.sh
This makes it easier to set the environment into your current shell for running specific tests.
> Extract script to set test environment

- app/main/helpers/services.py
- tests/app/main/test_services.py
I only noticed this because I was trying to manually test the supplier app when not connected to the internet. Instantiating `S3` talks to S3, this isn't necessary if we're not uploading files.
> Do not connect S3 if no files are being uploaded

- app/templates/auth/update-user.html
- tests/app/main/test_login.py
Fixes this bug: https://www.pivotaltracker.com/story/show/101511456
"Create your account" shouldn't send an email if an account already exists for the email address supplied.  This adds a check that a user account with the supplied email doesn't already exist.
I also learned a lot about how mocks need to be ordered to make the tests pass OK... ouch.
> [#101511456] Should not send a "create account" email if an account already exists

- app/templates/macros/toolkit_forms.html
The list macro had two 'hint' variables declared
so was using the second, which wasn't being
filtered for markdown.
> Remove extra template variable

- app/assets/scss/_updates.scss
- app/main/errors.py
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/updates.html
- requirements.txt
- tests/app/main/test_frameworks.py
***
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/100214054)
This update displays (on the framework updates page) a listing of files in an s3 bucket based on an assumed directory structure.  Links for each file are signed URLs which are valid for 30 seconds -- exactly like the ITT .zip file.
Taking [Ralph's prototype](http://dm-prototype.herokuapp.com/updates) as a basis, I created a root-level directory with two subdirectories: one for communications (emails) and one for clarification questions.
```
g-cloud-7-updates/communications/Title of Email.odt
g-cloud-7-updates/communications/Clarification questions and answers.odt
```
If the directory structure doesn't exist, then both tables display their empty messages.
- Listing the …
> [#100214054] Add Communications and Clarifications files to updates page.

- bower.json
Also includes the addition of a link and some changes to the service submission questions.
Includes these pull requests:
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/67
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/66
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/68
https://github.com/alphagov/digitalmarketplace-ssp-content/pull/69
...which is all of these changes:
https://github.com/alphagov/digitalmarketplace-ssp-content/compare/367594a11c8c1364dd09086c6b265c35dcf8f658...cf7bb6f370560fa5a69f81d3a5d06e45b4922c02
> Add links to declaration questions

- app/main/views/services.py
- app/templates/frameworks/services.html
- app/templates/services/service_submission.html
After discussing this a bit, we've decided to change the way "Make
a copy" works. It still creates a new draft as before, but instead
of returning to the services dashboard it will redirect to the
editing of service name section of the newly created draft.
The assumption is that this will encourage suppliers to give
unique and meaningful names to the copied drafts so that we
don't end up with multiple copies of the same service with the
same name.
[#101571000](https://www.pivotaltracker.com/story/show/101571000)
"Return to summary" was hidden for services without a service name
in 09acc4f. The page rendered after validation only uses the update
data, not the full draft service data, so serviceName should be
explicitly added to the context. This was achieved by adding
serviceName to the …
> Edit copy service name

- .ebextensions/apache_log.config
- .ebextensions/cwl-logs-apache-access.config
Configure Apache to output JSON formatted logs and CloudWatch logs to read them. With the JSON formatted logs more sophistocated filter patterns can be used. This change also introduces the more focused 4xx filter and alarms currently used in the data API (400 - 403).
> Configure JSON apache logs

- .ebextensions/cwl-logs-apache-access.config
CloudWatch logs configuration needs to have the JSONLogFile variable set
as it's being used later in the file.
> BUGFIX: Need to have the JSONLogFile set for logs

- app/__init__.py
- app/main/helpers/services.py
- app/main/views/services.py
- app/templates/macros/toolkit_forms.html
- requirements.txt
https://www.pivotaltracker.com/story/show/101692502
Change how the previously uploaded file is displayed on the upload form so that rather than showing a long URL we show a message saying when the file was uploaded.
This is implemented in the Jinja2 macro to avoid changing the draft data in place (and thus lying about the value is) and to avoid doing the formatting in the frontend toolkit (which doesn't have access to the
required template filters).
Move `unformat_section_data` to `dmutils.content_loader`:
This continues the work of moving content section related functions into `dmutils`. This removes the need for any question type checking functions in the frontend app any more.
Pass `service_content` into `get_section_error_messages`:
Along with the previous change this removes the …
> Change upload document display

- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
- tests/app/test_application.py
Importing the `data_api_client` and patching an individual method (in `test_application.py`) wasn't a great idea, so I've removed that.
I've also removed `Mock`s in a few places so as to be more consistent across the tests.
The supplier app has changed since [story on Pivotal](https://www.pivotaltracker.com/story/show/97111136) related to this was written.  The tests weren't failing when I started this, but the solution wasn't a very sustainable one.
> Patch data_api_client more better

- config.py
See: https://www.pivotaltracker.com/story/show/101903480
The Frameworks table is already updated to have G7 `open`, so this should be all that's required to turn on G7 features in staging.
> [#101903480] Enable G7 on Staging

- app/assets/scss/_framework-application.scss
- app/assets/scss/_service_submission.scss
- app/assets/scss/application.scss
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/edit_declaration_section.html
- app/templates/frameworks/services.html
- app/templates/frameworks/updates.html
- app/templates/macros/submission.html
- app/templates/partials/complete_service.html
- app/templates/partials/service_warning.html
- app/templates/services/_base_service_page.html
- app/templates/services/service_submission.html
- app/templates/suppliers/dashboard.html
- app/templates/users/list_users.html
- bower.json
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
This pull request encompases a bunch of changes:
- from @superroz and @cathrooney's Google Doc
- from when @ralph-hawkins, @katieminatie and I took some creative license yesterday and researched the dashboard page
- from when @ralph-hawkins and I did some guerilla research at the DS£MED
It mostly involves:
- wording of how things are labelled
- more, contextual warning messages if your application to G-Cloud 7 wont  succeed
- ~~the renaming of 'copy' to 'clone'~~
- duplicating the 'mark complete' button at the bottom of the page (because you'll probably click it after reviewing the whole service)
Stepping through a submission:
--
> Change messages, add warnings

- app/templates/auth/update-user.html
Lots of people complaining that their link is "invalid" when probably it's expired.
Updates to the wording to help users understand what is going on.
> Error page content updated as per Roz suggestions.

- app/main/views/frameworks.py
- app/templates/emails/clarification_question_submitted.html
- config.py
- tests/app/main/test_frameworks.py
See: https://www.pivotaltracker.com/story/show/101512016
This sends an email to the user who submitted a clarification question, to confirm that we have received it.  The email looks like this:
I also tested the do-not-reply email address, which seems to do the job:
> [#101512016] Clarification question response emails

- app/assets/scss/_forms.scss
- app/assets/scss/_return-link.scss
- app/main/views/services.py
- app/templates/services/edit_section.html
- app/templates/services/edit_submission_section.html
- bower.json
- tests/app/main/test_services.py
--
This PR give users the explicit choice of whether to:
- save and continue to the next page of questions
- or save and return to the 'service overview' page
It does this by naming each button, and redirecting based on which button is clicked. To do this required bringing in https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/146, which is why some of the tests/CSS have needed to change.
> Add a second submit button when editing drafts

- app/templates/auth/login.html
Unnecessary, so shouldn't be there.
Removing highlighted:
> Remove ‘Account’ from above page title

- scripts/generate_questions_csv.py
* The generated CSV files were missing answers for `boolean` type questions - now they are included.
* Lines with fewer options than the maximum are now right-padded with commas so that each line has the same number of columns.  This makes it look pretty in Github, and may help with importing into spreadsheets.
> Add trailing commas and Yes-No answers

- app/main/helpers/frameworks.py
- bower.json
- tests/app/main/helpers/test_frameworks.py
See: https://www.pivotaltracker.com/story/show/102066014
Following discussions with CCS these fields are now required in the declaration: SQ1-1b, SQ1-1d-i, SQ1-1d-ii, SQ1-1e
SQ1-1b wasn't optional before anyway, but the other three were and this makes them required.
Also fixes a small validation bug - previously using `if not ...` on the `SQ5-2a` field returned true for either `None` or `False`, but the required fields should only be added to the errors for the `False` case, and not for the `None` case.  So using `is False` is the right test.
> [#102066014] More required declaration answers

- app/main/helpers/services.py
- app/main/views/services.py
- app/templates/services/service_submission.html
- requirements.txt
- tests/app/main/test_services.py
[#102058034](https://www.pivotaltracker.com/story/show/102058034)
We're keeping "Save and return to summary" only for service name edits
after "Make a copy".
There's an expectation that some suppliers will use the section
editing flows to check filled in questions. When every update
sends a request to the API there's a risk that this would lead
to lost writes if other users are editing the same service at
the same time.
To avoid this we check if any of the submitted fields are different
from existing service data and only send the API update request if
fields were changed.
This works for input fields, but not for empty checkboxes, radios and
file uploads. Since they are not part of the posted data when no value
is selected, they don't trigger the "field change" event, which means
that the …
> Save if changed

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
This pull request adds a bit of contextual information to the G-Cloud 7 dashboard about when the supplier pack and the files on the updates page were last modified.
Spent a long time talking about date formats, but ultimately Cath said we wanted the year to be included, so I've gone with the [`DISPLAY_DATE_FORMAT`](https://github.com/alphagov/digitalmarketplace-utils/blob/master/dmutils/formats.py#L8) (ie, `Friday 28 August 2015`).
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/101483360)
***
> [#101483360] Display last modified dates on the G-Cloud 7 dashboard page

- .ebextensions/apache_log.config
Use the DM-Request-ID header from the response rather than the request.
As this app is what generates the request ID (Nginx strips any that may
have been nefariously set from outside) there will be no DM-Request-ID
request header here.
http://httpd.apache.org/docs/2.2/mod/mod_log_config.html#formats
> Use DM-Request-ID header from the response

- app/main/views/login.py
- app/templates/auth/create-user.html
- tests/app/main/test_login.py
When the validation fails I was passing None to the template instead of the values from the token we needed to render the page correctly
> Fix bug whereby token fields not passed to template

- requirements.txt
Brings in the fix for a unicode error from the
process that generates a fingerprint for the
static asset files:
https://github.com/alphagov/digitalmarketplace-utils/pull/155
> Bump utils to 6.7.1

- app/templates/auth/request-password-reset.html
Previous password reset message lied to users.
Emails have to be associated with supplier accounts -- validity is necessary but not sufficient.
> Change password reset message.

- README.md
Explains how to locally configure boto and links to official documentation.
I asked @allait about it, and both @tombye and @TheDoubleK asked me about it, so there's probably a reason to stick it in the README.
> Add boto configuration documentation to README file

- app/assets/javascripts/_analytics.js
- app/assets/javascripts/analytics/_init.js
- app/assets/javascripts/analytics/_pageviews.js
- spec/javascripts/manifest.js
- spec/javascripts/unit/AnalyticsSpec.js
This was missed out when the new functionality was added.
To run the tests, open `spec/javascripts/support/LocalTestRunner.html` in a browser.
> Add missing pageview tracking to analytics

- app/templates/_footer_categories.html
Since this ([soon won't be](https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/150)) behind a feature flag we can reliably assume, in this app, that it exists and therefore link to it.
> Add link to supplier A–Z

- .ebextensions/cwl-logs-application.config
Other alarms use 'supplier frontend' rather than 'supplier app'. This change makes it easier to determining the application that has raised the alarm.
This alarm is firing continuously on preview and regularly on staging and production. The intention of the alarm is to warn us of a possible attack, 10 requests in a minute is not indicative of that.
> Monitoring fixes

- app/main/views/suppliers.py
Nicole has been receiving reports of users creating their supplier account but not receiving the invite email. It's currently difficult to monitor this because we can't see whether the users ever visited the create-your-account page.
> Add more supplier create logging

- app/assets/scss/_assurance-question.scss
- app/main/helpers/services.py
- app/templates/services/_base_edit_section_page.html
See: https://www.pivotaltracker.com/story/show/101379472
Previously the main question was highlighted rather than the assurance part of the question.
This will make it clearer which part of the question is missing an answer.
> [#101379472] Highlight assurance questions for missing assurance answers

- bower.json
- requirements.txt
See https://www.pivotaltracker.com/story/show/102562916
This brings in the changes necessary to repopulate assertion answers with their values - both on validation error and when editing previously completed pages.
Depends on:
> [#102562916] Assertions repopulated on edit pages

- .ebextensions/apache_log.config
Add `requestTimeMicro` (the time a request took in microseconds) and `requestPath` (the request path without the query string) to the apache access logs.
`requestPath` is useful for metric filters against a specific page.
`requestTimeMicro` is justified here https://github.com/alphagov/digitalmarketplace-api/commit/9ec62be7f51997e7876e056bbb0236fc6fee5f7e
I have only added these to the JSON logs as they are the format we are moving towards and making changes to the plain text logs requires a bit more thought.
https://httpd.apache.org/docs/2.2/mod/mod_log_config.html#formats
> Add fields to apache access log

- .ebextensions/cwl-logs-application.config
- app/main/views/login.py
See: https://github.com/alphagov/digitalmarketplace-utils/pull/151
This allows us to calculate a rate metric for login failures as apposed to the absolute number we currently have.
> Add JSON application logs and `login.success`

- app/main/helpers/frameworks.py
- tests/app/main/helpers/test_frameworks.py
See: https://www.pivotaltracker.com/story/show/102983572
Our rules were too strict for non-UK companies, so we're not going to validate this field any more.
> [#102983572] Remove validation of VAT number

- README.md
- gulpfile.js
- package.json
- scripts/run_tests.sh
- spec/javascripts/manifest.js
You can currently only run the JavaScript tests by loading the test runner in a browser.
This adds a Gulp task which uses PhantomJS to run the tests so it can be done from a command as well.
Travis apparently has PhantomJS as part of its environment: http://docs.travis-ci.com/user/ci-environment/#Headless-Browser-Testing-Tools
There were a few problems getting the plugin to work with Travis, the details of which (and the reason we're pointing to a Github repo in the `package.json`) is explained here:
http://stackoverflow.com/questions/32461456/travis-ci-can-the-version-of-node-installed-on-all-vm-images-match-the-latest
and here:
https://github.com/alphagov/gulp-jasmine-phantom/pull/1
> Allow the JavaScript tests to run in CI

- app/main/views/suppliers.py
- app/templates/suppliers/companies_house_number.html
- app/templates/suppliers/company_contact_details.html
- app/templates/suppliers/company_name.html
- app/templates/suppliers/company_summary.html
- app/templates/suppliers/create_new_supplier.html
- app/templates/suppliers/create_your_account.html
- app/templates/suppliers/create_your_account_complete.html
- app/templates/suppliers/dashboard.html
- app/templates/suppliers/duns_number.html
- tests/app/main/test_suppliers.py
_These changes are based on:_
- _feedback that has come into enquiries@digitalmarketplace.service.gov.uk_
- _looking at the funnels in analytics_
- _some guerilla research that @ralph-hawkins and I did yesterday_
This just changes the order in the code, so that the functional changes in subsequent commits will be easier to review. This pull request will be easier to review on a commit-by-commit basis.
We have had some users dropping out of the supplier creation process after they have clicked the green button on the summary page.
We posit that this is because:
- they think they're done at this point
- we don't do a good job of explaining why you need to enter an email address for the second time
This commit changes the order of the pages to put the summary last, and not create the …
> Change signup order

- app/main/helpers/frameworks.py
- bower.json
- tests/app/main/helpers/test_frameworks.py
Adding 'none of the above' option means that the rules for the dependent question on that page need to be a bit smarter.
Also pulls in latest content with the 'none of the above' option.
> Validation tweaks for none of the above

- app/main/views/login.py
- app/templates/auth/login.html
- app/templates/auth/update-user.html
- tests/app/helpers.py
- tests/app/main/test_login.py
This pull request addresses incorrect messaging we were potentially sending to invite-link-clicking enthusiasts.
For example, if a new user
1. clicked an invite link
2. created an account
3. clicked the invite link again
they would end up on an error page telling them their account was locked or inactive, which it clearly wasn't. 
The following table should help: first column outlines a scenario, second column describes the result.  (Screenshots below.)
State of the user when they click a valid invite link | Result
------------ | -------------
Totally new user | sees the Create User Form
User with a Buyer account | sees the Update User Form (which converts a `buyer` account to a `supplier` account).
Locked user | sees an error message telling them they're locked
Deactivated user | sees an …
> [#102167826] Fix invitation link behaviour

- gulpfile.js
- package.json
Replaced the deprecated gulp-uglifyJS with gulp-uglify, as per the following warning message it was giving out:
`npm WARN deprecated gulp-uglifyjs@0.6.0: Since gulp-sourcemaps now works, use gulp-uglify instead`
While I was there I also updated Bower as it was also complaining of being a few releases behind and added sourcemaps to the JavaScript compression process.
If this is accepted I'll push it out to the other apps.
> Update Node modules

- scripts/run_tests.sh
It's useful to have something that points to the
testsuite that's being run, as mentioned in:
https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/159#discussion_r39135917
This is now in the buyers app so we should also have it here.
> Give the JS tests their own exit status

- app/templates/auth/request-password-reset.html
- app/templates/emails/reset_password_email.html
"[Some of the wording we're using in our user-facing messaged is not ideal](https://www.pivotaltracker.com/story/show/97612300)", and though some of it had been looked at, there were a few places left over that weren't.
We're not referring explicitly to forms any longer, but rather asking users to do something with the form.
Also, removed the bit about getting in touch from the password reset email unless getting in contact would be necessary.
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/97612300)
> Update password-reset error messages.

- app/assets/scss/_supplier-declaration.scss
See this bug: https://www.pivotaltracker.com/story/show/101673638
Previously the validation error red bars overlapped the outdented bullet points on list items.
Now bullets are indented if there is a validation error for the question.
Before: 
After:
> [#101673638] Indent list items with validation errors

- app/assets/scss/_assurance-question.scss
Fixes this bug: https://www.pivotaltracker.com/story/show/103193094
Before (Firefox):
After (Firefox):
> [#103193094] Prevent text being obscured on assurance validation error

- app/__init__.py
- app/main/helpers/__init__.py
- app/main/views/frameworks.py
- app/main/views/login.py
- app/main/views/suppliers.py
- app/main/views/users.py
- requirements.txt
This is a broad commit that does a few things.
Only put hashes of email addresses in logs. This means that we are not storing personal information in logs but we can search for log messages by email address if we hash the address locally first.
Extract variables out into extra parameters. The logging in dmutils has been changed to attempt to format log messages with the log record (containing all log variables). This means that if a log message is provided as a template and the variables provided in the extra dict then the message will be rendered correctly and the variables will be pulled out in the JSON logs.
> Improve and standardise logs

- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/auth/submit-email-address.html
- app/templates/auth/update-user.html
- app/templates/services/service_submission.html
- app/templates/suppliers/edit_supplier.html
- tests/app/main/test_login.py
IE7 needs submit buttons to have an attribute of `type="submit"` for them to work and a lot of ours don't.
This fixes that by adding the necessary attribute where needed.
> Give all submit buttons a submit attribute

- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
We have been seeing exceptions in production for the supplier account creation complete view. It seems this is caused by a refresh because the entire session is cleared. Ensuring the `email_sent_to` field is re-added to the session means that at least this page can be refreshed.
> Allow refresh on supplier account create completion

- app/main/views/suppliers.py
- app/main/views/users.py
- app/templates/suppliers/dashboard.html
- config.py
This commit removes feature flags which are now enabled on all environments, which are:
- `USER_DASHBOARD`
- `SUPPLIER_DASHBOARD`
- `EDIT_SUPPLIER_PAGE`
None of the other apps have feature flags which can be removed, therefore this completes [story 102080450](https://www.pivotaltracker.com/story/show/102080450).
> Remove remaining feature flags

- app/assets/javascripts/analytics/_events.js
- spec/javascripts/unit/AnalyticsSpec.js
It would be very useful to know, for example, the split between how many users are clicking the 'save and continue' button and how many are clicking the 'save and return to service overview'.
This commit adds code similar to the link tracking code to fire an event when any button is clicked.
By recording the text of the button and the URL of the page that the user is on we can filter the data to work out what's going on.
> Track when users click buttons

- app/templates/frameworks/updates.html
This is what happens when the story description gets updated after you've already copy-and-pasted the required content out of the story.
> Tweak copy to match updated version in story

- app/assets/javascripts/application.js
- app/assets/scss/_supplier-declaration.scss
- app/assets/scss/application.scss
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/auth/submit-email-address.html
- app/templates/frameworks/edit_declaration_section.html
- app/templates/frameworks/updates.html
- app/templates/services/_base_edit_section_page.html
- app/templates/suppliers/create_new_supplier.html
- app/templates/suppliers/create_your_account.html
- app/templates/suppliers/edit_supplier.html
- bower.json
Wraps all form content in a two-thirds grid so their width is dictated by the grid instead of part of their styling.
Part of https://www.pivotaltracker.com/story/show/103093496
Brings in this work from the DM Toolkit: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/158
This pull request also includes a shim for the `console` object so browsers that don't support it won't throw an error when it is used.
> Add grids to forms content

- config.py
This needs to be deployed at 5pm today.
> Switch on PROD feature flag to turn off clarification questions

- app/main/views/login.py
- app/main/views/services.py
- app/main/views/users.py
- app/templates/users/list_users.html
- requirements.txt
- tests/app/main/test_login.py
- tests/app/main/test_services.py
Part of this bug fix: https://www.pivotaltracker.com/story/show/103779820
When a supplier removed a user from their supplier account the message said that they could re-invite the user at any time.  This isn't entirely true, as Nicole will have to re-activate the user first.
Rather than spell this out in a lengthy flash message (as re-adding a removed user is an unlikely edge case), it's better to just confirm that the user has been removed.
Depends on:
> [#103779820] Improve messaging for removed users.

- app/main/views/login.py
- requirements.txt
Brings in:
Discussion point: is it right to say it's the user who is updating their password here—they're not logged in—is it something we can really know?
> Fix updating of password

- app/main/views/login.py
- tests/app/main/test_login.py
This method was assuming that `current_user` exists, but this method doesn't require login and breaks if called without a `current_user`.
500s in the logs caused by:
```
'AnonymousUserMixin' object has no attribute 'email_address'
```
> [#104451064] BUGFIX (urgent): There may not be a logged-in user for user updates

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- app/templates/macros/submission.html
- app/templates/services/_base_service_page.html
- app/templates/services/service_submission.html
- app/templates/suppliers/dashboard.html
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
See: https://www.pivotaltracker.com/story/show/103088520
There is a further story for @ralph-hawkins and/or @superroz to review the copy for G7-switchoff here: https://www.pivotaltracker.com/story/show/103088582
The copy changes in this pull-request are **TheDoubleK** specials.
The actual switch-off will be done by changing the `status` of the `g-cloud-7` framework from `open` to `pending`.  We should be able to merge and test this code on preview/staging by manually changing the database.  Once tested we should change the framework status back again, as the functional tests will fail once G7 submissions are closed.
With no change to the database then everything should be the same as it is now.
Once the framework is pending the following changes should be seen:
On `/suppliers`:
* The link …
> [#103088520] Close G7 submissions

- app/assets/scss/_framework-application.scss
- app/assets/scss/application.scss
- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- app/templates/services/service_submission.html
- app/templates/suppliers/dashboard.html
- bower.json
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Changes for when G7 is switched off.
https://www.pivotaltracker.com/story/show/103088582
> G7 closed content updates

- app/templates/frameworks/dashboard.html
There is no Tuesday, November 9th 2015.  Not anymore.
> Change the nature of time.

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- requirements.txt
- tests/app/main/test_frameworks.py
This brings in alphagov/digitalmarketplace-utils#178 which changes the `DataAPIClient` to match the language we use around the supplier declaration.
Using the SSP tests with the framework set to 'open'.
> Upgrade to dmutils 9.0.0

- README.md
The section on updating Python dependencies did not have the correct file reference to 'requirements_for_test.txt'
This change updates README.md
> update README.md to use the 'requirements_for_test.txt'

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
When the signature of `get_draft_document_url` was changed the download supplier file route was not updated.
> Fix bug #105988832: Communications files erroring

- app/main/__init__.py
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/edit_declaration_section.html
- app/templates/frameworks/services.html
- app/templates/frameworks/updates.html
- app/templates/services/edit_submission_section.html
- app/templates/services/service_submission.html
- app/templates/suppliers/dashboard.html
- bower.json
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
This change makes the routes that were hard coded to G-Cloud 7 support multiple frameworks. This change does not include moving any of the routes. This has been left for a later change as it will break far more tests.
This change has been tested with the functional test suite using both the @functional-test tag and the @ssp tag.
The list of routes is:
- /frameworks/<framework_slug>
- /frameworks/<framework_slug>/services
- /frameworks/<framework_slug>/declaration
- /frameworks/<framework_slug>/<path:filepath>
- /submission/<framework_slug>/create
The change consisted of a few steps:
- Replace `g-cloud-7` with `<framework_slug>` in the route
- Get the framework details from the data API - this 404s if it doesn't
exist.
- Pass framework slug to `url_for` calls - some of them have just been …
> Make G7 routes support multi-framework

- app/main/views/frameworks.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- app/templates/frameworks/updates.html
- app/templates/partials/complete_service.html
- app/templates/services/_base_service_page.html
- app/templates/services/edit_submission_section.html
- app/templates/services/service_submission.html
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Move the routes around to follow the agreed new layout which includes framework slug in all framework specific routes.
The main goal of this change is to allow DOS to be supported by the route on the supplier frontend. A secondary goal has been to rationalise the routes to make grouping for analysis easier.
Old route | New route
------- | --------
`/frameworks/<framework_slug>/<filepath>` | `/frameworks/<framework_slug>/files/<filepath>`
`/frameworks/g-cloud-7/updates` | `/frameworks/<framework_slug>/updates`
`/submission/<framework_slug>/create` | `/frameworks/<framework_slug>/submissions/create`
`/submission/services/<service_id>/copy` | `/frameworks/<framework_slug>/submissions/<service_id>/copy`
`/submission/services/<service_id>/complete` | …
> Move routes around to include framework slug

- app/assets/scss/_framework-application.scss
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/suppliers/_dos_messaging.html
- app/templates/suppliers/_g7_messaging.html
- app/templates/suppliers/dashboard.html
- config.py
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
Completes this story: https://www.pivotaltracker.com/story/show/105005134
Further design for displaying both DOS and G-Cloud messages on the same page is forthcoming.  For now I have simply put the DOS messages above the existing G-Cloud 7 messages.
I have also changed registering interest to only happen on a POST request from the button in the "register interest" message - for G7 interest was registered with all GET requests to the framework dashboard. 
Also removes the dependency on `'GCLOUD7_OPEN' is active_feature` from the dashboard template - all messaging is now conditional on the status of the frameworks in the databse, not on a feature flag.
Prototype design for before registering:
http://dm-prototype.herokuapp.com/states/account?dos.framework=open&dos.application=null
Screenshot …
> [#105005134] Register for DOS

- README.md
Similar to [this](https://github.com/alphagov/digitalmarketplace-admin-frontend/pull/138) pull request for admin-frontend, and as per @allait's comment, it is a good idea to point new developers to a page that actually exists rather than 404s.
> README fix: point to a page that exists

- app/__init__.py
- requirements.txt
As part of [an earlier pull request](https://github.com/alphagov/digitalmarketplace-utils/pull/192), a markdown filter was added to flask apps that import dmutils.
Means we can still use the `markdown` filter in our jinja2 templates, but we shouldn't be duplicating it in the `create_app` function.
*Might* have forgotten to do this earlier.
> Remove markdown package and filter definition.

- app/assets/scss/_framework-application.scss
- app/main/helpers/frameworks.py
- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/templates/emails/framework_agreement_uploaded.html
- app/templates/frameworks/agreement.html
- app/templates/frameworks/dashboard.html
- config.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- Add an environment variable for the base assets URL since the assets domain is not just for documents.
- Build a path for an agreements document based on the framework slug and the supplier ID of the current user. The agreement documents contain the supplier ID (for easy referencing later) and also live in a directory named the supplier ID (for easy browsing of the bucket).
- Add a function to get a document URL that works in a similar way to the draft document URL function but only replaces the host and scheme with the asset URL if the environment variable is set. This allows the URLs to work in development even if a reverse proxy is not being used.
- Add link to framework agreement page. This replaces the declaration status API call on the framework dashboard with a call to the …
> G7 display agreements

- app/main/helpers/frameworks.py
- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- app/templates/partials/complete_service.html
- app/templates/services/_base_service_page.html
- app/templates/services/edit_submission_section.html
- app/templates/services/service_submission.html
- bower.json
- config.py
- requirements.txt
- requirements_for_test.txt
- scripts/run_tests.sh
- setup.cfg
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Requires:
Splits framework services into two pages: list of lots and individual
lot pages with lot services.
Both pages are only displayed if framework status is either open or
pending. For pending frameworks page is only displayed to suppliers
who have submitted an application. Feature flag check is removed.
Lot pages check the 'one service limit' flag and:
* Display the list of lot services for lots with multiple services.
This is similar to the previous submission services page, except
the services are filtered by lot.
* For one service lots: creates the service for given lot and supplier
if it doesn't exist and redirects to the service page right away.
Note: creating an empty draft for one-service lots is an action taken
as a result of a GET request (which are not covered by the CSRF …
> Basic DOS service flow

- app/main/helpers/frameworks.py
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
When a supplier first registers interest in a framework the declaration
is null. This was causing the framework dashboard to blow up because we
were expecting the declaration to be a dictionary. This handles the case
when it is null.
> BUGFIX: Supplier framework with null declaration

- app/main/views/frameworks.py
- requirements.txt
- tests/app/main/test_frameworks.py
This brings in changes to how the agreement document path is generated. The function now expects the supplier name as well.
> Upgrade dmutils to 13.0.0

- app/assets/scss/_framework-application.scss
- app/main/views/frameworks.py
- app/templates/emails/framework_agreement_uploaded.html
- app/templates/frameworks/agreement.html
- app/templates/frameworks/dashboard.html
- config.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
Allow G-Cloud 7 signed framework agreements to be uploaded by suppliers.
> G7 upload signed agreements

- app/templates/frameworks/agreement.html
- app/templates/frameworks/services.html
…because it wasn’t considering the 'standstill' state.
This commit:
- fixes that
- changes the 'empty' message to be in the correct tense for each state
> Tidy up various things

- app/templates/emails/framework_agreement_uploaded.html
The format needs to be exactly as in the story so that Zendesk filters will work properly.
> Make `framework uploaded` email text match the story

- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
The template was previously getting a framework rather than the framework name.
This also removes confusing messaging  "0 draft services were not submitted" for suppliers who did not leave any services in draft.
> Pass framework name to email template

- app/main/views/frameworks.py
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
The files for the framework agreements need to use the registered
company name from the declaration.
> Use the declaration supplier name for agreements

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- bower.json
- tests/app/main/test_frameworks.py
This implements: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/178
For each lot, it tells the user how many draft and complete services they have submitted.
Right now it’s fairly specific to the G-Cloud 7 sitation (without actually having `g-cloud-7` anywhere). We’ll need to handle some different states when DOS comes along.
--
> Add lot counts to submitted lots page

- app/main/__init__.py
- app/main/helpers/frameworks.py
- app/main/helpers/validation.py
- app/main/views/frameworks.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
Previously framework validation rules were specifically for G-Cloud 7. To support DOS, we need to have the ability to have multiple validators. This lays the groundwork for this by separating out G7 framework rules into one class.
> Refactored framework validation to make it modular

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/frameworks/dashboard.html
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
See: https://www.pivotaltracker.com/story/show/107569658
For the supplier dashboard when the framework goes live:
- Framework dashboard is still visible, and does not have a "View services" link or a "You made your declaration..." summary sentence.
- The title is "Your <framework> documents".
- The updates and framework agreement pages both still work the same as when framework is in 'standstill'
Framework dashboard for successful G-Cloud 7 supplier after the framework is live:
This PR also fixes this bug with the services ordering: https://www.pivotaltracker.com/story/show/107912404
Before
======
After
=====
> [#107569658] Framework dashboard for 'live' framework

- app/main/views/frameworks.py
- bower.json
Depends on:
This commit accommodates the breaking change made in version 12.0.0 of the toolkit. It does not make any functional changes.
> Bump toolkit to 12.0.0

- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
There is an edge case where:
- a supplier has services
- a supplier is not 'on' a framework
In this case the link to view services should not be shown.
In actuality, the link was being shown.
This is because the logic was checking for different things when deciding to
- show the list of current frameworks and service counts
- showing the view link
This commit changes the code to check for the same thing (`frameworks.live`) for both purposes.
> Fix bug with display of current services

- app/templates/services/_base_edit_section_page.html
- app/templates/services/edit_section.html
- tests/app/main/test_services.py
At some point, our `return to service summary` links stopped displaying
properly.  Got them back and added a test.
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/107279234)
***
> Fix `return to summary` link while editing services

- app/main/views/frameworks.py
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Set the file extension correctly when uploading signed framework agreements.
We have been getting some zero byte files uploaded as signed agreement documents.
> Fixing agreement uploads

- app/main/views/services.py
- app/templates/services/service_submission.html
- tests/app/main/test_services.py
After https://github.com/alphagov/digitalmarketplace-api/pull/297 validation errors will come back in API responses when getting a single draft service. This change makes use of them to decide whether or not to show the 'mark as complete' button. This is required because not all of the validation rules can be determined just by whether any required fields are unfilled.
> Make use of draft service validation errors

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
When the declaration validation fails the submitted data should be remembered and presented back into the form.
> Remember submitted data on declaration failure

- app/main/errors.py
- requirements.txt
These exception can be raised if the errors map returned by the API contains keys that are not recognised by the content loader.
> Handle QuestionNotFoundError

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/submission_lots.html
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
Shows the status of a suppliers application to a framework on the page which lists the lots.
--
--
_Notes for reviewing:_
- _You won’t be able to follow the logic in the code—I’d be more interested to know if you think there are any obvious test cases I’ve missed_
--
This should work for existing G7 applications, future DOS applications and any other framework that fits our current model.
The exact messaging depends on:
- whether the lot has a limit of one service
- status of framework
- number of draft and complete services
- status of supplier declaration
- name of the lot
…which makes it quite complicated.
This commit adds a couple of tests to the existing tests for this endpoint. It then adds a _lot_ of explicit tests for the helper functions that generate the status messages. This is …
> Show status of application by lot

- bower.json
Various minor updates to the DOS questions.
> Bump frameworks version to 0.9.0

- bower.json
This is the version of frameworks that the API is using, so it fixes some broken behaviour.
Relies on:
> Bump frameworks version to 0.9.4

- app/assets/scss/_framework-application.scss
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- bower.json
- tests/app/main/test_frameworks.py
Based on talking this through with @ralph-hawkins.
- cuts down the number of status we show you by not talking about drafts on this page
- makes the statuses work for lots which have a limit of one service, as well as lots that have a limit of more than one service
- tells you which lots you are submitting to
- Tidy and simplify the dashboard template (to pave the way for the meat of this PR)
- Use new browse list status
- Move declaration above services
> Add new statuses for services on framework dashboard

- bower.json
[☞  v13.0.2](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/releases/tag/v13.0.2)
Includes:
- https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/190
> Bump toolkit version to 13.0.2

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/emails/clarification_question_submitted.html
- app/templates/emails/follow_up_question.html
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/updates.html
- config.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
Removes the `G7_CLARIFICATIONS_CLOSED` feature flag in favour of the
framework data `clarificationQuestionsOpen` flag returned by the API.
This requires a switch in `if ... else ...` order to make conditions
more readable.
Changes to clarification emails sent to zendesk:
* Email subject changed from "Clarification question" to "<framework>
clarification question"
* Email from address changed from `suppliers@...` to
`suppliers+<framework-slug>@...`
Changes to application emails:
* Subject will use the current framework name in "<framework>
application question"
* Tags changed from "g7-application-question" to "application-question"
> Make clarification emails non-G7 specific

- app/assets/scss/_service_submission.scss
- app/assets/scss/application.scss
- app/main/views/services.py
- app/templates/services/service_submission.html
- bower.json
This makes the text of the delete button name the lot, if the lot has a limit of one service. This makes sense because deleting the services effectively deletes the whole lot, and talking about these things as services is weird.
> Better buttons

- app/templates/services/service_submission.html
If a lot has a limit of one service it doesn’t make sense to link to the lot from the service page—it just links to the current page, which we don’t do anywhere else.
This commit adds a condition to hide the link.
Fixes [109072944](https://www.pivotaltracker.com/story/show/109072944).
> Fix breadcrumbs on lots with a limit of one service

- app/main/views/services.py
- app/templates/services/_base_service_page.html
- bower.json
- tests/app/main/test_services.py
This worked in previous SSPs. It got lost somewhere along the way.
It is jarring to be taken back to the top of a long page after answering a question, and having to scroll all the way down to find where the answer is played back (and potentially where the next section of questions you want to answer are).
This commit adds an anchor to jump between these pages more seamlessly.
> Jump links

- app/main/views/services.py
- app/templates/partials/service_warning.html
- app/templates/services/service_submission.html
- config.py
This pull request makes a few small changes where I noticed problems while clicking through the app.
1. Services that were marked as complete before the framework declaration was finished would direct users to the G7 declaration.
2. Otherwise, once the (DOS) declaration was completed, the old G7 deadline would be displayed.
3. Added time of day into the `DOS_CLOSING_DATE`
Should we move the DOS closing date into `digitalmarketplace-frameworks`?
There's still [one reference to `g_cloud_7_essentials` still in `_event.js`](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/808f074085346aaf70baa74491cc7f3d1210f428/app/assets/javascripts/analytics/_events.js#L5)?  Do we change it or get rid of it?  I don't know what it is.
> Remove G-Cloud 7 deadline and declaration link

- app/templates/services/_base_edit_section_page.html
Sue found an excellent bug: https://www.pivotaltracker.com/story/show/109279212
1. Click answer required on a section with multiple questions
2. Answer less than all the questions on the page
3. Click on save and continue
**Expected**: you are back at the top of the page and see the validation masthead
**Actual**: you are jumped down the page to the question for which you clicked 'answer required'
This is because the form always posts to it’s own URL. And if this url has a `#fragment` at the end of it, then this is the URL that gets posted to. Since you stay on the same page if there are any errors then the page you stay on also has the fragment, which matches the ID of the question, which is where you get jumped to.
This commit changes the HTMl to always post to the page’s own URL …
> Don’t jump down page after incorrect submission

- app/templates/services/_base_edit_section_page.html
- app/templates/services/_base_service_page.html
- app/templates/services/service_submission.html
- requirements.txt
This is replaced by…
Brings in and depends on:
> Make contextual help make sense

- app/main/helpers/services.py
- app/main/views/services.py
- app/templates/services/edit_submission_section.html
- tests/app/main/test_services.py
Removes the secondary "Save and return to summary" button and makes
all service "Save and continue" buttons return to the summary page
with the current section slug anchor.
Removes `next_section` and `return_to_summary` mentions from service
pages.
> Make "Save and continue" button return to summary

- app/assets/scss/_supplier-declaration.scss
- bower.json
Fixes: https://www.pivotaltracker.com/story/show/106191644
Brings in: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/197
Has some custom CSS to deal with the question headings on the declaration being
smaller than standard.
> Fix overlapping text on supplier declaration

- app/assets/scss/_forms.scss
Added some spacing between linebreaks in our really long question headings.
Only targeting paragraph tags in headings (excluding the last one), so the rendering for the majority of question headings doesn't change.
I'm making the change here instead of the frontend toolkit because the markup in each is different.
The supplier app passes all question headings through a markdown filter so the `<p>` tags only exist in this app.
Markup in the supplier app:
```html
<span class="question-heading ">
<p>Where will your agile coach work?</p>
</span>
```
Markup in the frontend toolkit:
```html
<span class="question-heading ">
Where will your agile coach work?
</span>
```
Adding CSS in the frontend toolkit that would only be interpreted in the supplier app because of a different way of rendering …
> Add spacing for question heading linebreaks

- app/templates/auth/submit-email-address.html
This field was using the `single-question-page`
class. This class currently assumes the page
heading will be a duplicate of the field label so
hides it.
The field was also using a different markup
pattern to other pages with one question (for
example, those in the 'create a new supplier
flow'). The markup for this pattern was missing
some span tags, causing the label to be hidden
normally but shown if validation messages were
present.
This change removes the `single-question-page`
class to ensure the label is shown and swaps the
markup out to use the [toolkit textbox pattern](http://alphagov.github.io/digitalmarketplace-frontend-toolkit/forms/textbox.html)
(which has markup that works both for the field
in its base and invalid states).
The page now looks like this:
> Show label for contributor email field

- app/main/__init__.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/updates.html
- app/templates/services/service_submission.html
- app/templates/suppliers/_frameworks_open.html
- app/templates/suppliers/_frameworks_standstill.html
- bower.json
- config.py
- requirements.txt
- tests/app/main/test_frameworks.py
Dates consistently change between frameworks. This moves all dates into
the digitalmarketplace-frameworks repo as messages. Ultimately it would
be good if these were stored in the API against a framework. However,
until we have a clear understanding of what dates are required, what
they mean, and how we want to manage them consolidating them in one
place is a good first step.
> Consolidate framework dates in the content repo

- app/templates/suppliers/_information.html
- bower.json
Requires the merging of [PR 192](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/192) on frontend toolkit.
If there's a URL, people should be able to click on it.
> Linkifying URLs in summary tables

- requirements.txt
Brings in
- [#221](https://github.com/alphagov/digitalmarketplace-utils/pull/221)
which fixes rendering for questions with assurances
None are breaking changes, so there shouldn't be anything else to do.
> Bump utils to 15.6.1

- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_open.html
Marking a string as safe does not work when building a string with .format.
> Fix deadline markup escaping bug

- app/main/views/frameworks.py
This comes from the API.
Previously used lot label from the content, which has changed to start with
'Apply to provide…'
--
Fixes https://www.pivotaltracker.com/story/show/109529008
> Use lot name for summary of completed lots

- app/main/views/frameworks.py
- app/templates/emails/dos_application_started.html
- requirements.txt
- tests/app/main/test_frameworks.py
[#107188306](https://www.pivotaltracker.com/story/show/107188306)
Sends a welcome email to all supplier users. Email is sent using
the updated `dmutils.email.send_email`: each recipient will get
a separate message with only one 'to' address.
The request will proceed without returning an error if send_email call
raises an exception, since if framework interest is registered a page
refresh would show the dashboard anyway.
> Send application started welcome email to supplier users

- app/assets/scss/_supplier-declaration.scss
In both the declaration and the 'service essentials' sections. In other words, don’t have it scoped to the declaration.
Also sets the type size explicitly for safety.
> Make section descriptions look the same

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
See: https://www.pivotaltracker.com/story/show/109538382
Previously all clarification questions were being sent "from" `G-Cloud 7 Supplier`.
Instead the framework in the "from" should match the framework that the question is about.
> [#109538382] Clarifications "from" should be framework-specific

- app/main/helpers/validation.py
- tests/app/main/helpers/validation/test_dos_declaration.py
Two things fixed here:
* Validation was treating `None` values as though they were valid answers for required strings
* Conditional validation for Q72 (`licenceOrMemberRequiredDetails`) had the wrong condition on it
Fixes these three bugs:
https://www.pivotaltracker.com/story/show/109608322
https://www.pivotaltracker.com/story/show/109608580
https://www.pivotaltracker.com/story/show/109608626
> Fix declaration validation

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
Is a user was removed from the contributors list they should not
receive the application started email.
> Don't send welcome email to deactivated users

- app/main/helpers/frameworks.py
- app/templates/macros/toolkit_forms.html
This is so that, for conditional questions, we can say something like “you need
to answer this question because question 99”.
Depends on:
> Add question references to validation messages

- app/main/views/login.py
- app/templates/suppliers/dashboard.html
- tests/app/main/test_login.py
- tests/app/main/test_suppliers.py
If a logged in user navigates to the login page they should be
redirected to the supplier dashboard.
This commit changes the redirect flow for the `/suppliers/create-user` route. Before this change if a logged in user clicked the create user link for a different email address they would be redirected to the `/suppliers/login` route rather than the supplier dashboard. Since changing the `/suppliers/login` route to redirect logged in users to the supplier dashboard this different flow just adds in another redirect step.
With this change we redirect the user to the same place (the supplier dashboard) but show them an error message telling them what has gone wrong.
The tests associated with this flow have been updated to not follow redirects and we instead verify the location header and …
> Redirect when logged in

- app/main/views/frameworks.py
- requirements.txt
The communications that have been copied over from the G7 bucket have
had timestamps set in a custom metadata field. This change loads those
metadata fields if available.
> Load custom timestamps on communications

- app/main/views/services.py
- app/templates/services/edit_submission_section.html
See: https://www.pivotaltracker.com/story/show/108242580
And: https://www.pivotaltracker.com/story/show/109717458
(They are the same bug)
As well as fixing breadcrumbs after a validation failure - as described in the bugs - this also adds a breadcrumb that was missing for multi-lot services.
Before:
After:
> Breadcrumb bugfix

- bower.json
This change renames West England to South West England.
> Upgrade digitalmarketplace-frameworks

- app/templates/auth/request-password-reset.html
- tests/app/main/test_login.py
Used to say: 
> If the email address you've entered belongs to a supplier account, we'll send a link to reset the password.
Now, because Administrators might be using it as well, it says: 
> If the email address you've entered belongs to a Digital Marketplace account, we'll send a link to reset the password.
Also refactored the tests a bit.
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/110492418)
> Generalise notification message for password resets

- app/templates/services/list_services.html
Before | After
--- | ---
Having two links in the table was confusing.
This commit has one link, which goes to:
- the live service on the buyer app if the 'edit service' feature flag is off (
because otherwise we’d be sending you to a pointless page)
- the page where you can turn your service off if the 'edit service' feature
flag is on
It also removes the pretty colours from the statuses, and changes ‘private’ to
‘unavailable’ to match the admin app. We think there’s still value in
differentiating between services that have been removed by an admin and services
that a supplier has removed themselves.
***
https://www.pivotaltracker.com/story/show/110085882
> Remove status link from list of current services

- app/assets/scss/_lists.scss
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/updates.html
- tests/app/main/test_frameworks.py
See: https://www.pivotaltracker.com/story/show/107186966
The first batch of countersigned framework agreements from CCS have now been uploaded to S3.
This story allows suppliers to access their countersigned agreement from their framework dashboard page if it has been uploaded.  The page checks for the existence of a countersigned agreement for the supplier in S3, and displays a link to it if it finds one.
This is how the page will look once the countersigned agreement has been uploaded (OK'd by @ralph-hawkins ):
Once they have their countersigned agreement then suppliers should no longer be able to contact CCS from the question box:
> [#107186966] Return countersigned framework agreements to suppliers

- app/templates/services/_base_service_page.html
- app/templates/services/service_submission.html
Fixes this bug: https://www.pivotaltracker.com/story/show/111771084
Before:
After:
And now also fixes this bug: https://www.pivotaltracker.com/story/show/111770766
Before:
After:
> [#111771084] Only show edit links if framework is open & fix banner message

- tests/app/main/test_frameworks.py
Running our test suite without an internet connection would fail because our `send_email` method wasn't being mocked properly in one of the tests.  
Now it is. 👍
> Mock a mandrill call so that tests work offline

- scripts/run_app.sh
Running the app without `DM_AGREEMENTS_BUCKET` set causes the app to fail in various places (such as [the frameworks dashboard](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/app/main/views/frameworks.py#L91)).
Setting the variable resolves the issue.
> Add agreement bucket to `run_app.sh`

- gulpfile.js
When copying the digitalmarketplace-frameworks contents from bower
components to app/content the build process used to copy all repo
files. Since we've added more non-content related files to the
repo (tests, scripts, etc.) that aren't used by the apps there's
no reason to add them to the app release package and they could be
causing issues in the future (eg being picked up by pep8 and pytest).
> Only copy the frameworks folder to app/content

- config.py
@cathrooney asked for the feature (suppliers' ability to remove their own services) to go live, so here it goes.
> Enable suppliers removing their services

- app/assets/scss/_lists.scss
- app/templates/frameworks/dashboard.html
- app/templates/suppliers/create_new_supplier.html
https://www.pivotaltracker.com/story/show/111771966
When a framework is in the pending / standstill state the list of lots that have been submitted to should be displayed differently.
> [#111771966] Change layout of submitted services

- scripts/run_app.sh
The supplier app uses them but they were absent until now.
> Add environment variables for agreements and documents buckets

- app/main/helpers/frameworks.py
- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/main/views/suppliers.py
- requirements.txt
- tests/app/main/test_frameworks.py
Because including the supplier names in the filenames for
uploaded documents is quite finicky, we've opted to keep only the
`supplier_id` in the filename proper but suggest a different filename
(which includes the supplier_name) when the file is downloaded.
By setting a `Content-Disposition` header on the uploaded file, we:
- force the browser to download it
- suggest a different filename in the 'Save As' dialog
Note that since we use the same dmutils function for both viewing
and downloading files, and since all existing files are tied to the
old naming convention, we have to update the supplier uploading method
separately from the supplier downloading method.
Once existing files have been renamed, we can port the change over to
dmutils.
If the old filename was: …
> Change uploaded document filenames and set a Content-Disposition header

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/agreement.html
- app/templates/frameworks/dashboard.html
- requirements.txt
- tests/app/main/test_frameworks.py
This pull request: 
- changes the pathnames for getting uploaded documents to look for document names without the suppliers' names
- refactors  the `upload_framework_agreement` route to once again use the `.get_agreement_document_path()` function in dmutils
- swaps filenames hardcoded in templates for filename variables pulled in from dmutils
Once all agreement files have been renamed on our production AWS bucket, we can release this to production.
> [#112422463] Upload and retrieve framework (agreement) documents without supplier names in their filenames

- app/main/views/frameworks.py
- app/templates/frameworks/dashboard.html
- scripts/run_app.sh
Even after judiciously refactoring the /frameworks/dashboard page, it
turned out that there was a stray `if` condition checking for a
template variable that was no longer being passed in.
This meant that, after uploading a signed framework agreement and
receiving a countersigned one back, that it would still be possible
to upload a *new* signed framework agreement -- anarchy, basically.
This bugfix removes that possibility.
> Don't show the "Sign and return your framework agreement" link if countersigned framework agreement exists

- app/main/errors.py
Our 500-level errorhandler had a generic name instead of the standard 'Internal Server Error'.
Fixed it in the buyer app, so fixing it here as well.
> Reflect status code in errorhandler name

- app/assets/scss/_lists.scss
- app/templates/frameworks/agreement.html
- app/templates/suppliers/_frameworks_standstill.html
- tests/app/main/test_suppliers.py
This pull request makes several small changes requested by @cathrooney on [the DOS - update content for signing framework agreement story on Pivotal](https://www.pivotaltracker.com/story/show/112422239).
| Existing text                                                                                                         | New text                                        |
|-----------------------------------------------------------------------------------------------------------------------|-------------------------------------------------|
| Go to page 16 and click the signature box under the title ‘Signed duly authorised for and on behalf of the supplier’. | Go to page 5 and click the first signature box. |
| Print and sign page 16. …
> Update framework agreements page for standstill.

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
@kevkeenoy and I noticed these deprecated redirects, so we heroically deleted them and an associated test.
Seems fairly unlikely that anyone's still using them.
> Removed deprecated redirect for file download

- app/main/__init__.py
- app/main/helpers/briefs.py
- app/main/views/briefs.py
- app/templates/briefs/clarification_question.html
- app/templates/emails/brief_clarification_question.html
- app/templates/emails/brief_clarification_question_confirmation.html
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_briefs.py
- tests/app/main/test_frameworks.py
Adds a form to submit brief clarification questions.
* Page is only available if brief is currently live.
* The check for supplier eligibility is not connected to the API so
will always accept the supplier until the filtering is implemented.
* There's no separate "question sent" page, the message is shown on
the page with the form right now.
* Email sent to the buyer user is sent from "do-not-reply@" with
anonymised supplier name.
* Failure to send a confirmation to the supplier is ignored. So as long
as the buyer email was accepted by Mandrill the app will respond with
200.
:exclamation: This needs some content work on the error/success pages and email templates.
> Submit brief clarification questions

- app/__init__.py
- app/assets/scss/_brief-response.scss
- app/assets/scss/application.scss
- app/main/__init__.py
- app/main/helpers/briefs.py
- app/main/helpers/frameworks.py
- app/main/views/briefs.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/macros/toolkit_forms.html
- bower.json
- requirements.txt
- tests/app/main/test_briefs.py
- tests/app/main/test_services.py
This story allows suppliers to submit responses to a briefs/opportunities (hereafter referred to as a 'brief').
All of the questions for a brief response are on one page; some questions are stored entirely in the content but others are a mixture of static content and dynamic (user-submitted) essential/nice to have questions from the brief itself.
Suppliers can only submit one response per brief. (If they try to submit another, they get a 404 page -- in future we might want to redirect them to another page and display a flash message.)
It *does not* check if suppliers are eligible to submit responses to a particular brief (this depends on the [only eligible suppliers can respond to a brief](https://www.pivotaltracker.com/story/show/112216509) story)
[>> Story on …
> [#112216471] Supplier responds to a brief -- frontend

- app/templates/briefs/clarification_question.html
Adds a closing date for brief clarification question answers to the
question form help text.
Requires https://github.com/alphagov/digitalmarketplace-api/pull/357.
> Add brief clarification question closing date to form help

- .travis.yml
- package.json
We made a custom version to deal with the fact
that the version of Node that Travis uses in the VM
image for Python projects was below that required
for the NPM module (see related [stackoverflow question](http://stackoverflow.com/questions/32461456/travis-ci-can-the-version-of-node-installed-on-all-vm-images-match-the-latest)).
This is no longer the case (it's currently running
at 4.2 (using nvm) so the custom version is no
longer needed.
> Remove custom version of gulp-jasmine-phantom

- requirements.txt
Brings in a bugfix around suppliers responding to opportunities (briefs) without any nice-to-have requirements.
> Update dmutils to 19.0.1

- app/main/helpers/briefs.py
- app/main/views/briefs.py
- tests/app/main/test_briefs.py
Creates an audit event with the clarification question text when a brief question is submitted.
Reuses the existing audit event type from framework clarification questions. Since the related object type is different it is still simple to distinguish the clarification question types when listing events.
> Add an audit event for sent brief clarification questions

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/submission_lots.html
- tests/app/main/test_frameworks.py
[#113766617](https://www.pivotaltracker.com/story/show/113766617)
Before this change the supplier view of their submissions (the lot selection page) does not make a lot of sense after the framework is no longer open. In the case of Digital Outcomes and Specialists the lot titles were things like 'Apply for Digital Specialists' and link through to add a service of that type. This doesn't make sense after the framework is no longer open for submissions.
This is a bit of a hack but it solving it more correctly does not seem like a priority right now.
Here labs isn't shown because the user didn't create any draft services for it.
> Fix supplier view of submissions

- app/main/views/briefs.py
- requirements.txt
- tests/app/main/test_briefs.py
Prevent clarification questions from being submitted after the deadline.
This change also bumps the apiclient to get the latest API stub for briefs which includes the `clarificationQuestionsAreClosed` flag.
> [#116127657] No clarification questions after deadline

- app/templates/briefs/clarification_question.html
Sarah found a bug trying to return to a brief after asking a clarification question.   Basically, the URL was pointing to the wrong place. 
Easy fix.  Didn't write any tests or anything because the page it links to is in another app.  But I've manually tested it works. 
[>> Bug on Pivotal](https://www.pivotaltracker.com/story/show/116545029)
> Fix return-to-brief link on clarification page

- app/main/views/frameworks.py
- config.py
- requirements.txt
- tests/app/main/test_frameworks.py
Mandrill is going to start preventing emails from unverified domains.
This means that we will no longer be able to send emails with the From
field set to supplier email addresses. This change sets the From field
to a no-reply address on our domain and uses the Reply-To field for the
supplier email address.
> Do not send email from unverified domains

- app/main/helpers/briefs.py
- app/main/views/briefs.py
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- tests/app/main/test_briefs.py
This pull request throws up an error page if you try to apply for or submit a clarification question for an opportunity that you're not eligible for.  Error pages will tell you what you can't do and if (a) you're not on the framework, or (b) you don't provide the right service.  Hard to be more helpful than that without getting into DOS-specific messaging, which we don't want to do.
@superroz, @ralph-hawkins, and, most recently, @suedavis have all looked at it.
***
> [#112216509] Only eligible suppliers can respond to a brief

- app/templates/services/list_services.html
Since digital-outcomes and other one-service lot servicesdon't have
a serviceName field we need to show the lot name instead, similar
to what we did in the service submission page title.
> Show DOS service lot instead of name for one-lot services

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
Adds word length validation to clarification questions in addition to the character length check. Word length check is using the same expression we use in JSON schemas.
> Validate brief clarification question word limit

- app/main/views/services.py
- app/templates/services/list_services.html
- config.py
- tests/app/main/test_services.py
Enabled for 2 months on all environments, should be safe to remove.
The fallback link for service page also assumed a g-cloud service.
Since DOS services don't have an edit service manifest or a public service page on the buyer frontend to link to we don't make the service name a link for now.
There's no check in the view, so the page would 500 if visited, but at the same time there's no obvious way to find the DOS service ID required to manually construct a link.
> Don't show link for DOS services on the supplier dashboard

- app/assets/scss/application.scss
- app/main/views/briefs.py
- app/templates/briefs/clarification_question.html
- app/templates/briefs/question_and_answer_session.html
- tests/app/main/test_briefs.py
Adds a page with brief "webinar" details only visible to eligible suppliers. The page displays Q and A session details from the brief.
If the details weren't set the link from the brief page should be hidden, and this view URL will show an empty page with a "Return to brief" link.
Class is already used by frameworks/agreement.html template and the same class is defined and used in the buyer frontend.
Moves header inside the 2/3 div and fixes the order of closing tags.
> Question and answer session details

- app/main/views/frameworks.py
The decision for whether an application has been made to a framework currently checks whether there are complete drafts and a complete declaration.  This is fine for frameworks that are not yet live.
However, once a framework is made live we may at some point delete the old draft, at which point the page would show "You did not make an application" even though the supplier is on the framework.
This adds the logic that if the supplier is currently on the framework then they must have made an application to it.
> Fix framework dashboard bug

- app/main/views/briefs.py
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- tests/app/main/test_briefs.py
See this story: https://www.pivotaltracker.com/story/show/117427089
Pull request made, but still need content review from @superroz (or similar) as the words in the story aren't quite right. 
The story doesn't mention any changes to page headings, but we might want to lose `submit`?
> [#117427089] Error message content update

- app/templates/macros/toolkit_forms.html
Hides the 'nice to have requirements' question header if there are not questions defined in the brief.
> [#117922093] Hide boolean list question section if there are no questions

- app/templates/_footer_categories.html
Brings in new pages on www.gov.uk and removes links made redundant by the launch of the Digital
Outcomes and Specialists framework.
Should be merged along with https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/276
> Updated footer links for DOS launch

- app/templates/frameworks/_dashboard_lede.html
- app/templates/frameworks/updates.html
- app/templates/services/service_submission.html
- app/templates/suppliers/_frameworks_open.html
- app/templates/suppliers/_frameworks_standstill.html
- bower.json
- tests/app/main/test_briefs.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Fixes this bug: https://www.pivotaltracker.com/story/show/118112493
We already bumped content in buyer app to be in line with schemas, but supplier app is behind, so brief-responses don't match the schema in the API.
> [#118112493] Update content and frontend toolkit versions to latest

- app/main/helpers/briefs.py
- app/templates/emails/brief_clarification_question.html
- tests/app/main/test_briefs.py
Completes this story: https://www.pivotaltracker.com/story/show/117850243
Wording change agreed with @superroz : "before" in doc --> "by"
Uses the fancy new URL defined here: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/283
> [#117850243] Update supplier question email content

- app/main/views/briefs.py
- app/templates/briefs/brief_response.html
- tests/app/main/test_briefs.py
Fixes the breadcrumbs on the brief response page and adds the right title if you're returned to the response page after getting a form error.
Adds a few more tests; pretty exciting.
[>> Bug on Pivotal](https://www.pivotaltracker.com/story/show/118103013)
***
> [#118103013] Fix breadcrumbs for brief response page

- app/templates/macros/toolkit_forms.html
Completes this: https://www.pivotaltracker.com/story/show/117629721
This is already done in the buyer app, but we also need to show the advice in the supplier app.
Of questions rendered by the supplier app only the `boolean_list` questions Essentials and Nice-to-haves currently have `question_advice` set.  But I've added it to all question-rendering templates, in case other supplier questions have advice in future.
Screenshots of the relevant page once this is applied:
> Add `question_advice` to question-rendering macros

- app/assets/scss/_service_submission.scss
- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/services/edit_submission_section.html
- app/templates/suppliers/_frameworks_open.html
- bower.json
- config.py
- tests/app/main/test_briefs.py
- tests/app/main/test_services.py
Completes this story: https://www.pivotaltracker.com/story/show/118178641
And this story: https://www.pivotaltracker.com/story/show/118178637
This seems to be everything needed to get G-Cloud service submissions looking reasonably peachy:
* Show links for lots without any draft services for live frameworks
* Reinstate the save-and-continue-to-next-question flow through submissions
* Fix document download URLs (document uploads were fine, but the generated download links were wrong)
There is a bug (again! I'm sure we've fixed this about three times now...) with the validation wrapper around questions with assurance.  I've raised it as a bug rather than fix it right away, because there are other higher priorities, like getting the functional tests running again: …
> G8 service submission

- app/main/forms/suppliers.py
- app/templates/suppliers/edit_supplier.html
- bower.json
- tests/app/main/test_briefs.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Originally intended to bring in the correct text for validation summaries (from [#245](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/245) in the DM Toolkit), this now also contains the following fixes:
- fixes for the [Validation summary links don't work](https://www.pivotaltracker.com/story/show/118185295) story
- corrections to the HTML of validation summaries, replacing label tags for their text in the links and wrapping links in a list
> Fix validation messages

- app/main/helpers/validation.py
- app/templates/frameworks/edit_declaration_section.html
- app/templates/macros/toolkit_forms.html
- bower.json
Completes this story: https://www.pivotaltracker.com/story/show/118180095
Depends on updated content being merged: 
This introduces a new macro to render multiquestions in the frontend.
It assumes all questions are `text` type.
Look and feel, including validation messaging and wrapping, all OK'd by @ralph-hawkins
> Split registered address into three fields

- app/templates/macros/toolkit_forms.html
- bower.json
- requirements.txt
- tests/app/main/test_frameworks.py
This is part of the [Validate 'how many suppliers you'll evaluate'](https://www.pivotaltracker.com/story/show/118392265) story, which changes `percentage` type questions into `number` types.
Also updated the frontend-toolkit, utils, and frameworks repository.
Needs:
> Transmogrify percentage macro into number macro

- app/templates/_footer_categories.html
Part of this story: https://www.pivotaltracker.com/story/show/119175733
Will bring footer links in supplier app up to date with those here: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/312
> Remove Digital Services Framework footer links

- app/main/helpers/frameworks.py
- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/services/service_submission.html
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Depends on this version of the API running:
Fixes this bug: https://www.pivotaltracker.com/story/show/118986461
I've also done a bit of tidying up:
* removing the `has_one_service_limit` function in favour of using the `lot['oneServiceLimit']` value directly
* checking that the `framework_slug` and `lot_slug` in the URL match those of the draft being edited 
* moving to using `lotSlug` rather than `lot` (they have identical values but we want to phase out using `lot` eventually)
This broke a lot more tests than I thought it would.
> Services not labs

- app/templates/frameworks/_dashboard_lede.html
- app/templates/frameworks/updates.html
- app/templates/services/service_submission.html
- app/templates/suppliers/_frameworks_open.html
- app/templates/suppliers/_frameworks_standstill.html
- bower.json
- tests/app/main/test_frameworks.py
Required to fix:
- https://www.pivotaltracker.com/story/show/119086793
- https://www.pivotaltracker.com/story/show/119075005
Depends on: 
The markdown filter wraps values in `<p>` tags but we generally want to use dates inline and the `<p>` breaks the page layouts in the frontend.  So we're not going to use markdown for date strings.
---------------------------
---------------------------
---------------------------
---------------------------
> Don't mark dates down

- app/templates/briefs/clarification_question.html
For [this](https://www.pivotaltracker.com/story/show/118095247) story on Pivotal.
Old: "buyers' response"
New: "buyer's answer"
> Update content on 'Ask a question page'

- bower.json
For [this](https://www.pivotaltracker.com/story/show/118391123) story on Pivotal.
This PR updates the framework version used to 1.3.14. This version has a full stop on the end of the validation message that a supplier sees if they overstate their day rate when applying for an opportunity.
[This](https://github.com/alphagov/digitalmarketplace-frameworks/pull/281) PR is the update to the framework.
Screenshot of new message below:
> Add full stop to day rate validation message

- app/main/helpers/briefs.py
- app/templates/emails/brief_clarification_question_confirmation.html
For [this](https://www.pivotaltracker.com/story/show/118095523) story in Pivotal.
The content of the email which is sent to a supplier after they ask a question of the buyer has been updated.
Also, a variable which was being assigned and passed in to the email template has been removed as it was no longer required after the content update.
> Update supplier confirmation email

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
A successful application to an opportunity results in a redirect to the supplier's dashboard which has the same URL as normal. 
To track the application in analytics, this marks the request as the result of an application by adding a query string parameter to the URL.
https://www.pivotaltracker.com/story/show/119634783
> Tracking supplier applications to opportunities

- bower.json
Brings in new breakpoint to mitigate the last pricing field dropping onto the second line.
[Relevant pull request in frontend toolkit](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/266).
[>> Bug on Tracker](https://www.pivotaltracker.com/story/show/118469059)
> Update toolkit to improve pricing fields

- app/assets/javascripts/analytics/_virtualPageViews.js
- app/templates/briefs/clarification_question.html
- spec/javascripts/unit/AnalyticsSpec.js
Change needed for this story:
https://www.pivotaltracker.com/story/show/119634865
...and fixes problems with the code merged in https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/487.
The regexp that looks for the banner telling users their question was submitted didn't take whitespace into consideration so wasn't finding it. This didn't show up in the unit tests because the HTML mock used had no whitespace in its banner text:
```
\n\s\s\s\sYour question has been sent. The buyer will post your question and their answer on the ‘Dissolve a company’ page.\n
```
```
Your question has been sent. The buyer will post your question and their answer on the ‘Dissolve a company’ page.
```
> Fix issues with supplier question tracking

- app/templates/_proposition_header.html
- app/templates/frameworks/edit_declaration_section.html
- app/templates/suppliers/edit_supplier.html
Remove "Create supplier account" link from the header.
View your account link comes before the Log out link.
Unlike in the header for the buyer app, we don't have a conditional statement on the "View your account" link because nobody can even get to the supplier app without being logged in with the correct role. So it always sends logged-in users to the supplier dashboard.
We changed from `current_user.email_address` to `current_user.is_authenticated()` because it seems like a better check for if a user is logged in or not.
Most of the breadcrumb links back to the supplier dashboard say "Your account", but there were a couple that had the name of the company (which is wrong).
Changed them all to say "Your account"
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/119993369) …
> [#119993369] Update links in header

- app/main/views/briefs.py
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- requirements.txt
- tests/app/main/test_briefs.py
Ok a few caveats here:
- In this case we've switched from using the `SupplierFramework.onFramework` to determine the supplier's "on framework"-ness to poking the api to see if the supplier has any published services on the lot or framework. However, there are still a few bits of this frontend that do use `onFramework` for various things. So I guess there's some possibility of an incongruence here. From what I can tell the only functional difference will be for suppliers who've had services removed for some reason. And most of the other places `onFramework` is used in this frontend seem to be during the pre-live phase. So maybe... it's... all... ok?
- Depends on `digitalmarketplace-apiclient` 3.8.0, which isn't merged yet.
- Tests had to be changed a bit, and I hope I still captured the …
> [#118392929] Update error message if supplier isn't eligible

- app/assets/javascripts/analytics/_register.js
`window.location.href` is wrapped in an interface to allow easier testing.
When it was implemented, it was done so with this error.
> Fix analytics wrapper for window.location.href

- app/templates/_footer_categories.html
- app/templates/_proposition_header.html
- bower.json
Upgrading the toolkit brings in the latest govuk frontend and slightly mitigates the problem where [the pricing field layout breaks if you have a scrollbar enabled on your browser](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/266).  
Also got rid of the `home` class which was being applied to a couple of header links and a footer link.
Very well researched.  Read the commit message.
I didn't notice any layout changes applying this pull request, so it should be totally invisible to users.
> Upgrade toolkit and remove superfluous "home" class from header/footer links

- app/assets/javascripts/analytics/_virtualPageViews.js
- spec/javascripts/unit/AnalyticsSpec.js
We hypothesise that Google Analytics needs to be sent the `pathname` of the current URL for a pageview rather than the full URL so this enables that change.
> Send page pathname rather than whole URL

- app/templates/frameworks/agreement.html
- bower.json
**Note: needs https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/269 to be merged first.**
Includes a fix for the changed `instruction-list` pattern, which is only used on the framework agreement page.  No other breaking changes.
> Update toolkit to 16.0.0

- app/templates/briefs/view_response_result.html
The default evaluation type isn't passed in (as I thought it would be), so for briefs without and additional evaluation types specified the page breaks with 500.  This prevents errors, but still needs more work to show the default evaluation type in the list.
> Don't assume there is an evaluation type

- app/main/__init__.py
- app/main/views/briefs.py
- app/templates/briefs/_brief_response_data.html
- app/templates/briefs/view_response_result.html
- tests/app/main/test_briefs.py
Should hopefully be the final bugfix for: https://www.pivotaltracker.com/story/show/121479497
The default evaluation types defined in the frameworks content are not stored in the brief object JSON at all, and are only added to the brief when `.summary` is called in the content loader.
So in order to be able to display all evaluation methods that will be used, including the defaults, we need to load the `edit_brief` manifest and call `.summary` with the current brief.
Here you can see the default "a work history" is displayed, despite not being stored in the brief data:
> Display the default evaluation type for brief responded to

- app/assets/scss/_text.scss
- app/assets/scss/application.scss
- app/main/forms/frameworks.py
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/emails/framework_agreement_with_framework_version_returned.html
- app/templates/errors/404.html
- app/templates/errors/500.html
- app/templates/frameworks/_dashboard_lede.html
- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/contract_review.html
- app/templates/frameworks/contract_start.html
- app/templates/frameworks/contract_submitted.html
- app/templates/frameworks/signature_upload.html
- app/templates/frameworks/signer_details.html
- app/templates/suppliers/_frameworks_standstill.html
- app/templates/suppliers/companies_house_number.html
- app/templates/suppliers/company_contact_details.html
- app/templates/suppliers/company_name.html
- app/templates/suppliers/create_new_supplier.html
- app/templates/suppliers/create_your_account_complete.html
- app/templates/suppliers/duns_number.html
- config.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
- tests/app/test_application.py
Built multipage flow to handle signing and returning your framework agreement
- Contains table of which lots you have passed and which you did not apply for
- Instructions for how to return your framework agreement
- The link to download your signature page is to a unique file for each company (TO BE COMPLETED)
- Form to get `signerName` and `signerRole`
- Form is validated by `form.validate_on_submit` after which values are sent to the API (which also does its own validation)
- If `signerName` and `signerRole` already exist in `agreementDetails` then these are prefilled in the form
- If filename exists in session, when the form is submitted you are taken straight to the contract review page as you have likely been editing your signer details
- Upload PDF, JPG or PNG file
- Validation …
> [#121577345] Sign and return your framework agreement

- app/main/views/frameworks.py
- app/templates/frameworks/contract_start.html
- requirements.txt
- Add G-Cloud 8 framework link directly to PDF
- Bump utils to 21.3.0
- Use `SIGNATURE_PAGE_FILENAME` to generate link to users signature page
This is the final part of [this pivotal story](https://www.pivotaltracker.com/story/show/121577345) and has come slightly later than the [previous pull request](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/506) as we were awaiting content.
> Add framework links and bump utils to 21.3.0

- app/main/views/frameworks.py
- app/templates/frameworks/contract_submitted.html
- tests/app/main/test_frameworks.py
Fixes three issues thrown up in testing by @andrewchong 
- Add missing "." 
- Replace link to DOS with G-Cloud 8 link
- Remove `signature_page` from session after a framework agreement as a) no longer needed and b) to minimise the risk of old incorrect data being shown to a user
> [#121577345] QA fixes frontend and copy fixes

- app/main/views/frameworks.py
`supplier_pack_filename` had been forgotten from our variables passed through to the template, causing the 'Download guidance and legal documentation (.zip)' link to break.
> Fix missing `supplier_pack_filename` variable from template

- app/main/views/frameworks.py
- requirements.txt
- tests/app/main/test_frameworks.py
We want to be able to track whenever changes are made to signature pages.
Through the API, we can track all changes to things we store in agreementDetails, but we don't know anything about file uploads.
This audit event tells us when files are uploaded, who did the uploading, and what their original filenames were.
> Add audit event for signature page uploads

- app/main/views/briefs.py
Users must be logged in to download brief responses.
Previously if no user was logged in then this route gave a 500 error as no supplier ID could be found for the anonymous user.
> Require login to download responses to a brief

- app/templates/frameworks/_guidance_links.html
was previously outputting an `ul` directly within another `ul` in the live/standstill state. instead put both possible blocks in a `li.browse-list-item`.
spotted this while digging in the wrong place for another story. all this patch does is move the `li.browse-list-item` outside the `{% if %}` block.
> framework dashboard guidance links: minor fix for html

- app/main/views/frameworks.py
- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/_submitted_services.html
by rehashing the way we pass lot data to templates. this code seems to have missed out on the addition of `unitSingular` and `unitPlural` to the lots table, so use that. rather than doing laborious cherry-picking of lot dict items we may as well just pass copies of the api-supplied lot dicts themselves with our added data annotated on.
this fell out of #508
> framework dashboard: fix pluralization of lot units

- bower.json
- requirements.txt
[This story](https://www.pivotaltracker.com/story/show/122114497) is for the top of the 'apply for this opportunity' page, add content for specialists only that says you can only put one specialist forward for each role.
Now that pull requests for the [copy changes](https://github.com/alphagov/digitalmarketplace-frameworks/pull/293) in the frameworks repo and the [ability to filter descriptions](https://github.com/alphagov/digitalmarketplace-content-loader/pull/6) in the content loader repo have been merged we are able to update our dependencies to bring the new content in to the supplier app.
> [#122114497] Bump content loader to 1.2.0 and frameworks to 2.0.0

- app/templates/_footer_categories.html
This reverts commit 01be2f635a3a3307bb5bdcdacee62992afa0c747. Long email address determined ugly.
> [#124104671]Revert "global footer: change visible text of support link to email address"

- app/main/views/login.py
- app/templates/suppliers/dashboard.html
- tests/app/main/test_login.py
- tests/app/main/test_suppliers.py
Currently, we are not able to tell using GA how many user accounts have been created. We could try to use a page view of the URL after an account is created to indicate this, however the URL is also accessible from other user flows and will not therefore be an accurate count of how many user accounts have been created. 
Therefore, as part of [this pivotal story](https://www.pivotaltracker.com/story/show/127062871), we wish to send a GA virtual page view every time a supplier account is successfully created. By embedding
`data-analytics="trackPageView" data-url="/suppliers/vpv/?account-created=true"`
into our template, we will send the required virtual page view on the success page(functionality [already exists](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/ap …
> [#127062871] Track account creation using GA virtual page views

- config.py
This adds a new feature flag `CONTRACT_VARIATION` to the app config, and sets it on for test and development modes.
I'm submitting it as it's own PR now because several stories in the backlog need to use this flag, and we don't want later stories blocked just on waiting for this flag to be merged.
This will allow conditional sections within a page template to be marked as:
```
{% if 'CONTRACT_VARIATION' is active_feature %}
...
{% endif %}
```
And entire page routes can be hidden behind the feature flag using the annotation:
```
@flask_featureflags.is_active_feature('CONTRACT_VARIATION')
```
(As described in [the documentation](https://github.com/alphagov/digitalmarketplace-utils#using-featureflags))
> Add feature flag to hide contract variation features until ready

- app/assets/javascripts/analytics/_pageViews.js
- app/main/views/briefs.py
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- spec/javascripts/unit/AnalyticsSpec.js
- tests/app/main/test_briefs.py
[Pivotal story](https://www.pivotaltracker.com/story/show/126116679)
When a supplier clicks to apply for a brief they can be one of 4 states:
1. are eligible and can apply
2. are not eligible as they are not on the framework
3. are not eligible as they are not on the lot
4. are not eligible as they can not provide the specialist role
After clicking the button to apply for a brief, in all of the above cases, they are taken to the same URL. In the success case (eligible) they are shown the form to apply. In the failure case (not eligible) they are shown the relevant message for why they can not apply to this brief. We wish to add analytics to this page so we can track the 4 cases. This is done by setting a Google Analytics custom dimension with a value related to one of the 4 cases.
- For …
> Analytics to tell if a supplier is eligible to apply for a brief

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
Part 3 of this bug fix: https://www.pivotaltracker.com/story/show/128509823
Allows suppliers to continue to see their response after a brief closes.
Depends on:
Should be released before:
> [#128509823] Supplier can view their response to a closed brief

- app/assets/scss/application.scss
- app/main/forms/frameworks.py
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/emails/g-cloud-8_variation_1_agreed.html
- app/templates/frameworks/contract_variation.html
- bower.json
- config.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
For this story: https://www.pivotaltracker.com/story/show/127807161
Depends on API changes here: 
~~There are minor content updates to come on Monday morning, but worth getting this up now for people to take a look.~~
Content updated to latest from document on 21/8/2016, screenshots here updated.
UPDATE: New validation message screenshot updated.
> [#127807161] Display contract variation page

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
For [this](https://www.pivotaltracker.com/story/show/127807417) story on Pivotal.
Will need rebasing on top of [this](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/522) once it's merged before tests can go green.
If a user returns their framework agreement but has not agreed
to the framework variation then redirect them to the variation.
If a user returns their framework agreement and has agreed to the
framework variation then redirect them to the framework dashboard.
If there are no framework agreement variations for a framework then
the user should redirect to the framework dashboard.
Functionality is built under the assumption that a framework will
have no more than one variation. Removing this assumption would
add a reasonable amount of complexity, such as …
> Redirect to contract variation after returning framework agreement

- app/templates/frameworks/contract_submitted.html
- tests/app/main/test_frameworks.py
If a supplier has returned their framework agreement then their documents page will show a link to any proposed contract variations.
Words agreed with Cath and Laurence.
Looks like this:
> Add link to contract variation page to framework dashboard

- .travis.yml
We've seen travis builds fail sometimes during npm install, so maybe [caching the dependency paths][1] will help to avoid this.
This might introduce other issues though, with stale cache causing the build to run outdated code, so keep in mind you might need to clear the travis cache if the build fails unexpectedly.
[1]: https://docs.travis-ci.com/user/caching
> Enable Travis cache for pip, npm and bower

- app/main/views/briefs.py
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- tests/app/main/test_briefs.py
Story https://www.pivotaltracker.com/story/show/129454097
We weren't filtering a supplier's services by those `published` when determining the reason for their non-eligibility, hence might make false deductions. So instead now filter all these queries for `published` services.
First created regression tests that fail with existing code, then added fix.
Also @idavidmcdonald I merged most of your separated `data-reason`-checking tests into their corresponding standard tests - if you can get away with testing for something by adding an assert to an existing test, there's no reason not to do it that way. Here I needed to create two new variants of the standard tests - if the asserts for the `data-reason` are included, when I copy the tests to create the new variants I get the …
> [#129454097]Brief eligibility error messages fix

- requirements.txt
Makes the app log 5xx responses with ERROR level, which is useful for frontend apps since their responses can fail when the API responds with 5xx and no exceptions get logged.
This is the only frontend app that doesn't have the up-to-date utils version yet.
> [#119736241] Update utils to include 5xx ERROR logging

- app/templates/frameworks/contract_variation.html
- config.py
Two for the price of one...
This bugfix: https://www.pivotaltracker.com/story/show/130297677
Plus turning on existing supplier service editing in Pre-Live environments, so we can see what still needs building.
> [#130297677] Unicode bugfix plus supplier editing pre-live

- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_login.py
- tests/app/main/test_suppliers.py
We recently ran into a production bug caused by non-ascii characters in a supplier user's name.
This adjusts the tests to login as users with non-ascii characters in their name and supplier name, so hopefully there will be less chance of a similar bug making it through to production in future.
> Adjust tests to run with non-ascii chars in supplier users

- app/templates/frameworks/contract_variation.html
The 'I accept these proposed changes' button on the contract variations page has a `<label>` tag nested inside its `<label>` tag instead of just a text string.
```
<label class="selection-button" for="input-accept_changes-1">
<label for="accept_changes">I accept these proposed changes</label>
<input type="checkbox" name="accept_changes" id="input-accept_changes-1" value="Yes, I accept the changes">
</label>
```
This is because `form.accept_changes.label` is assumed to be a string in the template whereas it is actually an instance of the`wtforms.fields.Label` helper class:
http://wtforms.readthedocs.io/en/latest/fields.html#wtforms.fields.Label
This changes the reference to point to the `text` property instead which is a string:
http://wtforms.readthedocs.io/en/latest/fields.html#wtforms.fi …
> Make 'Accept changes' field use correct property

- app/main/views/frameworks.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
This ensures that the supplier frontend saves the uploaded agreement file path into our database on upload.
These paths are not yet used by the frontend for rendering things, but they will be soon.
> Save agreement path on upload

- app/main/views/frameworks.py
- app/templates/frameworks/contract_submitted.html
- app/templates/frameworks/contract_variation.html
- bower.json
- tests/app/main/test_frameworks.py
For this story: https://www.pivotaltracker.com/story/show/128669753
Tests won't pass until this is merged:
New content is conditional on this migration to set countersigner details:
This can be released whenever because no changes will be visible until the API PR is merged. Once the countersigner details are set by the migration then the following changes happen:
(Previously "Read the proposed contract variation")
> [#128669753] Content updates for when contract variation is agreed by CCS

- app/templates/frameworks/contract_variation.html
- tests/app/main/test_frameworks.py
Once the contract variation is agreed we don't want the title to say "proposed".
> Remove "proposed" from page title if countersigned by CCS

- bower.json
Changes brought in can be seen here:
https://github.com/alphagov/digitalmarketplace-frameworks/compare/v3.3.0...v3.3.2
I've had a look locally and all seems to be working fine.
> Pull in latest content for DOS2 submissions

- app/assets/scss/application.scss
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/contract_review.html
- app/templates/frameworks/contract_start.html
- app/templates/frameworks/signature_upload.html
- app/templates/frameworks/signer_details.html
- bower.json
- requirements.txt
- tests/app/helpers.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
For this story: https://www.pivotaltracker.com/story/show/130358101
** UPDATED WITH SMALLER SPACE ABOVE BUTTON **
Now depends on this being merged before tests will pass: 
These changes make it so that FrameworkAgreements are updated directly rather than via a SupplierFramework.
For pre-G-Cloud-8 frameworks this means making three API calls in a single route (i.e. to  create, add signer details and "sign" the agreement).
For G-Cloud-8 and beyond the new signing agreement flow now creates a FrameworkAgreement when the new "Return your signed signature page" button is first clicked (it's currently a link not a button):
and the ID of the FrameworkAgreement thus created becomes part of the  URL for subsequent pages, allowing the FrameworkAgreement to be updated  directly with first the signer …
> [#130358101] Update FrameworkAgreements directly 

- app/main/views/briefs.py
- requirements.txt
- tests/app/main/test_briefs.py
Will set the brief response to be submitted for our existing one page flow. This will allow us to then do a data migration and set all brief responses as submitted.
Send page questions when creating a brief response. This is a preemptive change as the API will shortly be validating content when creating a brief response based on page questions rather than all questions in the schema as it does at the moment. This is similar to when creating a brief.
Tests will fail until [API client pull request](https://github.com/alphagov/digitalmarketplace-apiclient/pull/55) is merged.
> Brief responses call submit route on api

- app/main/views/frameworks.py
- app/templates/frameworks/agreement.html
- app/templates/frameworks/contract_start.html
- app/templates/frameworks/contract_variation.html
- app/templates/frameworks/edit_declaration_section.html
- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- app/templates/macros/toolkit_forms.html
- app/templates/partials/service_warning.html
- app/templates/services/_base_edit_section_page.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
- app/templates/suppliers/_frameworks_coming.html
- app/templates/suppliers/_frameworks_open.html
- bower.json
- requirements.txt
- tests/app/main/test_briefs.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
Since section fields can go through additional processing with Jinja we need to ensure we're always calling .filter before displaying them to the user so that we don't accidentally display template source.
> Always call .filter before displaying section data

- app/templates/suppliers/companies_house_number.html
- app/templates/suppliers/company_name.html
- app/templates/suppliers/duns_number.html
Supplier registration questions are manually using toolkit form templates, so they were affected by the removal of safe filters from the toolkit.
> Fix HTML descriptions in supplier registration forms

- bower.json
Preview seems to have old content loaded even though version is listed as 4.0.2.
Bumping toolkit version mainly as a means to forcing a reload on preview :/
> Update frontend toolkit version

- app/assets/scss/_phase_banner.scss
- app/assets/scss/application.scss
- app/templates/_base_page.html
- app/templates/_phase_banner.html
Replaces the in-app beta banner with the new toolkit version.  
Means we can delete a couple of files.
Largely the same as I'm doing in the [buyer frontend](https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/399).
> Replace in-app beta banner with new toolkit version

- app/templates/briefs/clarification_question.html
This was rendering with the verbatim html tags ever since the `markdown` filter was removed from the toolkit testbox template.
Works now though.
***
> Add safe tag to "ask a brief question" description

- app/main/views/briefs.py
- app/templates/briefs/start_brief_response.html
- config.py
- requirements.txt
- tests/app/main/test_briefs.py
For [this pivotal story](https://www.pivotaltracker.com/story/show/130018567)
- Adds the start page for applying to a brief response. Content is specific to the lot.
- For the moment, redirects to a temporary holder route but will in future go to the new flow for applying to a brief
- If no brief response exists, then the button says 'Start application' and clicking it will create a new draft brief response
- If a draft brief response exists, then the button says 'Continue application'. When we create the new flow (as part of [this pivotal story](https://www.pivotaltracker.com/story/show/129843611)) this button will need to link to their existing brief response application.
- If a brief response already exists then they are redirected to their already submitted brief response.
Will need …
> #130018567 Start page for supplier applications

- app/main/views/frameworks.py
- app/templates/frameworks/_agreement_returned_legal.html
- app/templates/frameworks/_guidance_links.html
- tests/app/main/test_frameworks.py
Addresses this bug: https://www.pivotaltracker.com/story/show/134161817
Call-off contracts have a "proposed" and "final" version, which we were previously missing.
Also, we shouldn't just have "agreement" files - they should always be "framework-agreement" for clarity.
**NOTE**: I have already created all the required files in S3 for all environments (i.e. duplicated the current files with new filenames), so links should work fine once this is released without any further S3 wrangling required (obviously it will need testing in Preview/Staging to be sure though).
> Update guidance file links

- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/_guidance_links.html
Fixes this bug: https://www.pivotaltracker.com/story/show/134350957
(I also picked up another issue that the "result letter" link wasn't appearing for FAILed G-Cloud 8 suppliers.  All failed suppliers get a letter, even on the "new" style frameworks.)
> Always show legal docs

- app/templates/macros/assurance.html
Missing "safe" filter on template string fixed for [#134680667].
> [#134680667] mark assurance hint as safe

- requirements.txt
This is technically a breaking change because it removes the `|markdown` filter from jinja, which means we can't use it in our templates in this app anymore.
Fortunately, we've removed all uses of `|markdown` in this app, so there aren't any changes needed.
> Update utils version

- app/main/__init__.py
- app/main/views/briefs.py
- bower.json
Brings in the renamed brief response manifests from https://github.com/alphagov/digitalmarketplace-frameworks/pull/330.
Tests will fail until https://github.com/alphagov/digitalmarketplace-frameworks/pull/330 is merged.
> Use renamed brief response manifest

- .cfignore
- requirements.txt
We're running gunicorn when deploying apps to PaaS, so it has to be listed in the requirements file.
Lists folders ignored by `cf push`. Significantly speeds up PaaS deployments. Contents copied from the buyer frontend.
> Supplier frontend on PaaS

- app/assets/scss/_supplier-declaration.scss
Because it causes overlap of validation side borders.
Story https://www.pivotaltracker.com/story/show/131267691
> [#131267691]supplier declaration question css: don't out-dent question numbers in non-wide mode

- bower.json
Story https://www.pivotaltracker.com/story/show/133024283
Before:
After:
> [#133024283]frontend toolkit: bump dependency to version 19.2.1 to fix service summary table action link padding

- app/templates/frameworks/_guidance_links.html
- tests/app/main/test_frameworks.py
to determine whether to show prompts for clarification questions instead of just framework.state being "open".
Add a test that covers this.
Would be quite good to get this out quickly as it's currently showing misleading text on production.
> framework_dashboard: heed framework.clarificationQuestionsOpen

- config.py
This is by request of Andrew so staging is the same as production and we can use it for testing the existing supplier flow.
> Turn off new supplier flow feature flag on staging

- app/main/views/login.py
- requirements.txt
- tests/app/main/test_login.py
stops personally identifiable information being committed to logs. also clean up file so we're not calling `.get` to get values out of dicts that we always need to be there. also don't pass in `role` to decode_token anymore
bump dmutils to 23.0.0 for this
> encrypt email tokens

- tests/app/main/test_briefs.py
For [this pivotal story](https://www.pivotaltracker.com/story/show/134427911).
Our IT health check flagged issues with XSS vulnerabilities for brief data. These have been fixed in the content loader however we also wish to double check they have indeed been fixed on the front end (as there is the possibility to override the content loader and put unsafe content into pages). 
Whilst we are doing so, we also check that markdown is escaped (again the content loader should be doing this but could be overwritten).
There are several different brief response fields playing back information (essential requirements, nice to have requirements, start date, day rate). The pivotal story lists exactly what pages need testing and what for (i.e. xss/markdown/both).
> [#134427911] Add tests for markdown and html escaping brief content

- app/main/views/briefs.py
- config.py
- tests/app/main/test_briefs.py
Part of this story on Pivotal [https://www.pivotaltracker.com/story/show/129843611](https://www.pivotaltracker.com/story/show/129843611).
This PR is a small update to the supplier frontend which allows the new style brief-responses to work end to end. Without it, new style brief responses would cause the app to fall over after submission.
There is a check made when viewing the response result that all of the `essentialRequirements` are True. The new style brief responses do not have this key, instead it they have `essentialRequirementsMet` which is just a boolean. This PR makes the app check if this new key exists and if it's True, before checking the original `essentialRequirements` key.
> Allow end to end flow for new brief responses

- Makefile
We've had a problem installing cryptography on local machines,
one solution to which is to make sure your is updated.
This pull request would add a step to the Makefile to always
upgrade pip before installing the rest of the requirements.
If we want to do this, I can port it to the other apps.
[Issue discussion on github](https://github.com/pyca/cryptography/issues/2350#issuecomment-179321979)
We could also just put something into the README, if that was a lower-overhead thing people would me more comfortable with.
> [Proposal] Upgrade pip every time to kill the cryptography bug

- app/templates/briefs/start_brief_response.html
- bower.json
A content tweak for the following pivotal story - https://www.pivotaltracker.com/story/show/129839965
Content changes outlined in [this google doc](https://docs.google.com/document/d/1TDZhOjV9ykfPA0tMoWbxS8oZzyGXG8B7lOF51SRRaO4/edit?ts=5852b310)
Tests will fail until the related [frameworks pull request](https://github.com/alphagov/digitalmarketplace-frameworks/pull/346) is merged.
For the start page we were using the word "criteria". We now use "requirements"
For the essential requirements met page we use "essential skills and experience" instead of "essential requirements.
> Consistent content for essential requirements

- app/main/helpers/frameworks.py
- app/main/views/briefs.py
- bower.json
- requirements.txt
- tests/app/main/test_briefs.py
[Pivotal story](https://www.pivotaltracker.com/story/show/129841565)
- Pulls in latest frameworks repo giving us a new page for the new `essentialRequirements` dynamic list question
- Corresponding tests for the new page
- Uses the content loader `unformat_data` to transform brief response data into form data (see nice example of unformatting [here](https://github.com/alphagov/digitalmarketplace-content-loader/blob/master/dmcontent/questions.py#L315) in the content loader)
> Essential requirements evidence

- app/main/views/frameworks.py
- app/templates/frameworks/contract_start.html
The template here had a G-Cloud 8 URL hard coded.  I've changed it to instead use the `framwork_url` from the content of the relevant framework.
> Use framework URL from content

- app/assets/javascripts/_selection-buttons.js
- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- app/main/views/briefs.py
- app/templates/macros/toolkit_forms.html
- bower.json
- package.json
- requirements.txt
- tests/app/main/test_briefs.py
Part of this story on Pivotal [https://www.pivotaltracker.com/story/show/129841633](https://www.pivotaltracker.com/story/show/129841633).
This PR updates the supplier frontend to deal with the new nice-to-have-requirements question
The nice-to-have-requirements question uses the progressive disclosure pattern to collect the suppliers evidence. This requires an updated version of the govuk frontend toolkit.
The new version of the content loader fixes a bug with the unpacking of brief_response data for dynamic lists questions.
Finally, a small update to the `update_brief_response` view to only replay the form data from a POST request if the request fails validation. Previously the form date was being merged with the service data already pulled from the api, and this was causing issues with …
> Add nice to have question to new supplier flow

- bower.json
- tests/app/main/test_briefs.py
Part of this story on Pivotal [https://www.pivotaltracker.com/story/show/135599725](https://www.pivotaltracker.com/story/show/135599725)
See complimentary PR on the frameworks here: [https://github.com/alphagov/digitalmarketplace-frameworks/pull/354](https://github.com/alphagov/digitalmarketplace-frameworks/pull/354)
See complimentary PR no the api here [https://github.com/alphagov/digitalmarketplace-api/pull/513](https://github.com/alphagov/digitalmarketplace-api/pull/513)
The PR on the frameworks repo will need to be merged and tagged before tests go green.
The frameworks repo has been updated to include the availability question for responses to user research participants briefs. Previously different lots had separate availability questions with separate content. They've now been …
> Test content of availability question for all lots

- bower.json
- tests/app/main/test_briefs.py
For this story on Pivotal: [https://www.pivotaltracker.com/story/show/135599725](https://www.pivotaltracker.com/story/show/135599725)
Needs this PR on the frameworks to be merged before tests will pass. [https://github.com/alphagov/digitalmarketplace-frameworks/pull/360](https://github.com/alphagov/digitalmarketplace-frameworks/pull/360)
This version of the frameworks repo removes a trailing full stop in the availability question for brief-responses. If a buyer includes a full stop at the end of their requirements, you get two full stops on the page and it looks weird. See the pivotal story for an example.
> Remove full stops from brief-response availability question

- app/main/views/services.py
- app/templates/services/_base_service_page.html
- tests/app/helpers.py
- tests/app/main/test_services.py
Story https://www.pivotaltracker.com/story/show/136029251
(tl;dr we're adding a flash message that says "You’ve edited your service. The changes are now live on the Digital Marketplace.")
> [#136029251]service editing: add "service updated" flash message & tests

- requirements_for_test.txt
- tests/app/helpers.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/helpers/validation/test_g7_declaration.py
- tests/app/main/test_application.py
- tests/app/main/test_briefs.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_login.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
- tests/app/main/test_users.py
- tests/app/status/test_status.py
- tests/app/test_application.py
~~This sits on top of https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/589 because the alternative would have caused muchos merge conflicts with it, so will have to wait till that's in.~~
Most significant thing here is the removal of nose, but some uses of mock's `.*called*` assertions have been converted to less error-prone forms.
> Old test framework purge: supplier frontend edition

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
We should skip the nice to have requirements evidence and page and go straight to the essentialRequirements page if the brief has no nice to have requirements.
Bug fix for https://www.pivotaltracker.com/story/show/137359355
> Fix bug for previous page link when no nice to have requirements

- app/templates/briefs/start_brief_response.html
- tests/app/main/test_briefs.py
For this story - https://www.pivotaltracker.com/story/show/138429463
Question for reviewer. Is this the best way to do the tests, by creating a test helper class and then the main test classes inheriting from both `BaseApplicationTest` and `BriefResponseTestHelpers` or instead should we create `BriefResponseTest` that inherits from `BaseApplicationTest` and then our main test classes just inherit from `BriefResponseTest`?
> Add breadcrumbs to brief response start page

- app/main/__init__.py
- app/main/helpers/validation.py
- app/templates/emails/g-cloud-9_application_started.html
- app/templates/macros/toolkit_forms.html
- app/templates/services/_base_edit_section_page.html
- bower.json
This PR:
- Pulls in the latest content including skeleton G-Cloud 9
- Loads the G-Cloud 9 manifests on startup
- Adds a welcome email template for G-Cloud 9
- Fixes a few small multiquestion bugs:
* showing "None" as a question number
* only rendering textboxes as sub-questions
* not passing validation errors properly to sub-questions
Tested locally and declaration and G9 service submissions work OK.
> Bootstrap G-Cloud 9

- app/main/__init__.py
- app/main/views/briefs.py
- app/templates/briefs/_brief_response_data.html
- app/templates/briefs/_legacy_view_response_result_content.html
- app/templates/briefs/view_response_result.html
- tests/app/main/test_briefs.py
More specifically, makes the brief response results page work for both formats of data. The tests will not pass until [#363](https://github.com/alphagov/digitalmarketplace-frameworks/pull/363) on the content loader is merged.
This almost doubles the amount of tests for the page so is best read commit-by-commit.
> Make brief response results page work for new flow

- LICENCE
I was looking for a licence to send someone as an example and noticed that this one doesn't make it clear it's the MIT licence. This PR changes that, to make it easier for people to understand what licence is being used.
> Make it clear that this is the MIT licence

- bower.json
Pull in latest frameworks for draft g9 hosting+software questions.
> bump version dependency for dm frameworks

- app/main/views/briefs.py
- app/main/views/services.py
- tests/app/main/test_briefs.py
Backwards compatability as migration will soon land changing `framework.framework` from 'dos' to 'digital-outcomes-and-specialists'
> update hard coded reference to DOS framework

- app/main/views/services.py
`framework.framework` has now been migrated to be 'digital-outcomes-and-specialists' rather than 'dos'. The line removed was to maintain backwards compatibility whilst that migration was rolled out.
> Remove reference to old `framework.framework` value

- app/templates/services/list_services.html
- tests/app/main/test_services.py
For [this chore on Pivotal](https://www.pivotaltracker.com/story/show/139269583).
In the list view of services, if a service is a DOS service we don't
provide a link to edit that service. This was achieved by comparing the
services `frameworkName` to the string
`digital-outcomes-and-specialists`. This wouldn't work for DOS2.
We now compare using the recently update `frameworkFramework` which will
be `digital-outcomes-and-specialists` for all DOS services, regardless
of the framework iteration.
> Use frameworkFramework when rendering service name

- app/main/views/services.py
- app/templates/macros/toolkit_forms.html
- app/templates/services/_base_service_page.html
- app/templates/services/edit_submission_section.html
- bower.json
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_services.py
One question per page flow for supplier services.
This changes the service specification flow for suppliers and moves towards a 'one question per page' standard. On the summary page, per-section editing is disabled and a link to add/edit answers is shown next to each question. As you work through the service spec, each question will follow on to the next question in the same section; when you reach the end of the section you will be returned to the service summary.
Included in this PR is a bugfix for multiquestions that will allow them to display any question type as children without individually specifying/checking the type each time.
> [194] One question per page

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
Part of this story: [https://www.pivotaltracker.com/story/show/139283847](https://www.pivotaltracker.com/story/show/139283847)
When we expire DOS1, suppliers will still need to be able to apply to live DOS1 briefs and view their previous responses.
This does that.
Also see this PR on the API: [https://github.com/alphagov/digitalmarketplace-api/pull/543](https://github.com/alphagov/digitalmarketplace-api/pull/543)
> Keep DOS1 functional when it's expired

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/reuse_declaration.html
- app/templates/frameworks/start_declaration.html
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
https://www.pivotaltracker.com/story/show/138323285
* Helper function for framework ordering
* Helper function to get a reusable declaration given a supplier
* New view reuse_framework_supplier_declaration to determine whether to ask if we should reuse
* New view reuse_framework_supplier_declaration_post to set prefill preference based on form
* New template app/templates/frameworks/reuse_declaration.html for reuse page
(as per http://dm-prototype.herokuapp.com/structure/declaration-start-page/declaration?thisPage=declaration-reuse)
* Change start declaration 'next page' to new reuse page
* Bump apiclient dependency version
* Tests
Requires: https://github.com/alphagov/digitalmarketplace-api/pull/539
> 138323285-declaration_reuse_view

- app/main/views/frameworks.py
- app/templates/frameworks/edit_declaration_section.html
- tests/app/main/test_frameworks.py
All on the declarations page:
* Save and continue
* See what is coming Next
* Save and return to the declaration overview.
* Remove 'make decl' button from last page
* Hook up the breadcrumb back to the overview page
> 138702235-save-and-continue-and-save-button-on-declr

- app/main/views/services.py
- tests/app/main/test_services.py
This PR:
* Fixes a bug with copying services; one-question-per-page services could not generate the correct URL to redirect to as the logic was missing.
> FIX: Copying draft services

- app/assets/javascripts/_analytics.js
- app/assets/javascripts/_selection-buttons.js
- app/assets/javascripts/_shim-links-with-button-role.js
- app/assets/javascripts/application.js
- app/assets/scss/_footer.scss
- app/assets/scss/_supplier-declaration.scss
- app/assets/scss/application.scss
- app/templates/auth/create_user.html
- app/templates/macros/toolkit_forms.html
- app/templates/suppliers/edit_supplier.html
- bower.json
- package.json
- tests/app/main/test_briefs.py
This pull request
- updates the govuk_frontend toolkit to the latest
- updates the digitalmarketplace frontend toolkit to the latest
- [brings in the new radios/checkboxes](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/302)
- treats links with a `role="button"` as buttons (ie, "Apply for this opportunity" link)
- removes some unused classnames
💥  Explosion noise 💥
> Bring in new toolkit with new input fields

- app/assets/javascripts/application.js
- app/templates/briefs/_brief_response_data.html
- app/templates/macros/toolkit_forms.html
- bower.json
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_briefs.py
- tests/app/main/test_frameworks.py
This PR:
* Updates the content-loader to 3.1.1, which enables support for followup questions/questions with dependencies.
* Updates the dm-frontend-toolkit to 21.0.0.
* Updates dm-frameworks to 6.2.0
* Pulls in show-hide-content.js from dm-frontend rather than govuk-frontend.
* xfail test_display while declaration is changing; too many changes and too complex a test.
> Update dependencies for followup questions

- app/main/views/frameworks.py
- app/templates/frameworks/edit_declaration_section.html
- app/templates/macros/toolkit_forms.html
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
Here we have working code that pretty much completes:
https://www.pivotaltracker.com/story/show/138702601 (Pre-filling relevant declaration sections with answers from a previous framework)
https://www.pivotaltracker.com/story/show/138703089 (Adding blue banners and validation-style blue messages to pre-filled pages)
~~**NOTE**~~ 
~~!!!!!!!!! There are no new unit tests at all for this new behaviour :scream:  !!!!!!!!!~~
~~Feel free to pick this up and add some relevant tests.~~
~~Or review it and merge it in if you feel like seeing it all working on Friday, and on my honour I will add the required unit tests on Monday.~~
**UPDATE 26/2: Tests added and rebased up-to-date - now 100% ready for review.**
Here's a screenshot:
> Prefill declaration sections

- app/main/views/briefs.py
- requirements_for_test.txt
- tests/app/main/test_briefs.py
Reviewers, please read the pivotal story with comments first - https://www.pivotaltracker.com/story/show/139468419
POST route now handles three cases
- no existing brief response
- existing draft brief response
- existing submitted brief response
If you click the 'Start application' button and you have an ongoing application that has not been submitted you should be redirected to the application flow at the start for your existing application which is prefilled (similar to the continue application button).
If you click the 'Start application' button and you have already applied and completed an application you should be redirected to your response page with a error message saying 'you have already applied' or to that effect, again the same as the continue application button.
I wanted to …
> Fix bug with POST to 'responses/start' if brief response exists

- app/main/helpers/validation.py
- bower.json
This should fix multiquestion madness, but tests won't pass until https://github.com/alphagov/digitalmarketplace-frameworks/pull/393 is merged.
Before
After
~~~Also have slipped in a fix whereby the validator was expecting a field named `distortedCompetition` instead of  `distortingCompetition`.~~~
None of these changes were covered by the tests, which is a bit scary...
> frameworks dependency bump

- app/main/views/frameworks.py
- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/reuse_declaration.html
- app/templates/frameworks/start_declaration.html
- requirements.txt
- tests/app/main/test_frameworks.py
* On the framework overview page:
* "Confirm eligibility, agree to the application terms and provide
supplier information"
* Start your declaration page:
* "You must make the supplier declaration to confirm you’re eligible to
provide services through G-Cloud 9.
You can come back and change your answers before the application
deadline at 5pm BST, 11 April 2017.
After the application deadline, the Crown Commercial Service will review
your answers and let you know if your application has been successful."
* Reusing answers page:
* Remove the comma between the month and the year
* Declaration overview page (application close date for G9):
* GMT to BST
* Don't allow the date to break over two lines - top of page and bottom
> 140127375-supplier-declaration-content-tweaks

- app/main/views/frameworks.py
- app/templates/emails/clarification_question.html
- tests/app/main/test_frameworks.py
When we send supplier clarification questions into Zendesk, we currently
show:
* Supplier name
* User name
People will now be able to see this when they are answering the
question.  We need the people answering questions to be independent.
We need to change this to supplier ID so that it is not obvious who
asked the question
Changes:
* Change template to use supplier id
* Test
> 140507667-no-supplier-name-in-zendesk-clarification-question

- app/templates/frameworks/declaration_overview.html
- bower.json
* Fixes a bug with the summary page where optional questions without answers break the table display.
* Pull in latest frameworks 6.3.5
Old:
New:
> [140828441] - Declaration overview fixes

- app/templates/macros/toolkit_forms.html
Fixes this bug: https://www.pivotaltracker.com/story/show/140851855
Some question numbers in supplier declaration were not being displayed following the recent change to use kwargs in the question macros.  This explicitly passes question number to all question types so will fix the issue.
> BUGFIX: Pass question numbers through to all question types

- app/assets/scss/_supplier-declaration.scss
Everyone hates hanging bullets, so I removed them. Adds a secondary bullet style to make nested lists clearer.
Looks like this:
> removes hanging bullets and adds secondary bullet style

- app/templates/frameworks/declaration_overview.html
- tests/app/main/test_frameworks.py
For each section in the supplier declaration, the first question's edit link should load without any anchors. This will ensure that the top of the page is visible, showing any section description/guidance/preamble for users who click the question-level edit rather than the section-level edit.
> [140837783] - First question, no anchor

- app/main/forms/frameworks.py
- tests/app/main/test_frameworks.py
* Catch correct false value in reuse form
* As per
http://stackoverflow.com/questions/38088806/wtforms-booleanfield-treats-json-false-value-as-true
> BUGFIX-false-values-in-form

- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- app/templates/partials/service_warning.html
- tests/app/main/test_frameworks.py
Story https://www.pivotaltracker.com/story/show/139553967
Previously this code was duplicated between the submission and submission lot pages
and linked to the first question page of the declaration (the old way of doing things).
instead we now point at the declaration overview or the "start declaration" page
depending on the status of the declaration. also improve testing coverage of this
banner's presence/absence.
> [#139553967]service submission pages: merge generation of "You need to make the supplier declaration" banner, retarget

- tests/app/main/test_frameworks.py
@samuelhwilliams mentioned the paratrization was a little hard to decode. Hence added comments. Better, @samuelhwilliams ?
> TestDeclarationOverview: slightly deobfuscate by adding comments

- app/templates/frameworks/edit_declaration_section.html
The fragment identifier only comes into play when there is a validation
error to display, in which case the first error may be at the top
of the page, and the fragment id should be ignored.
See https://www.pivotaltracker.com/story/show/140504509
> Ensure posted form does not have URI fragment identifier

- app/main/views/frameworks.py
- requirements.txt
* This will allow the TemplateField options.description to be rendered properly by the content loader; ContentLoader.get_question() otherwise just returns a dictionary that won't render TemplateFields.
* Bump content-loader dependency.
> New content-loader to use TemplateField subfields

- app/assets/scss/application.scss
- app/templates/macros/toolkit_forms.html
- bower.json
- requirements.txt
This pull request:
- pulls in the latest `frontend-toolkit` with the checkbox_tree pattern
- pulls in the latest `frameworks` with the new service categories
- pulls in the latest `content-loader` which knows how to process checkbox_tree data
- adds a wrapper macro for a `checkbox_tree` question
- brings in the ability to chain show/hide questions
> Add checkbox_tree component to supplier app

- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
This should be taken from the framework instead as it may be a DOS2 opportunity for example.
> Remove hardcoded framework name

- app/main/views/services.py
- tests/app/main/test_services.py
Story https://www.pivotaltracker.com/story/show/141001837
The question.name doesn't get displayed on this page so it makes little sense
> [#141001837]edit service submission: refer to questions by question, not question.name, in validation error masthead

- requirements.txt
Flask requires Jinja but we found a bug with differing versions of Jinja on our different environments. We require all environments to run the same version and so therefore pin this dependancy.
> Require Jinja pinned dependancy

- app/assets/javascripts/_details.polyfill.js
- app/assets/javascripts/_stick-at-top-when-scrolling.js
- app/assets/javascripts/application.js
- app/assets/javascripts/category-picker.js
- app/assets/scss/application.scss
- bower.json
The javascript that runs overtop of the category-picker currently makes the assumption that there is only one category-picker component on a page, so it doesn't really work on [the "examples" page of the frontend toolkit](http://alphagov.github.io/digitalmarketplace-frontend-toolkit/forms/checkbox-tree.html) where there are multiple of them.
That being so, I've kept it in the supplier app for the time being until it can be further generalised.
It's also worth pointing out that we don't have a way of including javascript on a per-question basis in the app, so I've just added all the category-picker-specific stuff to the general `application.js` file.  It won't cause any problems or anything, it's just something to be aware of.
This pull request:
- adds a polyfill so that the `<details>` …
> Add javascript stuff for category-picker

- app/main/views/frameworks.py
- app/templates/emails/clarification_question.html
- tests/app/main/test_frameworks.py
* Remove user name from clarification email
* Update tests
> 140507667-no-supplier-username-in-zendesk-clarification-question

- requirements.txt
* As above. Pull in dm-content-loader 3.5.1, which will drop smart quotes from generated slugs.
#666
> Pull in new content-loader for simplified slugs

- app/assets/javascripts/category-picker.js
Super tiny change to use full words rather than their shortened versions as variable names.
'evt' -> 'event'
'idx' -> 'index'
This was something that @carolinegreen mentioned earlier but I forgot to make the change.
> Use full words for variables in category-picker.js file

- requirements.txt
niceToHaveRequirements page was 500'ing due to a bug with the content loader when validating questions that had not been answered. This should fix that. For further context please see the related PR for the content loader - https://github.com/alphagov/digitalmarketplace-content-loader/pull/33
> Bump content loader to 3.5.2 to fix niceToHaveRequirements validation

- app/templates/frameworks/declaration_overview.html
- tests/app/main/test_frameworks.py
We now have shorter questions in the supplier declaration, so we should reclaim the unused space and give it to the answers on the dashboard.
https://trello.com/c/qoqrHUaq/290-make-declaration-summary-page-summary-table-first-column-1-third-width
> Change supplier declaration template column widths

- app/templates/briefs/view_response_result.html
As per ticket:
> Nicole has spotted an error in the copy on the 'what happens next' page.
We say that suppliers will provide feedback, when actually all they'll
do at shortlisting is tell a supplier they were not successful.
> It currently says:
'If you’re not successful, the buyer will give you feedback on the
evidence you provided.'
> #Could we please replace with:
'The buyer will tell you if you're not successful.'
https://www.pivotaltracker.com/story/show/139477629
> 139477629-Shortlisting-content-error

- app/assets/scss/_framework-application.scss
- app/main/__init__.py
- app/main/views/frameworks.py
- app/templates/frameworks/_framework_actions.html
- bower.json
- tests/app/main/test_frameworks.py
Ticket: https://trello.com/c/RhoLFz3M/322-clarification-around-what-we-do-with-submitted-service-data
This PR pulls in an updated frameworks repo which contains content to be displayed on the frameworks dashboard explicitly clarifying what we do with any data provided about services submitted to a framework. This is currently available in supplier guides but is not present anywhere on DM pages themselves.
It also adds bullet styling for unordered lists within browse-list-items on the framework dashboard only.
Depends on https://github.com/alphagov/digitalmarketplace-frameworks/pull/408
> Clarification around what we do with submitted service data

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
For this bug fix: https://www.pivotaltracker.com/story/show/141950783
Depends on this API change going in first:
The snake_case keys are on their way out - use the new camelCase versions instead.
Also a sneaky second commit to add a 400 response code when there's a validation error on the "reuse your old declaration" form.
> Update to use camelCase keys from framework JSON

- .flake8
- Makefile
- requirements_for_test.txt
- setup.cfg
* New .flake8 file
* Exclude virtualenvs, cache, bower and node stuff
* Ignore blank line required before class docstring (pretty standard ignore)
* Ignore unused imports in __init__ files
* Ignore import not at top of file in _some_ __init__ files
* Ignore complexity in views
* Makefile
* New test_flake8 command to run flake8
* Remove test_pep8 command
* replace pep8 command with flake8 in test run command
* requirements_for_test
* Remove pep8
* Add flake8 and flake8-putty
* Alphabetize
* setup.cfg
* Remove unused pep8 and nose config entries
> FLAKE8-do-flake8

- app/assets/scss/application.scss
- bower.json
**Note: if this goes in before [the other frontend toolkit update](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/688), the other one becomes irrelevant and should be closed rather than rebased and merged.**
***
Brings in the latest-latest frontend toolkit to kill the bug where two checkboxes pointing at the same target element might unintentionally hide that target element. ([more explanation here](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/322)).
> Still show target element if any controlling element is still selected.

- app/main/views/services.py
- config.py
- requirements.txt
- tests/app/main/test_services.py
Using a single bucket allows us to use S3 bucket domain as our
assets URL without a running a separate nginx proxy.
The bucket is empty at the moment and might get replaced in the
future when we start managing it with Terraform.
> Update dev config to use a single bucket for all upload types

- README.md
I don't think it's immediately obvious that this is how the applications are split up.  Also add documentation about nginx configuration for supplier frontend.  I realise this is in digital marketplace manual too, but this is in a private repo so I think it's useful to have it here in the readme too.
> Add documentation about login

- app/main/views/frameworks.py
- app/templates/frameworks/_submitted_services.html
- app/templates/frameworks/declaration_overview.html
- tests/app/main/helpers/validation/test_g7_declaration.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Story https://www.pivotaltracker.com/story/show/140222101
In the story it was decided to cope with all `complete` declarations for non-open frameworks and ignore whether a supplier was `onFramework` or not. Suppliers with non-`complete` declarations for a framework will receive a `410` (see code for reasoning).
One consequence of this is that non-open frameworks end up with no introductory text or paragraph on this page.
~~~Works back to G7 though in an ugly way because pre-G9 questions didn't tend to have "short" question text variants to use in the table. (screenshots coming...)~~~ ~~~~doesn't appear to work properly on G7, will need to look at this...~~~~ ok it does seem to work, it was just the mock declaration that was wrong...
~~~One thing still TBD is where/how this page will get …
> [#140222101]declaration overview: enable visibility in non-open framework statuses

- app/main/helpers/services.py
- app/main/views/frameworks.py
- app/templates/frameworks/contract_start.html
- tests/app/main/test_frameworks.py
For this story: https://www.pivotaltracker.com/story/show/144514369
Suppliers prefer the word "Successful" to "Pass", and it matches what we say in the emails to them.
Also, turns out the page was not dealing with DOS-style frameworks properly and showing failed lots as "No application".  This fixes it so that if a lot was submitted but failed it will show "Unsuccessul" rather than "No application".
> Change "Pass" to "Successful" and deal with failed lots

- app/templates/services/_base_service_page.html
- bower.json
Fixes this bug: https://www.pivotaltracker.com/story/show/144683417
Also pulls in the correct G-Cloud 9 framework agreement URLs, so tests passing depend on the following PR being merged (still waiting for the final-FINAL-v3 URL to update that though):
> Bugfix service summary table when not editable

- bower.json
Brings in a bugfix to get the show-hide thing working for IE8 users applying to briefs.
It's been QA'd to the max by me, but it would be good to get someone else to look at it.
More context ->  https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/334
> Bring in bugfix for show-hide questions in IE8

- bower.json
This has the re-updated G-Cloud 9 framework agreement PDF URL.
> Pull in latest content 8.1.2

- bower.json
This has the re-updated G-Cloud 9 framework agreement PDF URL.
Depends on:
> Pull in latest content 8.3.1

- app/main/helpers/briefs.py
- tests/app/main/test_briefs.py
When a user asks a clarification question on a brief, we want to be able to be able to easily find the supplier the user belongs to so that we can notify them of changes to the brief.
We're pretty lax about what goes into audit events, so it seems like a good idea to keep track of the supplier ID in the audit event created when a clarification question is asked about a brief.
> Store `supplierId` in brief clarification question audit event

- app/main/__init__.py
- app/main/views/services.py
- app/templates/services/_base_service_page.html
- app/templates/services/list_services.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
- bower.json
- tests/app/main/test_services.py
Trello: https://trello.com/c/iptxy2Oy/397-allow-dos-suppliers-to-view-their-services
- Page for all 4 DOS lots
- G cloud services should remain exactly the same
- No link to public service page for DOS services
- Should not be able to remove a DOS service
- Removed DOS services should the banner that they have been removed
- DOS services should have no links to edit their information
- User can not guess URLs and edit a DOS service
- Empty summary table rows are not shown (i.e. specialist roles and outcomes capabilities)
- Functional tests PR ready to go - https://github.com/alphagov/digitalmarketplace-functional-tests/pull/296
> Allow suppliers to view their DOS services

- app/templates/services/service.html
- tests/app/main/test_services.py
Bug as spotted by Andrew - https://trello.com/c/iptxy2Oy/397-allow-dos-suppliers-to-view-their-services
If the user 'hacked' the url and added `remove_requested=True` the url of a DOS service they should not see the removal confirmation that you usually would for GCloud services.
We decided to not show the message rather than 404 as it's more forgiving to a user.
Before picture:
After picture:
> Do not show remove service confirmation message for DOS

- app/templates/briefs/_brief_response_data.html
- app/templates/briefs/clarification_question.html
- app/templates/briefs/question_and_answer_session.html
- app/templates/frameworks/submission_lots.html
- requirements.txt
- tests/app/main/test_frameworks.py
We're bringing in a new jinja filter that keeps line breaks (up to a maximum of two) for the large textarea content.
Specifically, it's going into:
- the "view your application page" for brief responses.  (Note there is no corresponding buyer page to see brief responses -- they only get CSVs/ODS files to download.)
| before | after |
|--------|-------|
| ![screen shot 2017-07-04 at 11 00 18](https://user-images.githubusercontent.com/2454380/27825988-5ae3a1d2-60a9-11e7-954e-f23a62371371.png)    | ![screen shot 2017-07-04 at 10 59 18](https://user-images.githubusercontent.com/2454380/27826011-6ecdb084-60a9-11e7-91a3-abd8041498d0.png)   |
**Note**
It's  _not_ going into the service editing summary page (either here or in the admin app) because the way we group the questions in the service …
> Preserve line breaks for seeing your brief responses

- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/briefs/view_response_result.html
- app/templates/suppliers/_frameworks_live.html
- app/templates/suppliers/opportunities_dashboard.html
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
User need
As a supplier, I want to see the opportunities I've applied for, so I can keep track of them
Add page suppliers/framework-slug/opportunities-overview to allow suppliers to view their applications to opportunities.
Add link to this page from supplier dash and from 'application complete' page
Template and view for this page
Tests
Small test refactor in tests/app/main/test_suppliers.py to add mocks to class instead of every method
> Allow suppliers to view their applications

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
Simple fix to change the status code returned when a supplier is ineligible for a brief (from 400 to 403).
Ticket: https://trello.com/c/gCEsNuQ3/401-return-403-rather-than-400-http-code-if-supplier-not-eligible-for-brief
> Return 403 status if supplier ineligible for brief

- app/main/views/frameworks.py
Recent utils version bump brought in updated s3 functions.  `get_key` used to return None for a None input, but now will raise an error instead, so the caller needs to check that the param is not None before calling.
> Check for empty path before calling get_key

- .flake8
- .gitignore
- default.nix
- local.example.nix
- requirements-dev.txt
This is something that's going to need extensively more of a writeup than this, but...
_Note: this is meant to be a strictly optional convenience for those of us who want to use it_
This `default.nix` allows users with a working nix install to simply perform a
```
$ nix-shell --pure .
```
in the repository root and get a fully working development environment with all dependencies.
(you may have to blow away your `node_modules/` and `bower_components/` directories before running `make run_all` to get them re-fetched again as they will have been constructed using a different node version)
You can choose the python version by editing the line
```
pythonPackages = pkgs.python36Packages;
```
to, e.g., `pkgs.python27Packages`. I've set up `nix-shell` to use a separate virtualenv for each python …
> Add default.nix

- app/main/views/services.py
- app/templates/services/edit_section.html
- app/templates/services/list_services.html
- app/templates/services/service.html
- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Story https://trello.com/c/I0beYt9w/40-1-allow-services-page-to-filter-by-framework
In short, a supplier's service listing page has been segregated to provide listings by framework. Though for the hierarchy to continue making _any_ sense, URLs of various pages living beneath `/suppliers/services/<service_id>` had to be moved to beneath `/suppliers/frameworks/<framework_slug>/services/<service_id>`.
The supplier dashboard has had its large "View services" link moved to the per-framework links: 
The actual listing page is now at `/suppliers/frameworks/<framework_slug>/services` and has had its heading changed appropriately:
Service detail pages have been moved to `/suppliers/frameworks/<framework_slug>/services/<service_id>` and its breadcrumb pointing back to the listing page has been …
> Service listing page: segregate by framework, adapt URL scheme

- app/assets/javascripts/category-picker.js
- bower.json
- gulpfile.js
- package.json
Bring in Digital Marketplace frontend toolkit with the new buttons that work without javascript.  This was a breaking change, so GOV.UK Elements is now a dependency and there is new build process reflecting that.
Additionally the category picker was slightly altered to handle the new markup.
Relies on: https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/353
> Bring in frontend toolkit updates

- app/main/forms/suppliers.py
- app/templates/suppliers/details.html
- app/templates/suppliers/edit_supplier.html
- tests/app/main/test_suppliers.py
For this Trello card: https://trello.com/c/8y0ApVRh/63-update-the-contact-address-front-end-1
* Removes `address2` and `country` fields from the displayed address and from the edit supplier details page 
* Updates wording to be "Registered office address"
> Supplier address rejig

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/companies_house_number.html
- app/templates/suppliers/dashboard.html
- app/templates/suppliers/details.html
- app/templates/suppliers/edit_supplier.html
- tests/app/main/test_suppliers.py
For this story in Trello: https://trello.com/c/GFp7ncpN/62-update-the-supplier-page-to-expose-the-migrated-declaration-information-2
**THERE IS AN ACCOMPANYING LEGACY FUNCTIONAL TESTS PR TO MERGE AT THE SAME TIME**: https://github.com/alphagov/digitalmarketplace-functional-tests/pull/336
This adds the new "Registration information" section to the supplier details page, and also updates the edit supplier information form to only show the fields that are now displayed.  Wording is updated to match the prototype, and the fields on the edit page match the names of the fields on the display page (which previously they didn't 😞 ).
Updated page looks like this:
And like this for a supplier with more registration info:
> Display new supplier fields

- app/main/forms/suppliers.py
- tests/app/main/test_suppliers.py
We recently (in this commit: https://github.com/alphagov/digitalmarketplace-api/pull/626/commits/fd76ee0bb6f0edacf29ed239d78424650b05e00e) introduced a validator on the API to restrict Companies House numbers to valid formats, but didn't update validation in the frontend flow here at the same time.
Because nothing gets posted to the API until the final step of this flow it is currently possible to submit an invalid CH number here and then have the API post request fail when submitting the final step.
It's not ideal to have the same regex in two places, but this is a current production bug and this will fix it for now.
> Bugfix: not validating Companies House strictly enough on frontend

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/flashmessages/join_open_framework_notification_mailing_list_success.html
- app/templates/suppliers/join_open_framework_notification_mailing_list.html
- config.py
- requirements-app.txt
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
Story https://trello.com/c/V8bUSjq8/77-implement-an-email-sign-up-capability-for-suppliers-2
This story adds a `/supplier/mailing-list` view which will allow a (non-)user to sign up to a mailchimp mailing list:
Taking its its mailchimp configuration from the config variables `DM_MAILCHIMP_USERNAME`, `DM_MAILCHIMP_API_KEY` and `DM_MAILCHIMP_OPEN_FRAMEWORK_NOTIFICATION_MAILING_LIST_ID`. If this fails for some reason the user is brought back to the same page with an error flash message:
On success, they are redirected to the DM root page complete with success flash message using georgian flashing:
As part of this I consolidated the app's email form field validation:
> Implement an email sign up capability for suppliers

- app/templates/suppliers/join_open_framework_notification_mailing_list.html
Removal of fullstop on failure message and addition of "Your email address" field label.
Related discussion on trello: https://trello.com/c/V8bUSjq8/77-implement-an-email-sign-up-capability-for-suppliers-2
> join_open_framework_notification_mailing_list: fix minor display issues

- app/templates/macros/toolkit_forms.html
- tests/app/main/test_services.py
Story https://trello.com/c/W3d7VMrO/72-supplier-app-use-frontend-toolkit-macros-3
Turns out jinja doesn't appear to re-export imported macros after all, but there wasn't a test covering these question types. so add a slightly ugly passthrough hack for the macros and add a couple of (very basic) tests for editing of G9 services.
> form macros: fix for boolean_list and multiquestion macros, add tests

- app/templates/suppliers/company_summary.html
Down to some sloppy copy-and-pasting from the frontend toolkit back in 2015 (check the Blame if you're interested) these tables never got a caption that matched the heading (useful for accessibility).
Functional tests just changed to look for caption rather than heading (to allow finding tables without headings, which we sometimes have), so they could no longer find the tables here.
I didn't notice the error because I didn't have a framework that could be applied to, so the test currently failing on Preview skipped when I ran them locally.
> Add appropriate captions to tables on supplier sign-up overview page

- config.py
Optimistically setting the "Live" date for this coming Monday.
Ticket here: https://trello.com/c/j3iEdpmn/77-allow-suppliers-edit-their-g-cloud-service-listing
API PR forthcoming to acknowledge audit events up until then too.
> Finally turn on supplier editing G-Cloud services in prod

- app/main/views/services.py
- app/templates/services/service.html
- bower.json
- setup.cfg
- tests/app/main/test_services.py
Tests will fail until this is merged:
For this ticket: https://trello.com/c/tZwe5CNc/138-suppliers-can-upload-documents-when-editing-g-cloud-services
This adds a new Documents section to the "edit service" view for G-Cloud 9 services, with a row for service definition document that is visible even if there is no document uploaded (see screenshot below).  Rows will continue to not be shown for empty questions that are not editable (as happens on the DOS version of this page).  Most of the new tests here mirror the tests we have for file uploads during the submissions process
> Suppliers can upload service definition documents

- requirements-app.txt
- requirements-dev.txt
- requirements.txt
Addresses a vulnerability in the Python `requests` library.
While this app does call the `update_user` method, the v13.0.0 breaking change should not affect this app as the client call uses keyword args rather than positional args.
Also fixes a pytest deprecation warning.
> Upgrade API client to v13.1.0

- app/assets/scss/application.scss
Move our DM CSS reset to the top of our `application.css` file so that we clear styling on all HTML core elements, giving us a definitively clean base upon which to buildn.
> Reset styles before DM CSS

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- tests/app/main/test_services.py
Addresses this bug: https://trello.com/c/6mO70EhR/186-editing-of-services-from-expired-frameworks
We currently restrict the list of services shown to suppliers to live frameworks, but if the URL is manipulated to have the ID of a service on an expired framework it could still be edited.  This changes things to prevent that from happening.
> Services can only be edited while framework is live

- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
Story https://trello.com/c/g93M7T3f/104-503-responses-for-bad-email-addresses-should-be-400s
Those cases being the ones where we think the failure might somehow be due to the user's email address.
Debatable whether we want to apply this or remain alert to these failures. Note this still doesn't completely quieten these events - the `DMMailChimpClient` from `-utils` itself emits a log message, which we may want to downgrade to a warning in this, less severe, case. But that's a separate issue.
> join_open_framework_notification_mailing_list: return 400 status code in some mailchimp call failure cases

- bower.json
This will allow us to open G10 and DOS3 on Preview.
The major version bump (9.x to 10.x) is to do with search mappings that are not used by this app, so it's OK to pull in without any further code changes.
> Pull in latest frameworks version

- app/main/__init__.py
We 100% need a better way to do this, but I've lost an afternoon trying to get it to dynamically load based on what frameworks are in the database (as we do in eg the admin app).  
Dynamic loading is complicated (or at least made very ugly and hard-codey) by the fact that G6 doesn't have `edit_submission` or `declaration`, and G9 is the only framework with `advice` messages, and so we end up specifying what to load per-framework or having a `try... except` around every single `load`.
I'm going to add it as a tech-debt ticket to fix this and do something consistent across all apps (I'm pretty sure the ticket already exists TBH), but in the interests of un-breaking preview I think we should go with this for the time being.
> Load the content for G10 and DOS3

- Dockerfile
- Makefile
- yarn.lock
We updated the frameworks repo but didn't re-install locally so the `yarn.lock` file got out-of-date.
Also start using frontend.base Docker v3.0.1 which changes the yarn command used to install dependencies.
> Update lockfile for new frameworks version

- tests/app/main/test_frameworks.py
Tidy up 2 tests:
* Remove extraneous, unhelpful assertion and use `self.client`
* Mock session instead of forcing a new context
> Tweak framework tests in supplier frontend

- tests/app/main/test_frameworks.py
These calls are, and always have been as far as I can tell, unnecessary.
I guess they are some sort of copy-paste artefact.
_The only changes in this PR are removing the `with self.app.test_client()` calls and sorting out the indenting_
This makes the test more readable and easier to maintain.
> Remove unnecessary `with self.app.test_client()` calls in `test_frameworks.py`

- app/main/helpers/frameworks.py
- app/templates/macros/toolkit_forms.html
- tests/app/main/test_services.py
https://trello.com/c/iaRQlj6y/87-toolkit-forms-macros-are-different-in-all-of-the-apps
I originally was hoping to remove the custom `toolkit_forms` macros file from this repo so that instead it could just use the the macros found in the FE toolkit so we had consistency between the apps. However upon on review, we have functionality in this app that relies on these custom macros (question references being parsed for declaration questions and nice date values on file uploads for service editing).
There were however a few small things that I could tidy up
- removed two lines of code from the toolkit_forms macros that were having no effects
- Improved documentation
- Added test coverage
Current behaviour for upload time:
Behaviour that would have been changed if we used the toolkit macros …
> Improve documentation around custom form macros found in this app

- app/main/__init__.py
- app/main/errors.py
- app/main/forms/auth_forms.py
- app/main/forms/frameworks.py
- app/main/forms/suppliers.py
- app/main/helpers/__init__.py
- app/main/helpers/frameworks.py
- app/main/helpers/services.py
- app/main/helpers/validation.py
- app/main/views/frameworks.py
- app/main/views/login.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/main/views/users.py
- requirements-app.txt
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_login.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
- tests/app/test_application.py
This fixes the S3 files-not-showing-if-no-timestamp bug: 
https://trello.com/c/qBiGn3bP/9-legal-documents-files-not-appearing-on-framework-application-dashboard
The (unintentional) updating of Werkzeuz caused a test to fail (and, it turns out, the app to break) - see my commit message on new commit, copied here for ease of reference:
```
Running `make freeze-requirements` has, as well as adding utils and ODFPy
updates, pulled in a newer version of Werkzeug (it's gone from 0.12.2 to
0.14.1).  This dependency comes from the Flask libraries specification of
`required: >=0.7`, but pip pulls in the latest available at the time it
runs.
The new version has new behaviour for file uploads. Previously, if no file
was uploaded Werkzeug would pass an empty FileStorage object to the route
under the …
```
> Pull in latest utils

- app/main/views/suppliers.py
- app/templates/suppliers/company_summary.html
- tests/app/main/test_suppliers.py
This has been done as this number is optional and now we will
let suppliers add it on the 'company details' page.
Related pull request for Functional Tests: https://github.com/alphagov/digitalmarketplace-functional-tests/pull/463
Trello ticket:
https://trello.com/c/coCrPhFZ/25-remove-companies-house-page-from-sign-up-journey
> Remove Company House Number page from supplier sign up flow

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
See this trello ticket: https://trello.com/c/G4fvE87X
Files that had been uploaded to the digitalmarketplace-dev-uploads
bucket didn't have permissions that meant they were accessible from the
console.
The issue is that both buckets and objects have their own different
access controls lists.
The digitalmarketplace-dev-uploads bucket is part of the dev account.
When running the apps locally boto3 will use your default credentials as
specified in `~/.aws/credentials`. If set up correctly, these will be your
credentials for the main account (this is the account that your user is
set up on). This means that any time you upload a file, it's coming from
the main account. In S3, when you look at the permissions for an object,
the name of the object owner you see (`suppliers` or `development-aws` …
> Change object permissions to 'bucket-owner-full-control'

- app/templates/suppliers/create_new_supplier.html
- app/templates/suppliers/duns_number.html
Update the content when asking suppliers for their DUNS number. Also add breadcrumbs to the DUNS number page and the 'create new supplier' page, which doesn't have the breadcrumb it ought to (according to the prototype). We've had to change from `single-question-page` to `dmspeak` on the top-level div for two reasons.
1) `single-question-page` hides the "DUNS number" header above the hint text.
2) `dmspeak` adds some padding around the paragraphs, which are otherwise too tightly packed.
https://trello.com/c/ae5UzOAn/39-sign-up-flow-update-copy-on-duns-number-page
> Update content for DUNS number

- app/assets/scss/_variables.scss
- app/assets/scss/application.scss
- app/main/forms/frameworks.py
- app/templates/emails/g-cloud-9_variation_1_agreed.html
- app/templates/frameworks/contract_variation.html
- tests/app/main/test_frameworks.py
As a supplier, I can review the proposed contract variation for the GCloud9 framework agreement and call-off contract, so that I understand what it includes and decide whether to accept it.
Ticket: https://trello.com/c/ipSUk2Yo/104-add-final-copy-for-contract-variation-for-gcloud-9-and-update-feature-to-reflect-the-correct-dates
> G Cloud 9 Contract variation updates

- app/__init__.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Update utils to use eea/odfpy rather than our interim alphagov/odfpy
fork, which we created to allow us to patch a bug. Now that the bug has
been accepted into the main library as of release 1.3.6
(https://github.com/eea/odfpy/pull/72) we no longer need to support
own our fork.
Also adds a comment when registering the external blueprint from 
dm-utils to ensure it is registered last.
> Revert back to eea/odfpy

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/become_a_supplier.html
- app/templates/suppliers/companies_house_number.html
- app/templates/suppliers/company_contact_details.html
- app/templates/suppliers/company_name.html
- app/templates/suppliers/create_new_supplier.html
- app/templates/suppliers/create_your_account.html
- app/templates/suppliers/create_your_account_complete.html
- app/templates/suppliers/duns_number.html
- app/templates/suppliers/edit_supplier_organisation_size.html
- tests/app/main/test_suppliers.py
Adds a new page to the supplier account that allows a supplier to edit their organisation size. This page hasn't been plumbed up to anything yet - that will be done in a later ticket.
There's no flash message confirming the action the user has taken included as part of this ticket. It feels like it might be good to add this as part of this ticket but I'll need the content (@constancecerf?)
https://trello.com/c/eB9u3xe7/40-new-editable-page-build-organisation-size-page
> Add page to edit organisation size

- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
When suppliers are serialized by the api any `None` value keys are
dropped before being returned in the response.
The `registrationCountry` field in the suppliers table is a nullable
field. Whilst in practice in production we don't have any null values in
this field (it's either an empty string or 'gb' at the time of writing),
we should cover this case just in case.
This issue was picked up by the functional tests on preview. The
suppliers generated by the functional tests have null values for
`registrationCountry`. This may also need looking at.
> Handle suppliers with no `registrationCountry` key

- app/templates/suppliers/companies_house_number.html
- app/templates/suppliers/company_name.html
- app/templates/suppliers/duns_number.html
- app/templates/suppliers/edit_supplier_organisation_size.html
- tests/app/helpers.py
- tests/app/main/test_suppliers.py
When https://trello.com/c/eB9u3xe7/40 was getting QA'd, it was highlighted that we hadn't added a validation masthead at the top of the page to highlight that something was wrong. This has now been added and retrofitted to some other existing single-question-pages that were missing the same, so that we're more consistent.
Checking with @laurenceberry whether the masthead should be inside the column-two-thirds or outside.
https://trello.com/c/eB9u3xe7/40
> Add validation mastheads

- app/templates/suppliers/duns_number.html
Remove the `single-page-question` div around duns-number so that the subheading is not hidden by our pattern styles
https://trello.com/c/eB9u3xe7/40-new-editable-page-build-organisation-size-page
> Duns number subheading

- app/main/views/frameworks.py
Because we now have 3 different methods of sending emails we should update utils to ensure `send_email` is imported from the client specific sub-directory of `emails` in utils
> Update import to import send_email from dm_mandrill

- app/main/helpers/suppliers.py
- app/main/views/frameworks.py
- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/dashboard.html
- requirements-app.txt
- requirements.txt
- tests/app/main/helpers/test_suppliers.py
- tests/app/main/test_frameworks.py
Adds a new section to a supplier's framework application tasklist. They
must now check+complete their company details are correct and are
all present. This includes some helper logic to parse the API supplier
data and determine whether or not it's "complete".
Pulls in a new apiclient which contains a supplier fixture.
Tests won't pass until that's been merged.
https://github.com/alphagov/digitalmarketplace-apiclient/pull/124
https://trello.com/c/8Ahl8YNc/43-supplier-account-add-supplier-details-to-tasklist-page
> Add supplier details to tasklist page

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/already_completed.html
- app/templates/suppliers/edit_registered_name.html
- tests/app/helpers.py
- tests/app/main/test_suppliers.py
For this ticket: https://trello.com/c/Q5N2RVEj/47-new-one-time-page-build-registered-company-name-page
Adds a new page where suppliers can add their registered name.
> Add registered name page

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/details.html
- app/templates/suppliers/edit_supplier.html
- app/templates/suppliers/edit_what_buyers_will_see.html
- tests/app/main/test_suppliers.py
Trello ticket: https://trello.com/c/VF5yc1pd/50-supplier-account-1-update-supplier-details-page
- rename headers
- rename 'Edit' to 'Change' link
- add 'Optional' next to summary field
- Move address field to second section of the page and add registration country to it
- remove 'Registration Country' as a separate question
- write a test for address field
- adjust existing tests
Also 2nd Trello ticket: https://trello.com/c/A3ovgHlk/51-remove-address-from-edit-supplier-details-page
- Delete address details from "Edit supplier" page
- Change header and breadcrumb for 'What buyers will see' page
- Move validation errors banner above the page header
-  Rename route/page from 'edit_supplier' to 'edit_what_buyers_will_see' 
ADDITIONALLY:
- unite GET and POST routes for edit_supplier contact …
> Rearrange Supplier Details page elements and change headers

- app/templates/suppliers/details.html
- app/templates/suppliers/edit_what_buyers_will_see.html
Also make "Optional" only appear when the summary is empty.
> Fix links on "What buyers will see" validation banner

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/edit_supplier_trading_status.html
- tests/app/main/test_suppliers.py
Adds a page for suppliers to edit their trading status.
https://trello.com/c/Wvvtb1yW/52-new-editable-page-trading-status
> Add edit trading status page

- app/main/helpers/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/registered_address.html
- tests/app/main/helpers/test_suppliers.py
- tests/app/main/test_suppliers.py
Some minor tweaks to the new registered address page, to bring it inline with how we're doing things on other pages. Mostly spurred on my working out why validation masthead links were broken in some cases.
There was an issue with the usual links not working so we used
JavaScript instead. I've worked out what the problem was.
The links are actually powered by some other JavaScript from the
frontend toolkit. They look for an element with an ID that matches the
field name, and then target the first input or text area _within_ that.
So if the input itself has the id, or the id isn't used, the link won't
work.
As we're validating on the frontend, all errors should be due to
network issues or the like. So any APIErrors can bubble up as 500's.
By processing both forms errors in the view and …
> Update registered address page

- app/templates/suppliers/create_new_supplier.html
Update the copy on the supplier create account start page to clarify what users will need before starting
https://trello.com/c/GgKXHr4V/38-sign-up-flow-update-copy-on-start-page
> Update start page copy

- app/main/views/frameworks.py
- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- app/templates/partials/service_warning.html
- package.json
- tests/app/main/test_frameworks.py
- yarn.lock
Update copy in the notification banner on service/lots page of supplier application to framework to include links to the company details page and the declaration page
~https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/412~
https://trello.com/c/JVr9gFEC/56-incomplete-application-banner
> Update content in notification banner

- app/templates/frameworks/_framework_actions.html
Consistently colour the tasklist notices under each heading based on
whether all parts of the application have been completed.
Caught in QA that the bit under declaration wasn't going green.
https://trello.com/c/8Ahl8YNc/43-supplier-account-add-supplier-details-to-tasklist-page
> Fix colour on tasklist notices

- app/templates/suppliers/create_new_supplier.html
Add a non-breaking space between Companies House to ensure a single word is not left dangling on its own line.
https://trello.com/c/GgKXHr4V/38-sign-up-flow-update-copy-on-start-page
> Non-breaking space in Companies House

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/edit_vat_number.html
- tests/app/main/test_suppliers.py
- yarn.lock
Trello ticket here: https://trello.com/c/NFRFA2K5
The tests won't go green until the [related PR](https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/409) on the frontend-toolkit goes in. It's been approved, it's just waiting for Laurence to give it a thumbs up.
~~The validation messages may also be updated; Constance is reviewing them so they may change.~~
Constance has reviewed the validation messages.
We need only validate the VAT number entered if the user has stated that
they are registered. We can't use the `Optional` validator for this in
case the user has started typing something in the input field and then
changed their mind.
The regex used for the VAT number covers 9 and 12 digit VAT codes, both
with the optional 'GB' prefix. It also supports the lesser used but …
> Add one time vat page

- app/templates/frameworks/contract_review.html
- app/templates/frameworks/declaration_overview.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
- app/templates/suppliers/company_summary.html
Trello: https://trello.com/c/sYJYKnK9/58-how-summary-tables-handle-their-links-means-pages-can-contain-multiple-links-with-duplicate-text
Summary tables with multiple 'Edit' or 'Change' links are unhelpful for screenreader users who may not know which section the link refers to. 
v28.1.0 of the FE toolkit adds in a 'hidden_text' param to the `summary.top_link` macro (similar to the existing `summary.edit_link`) so we can make the link text less ambiguous for screen reader users. 
For example:
```
<a href="...">Edit</a>
```
becomes
```
<a href="...">Edit<span class="visually-hidden"> supplier details</span></a>
```
NB: I've guessed at the content for some of the links where there isn't an existing `section.name` to use. These will need a content designer to review (@constancecerf …
> Accessibility fixes for summary table Edit links

- app/main/helpers/suppliers.py
- tests/app/main/test_suppliers.py
Registration date is a field we are no longer interested in, so we should remove all references from it as we will be dropping it from the API shortly.
https://trello.com/c/M2jPJ3kZ/58-purge-registration-date-from-logic-and-data
> Remove registration date

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
Final piece of QA follow-up for this ticket: https://trello.com/c/nToxBmYI/48-new-one-time-page-build-registered-with-companies-house-page
The heading on the "contact support" page should match the text in the bullet point, which is just "registration number".
> Remove "company" from "company registration number"

- app/templates/_base_page.html
- requirements-app.txt
- requirements-dev.txt
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/PZyZdMtG/337-custom-dimension-to-capture-size-of-supplier
- Adds in extra context for the custom dimensions template to set the organisation size for a supplier.
- Updates test helpers to include the supplier organisation size in the test user JSON.
> Set GA custom dimension for supplier organisation size

- app/main/forms/suppliers.py
- tests/app/main/test_suppliers.py
To fix this bug: https://trello.com/c/c5wWLrkJ
During supplier creation a phone number is required. It should also be
when editing supplier contact details. Have also added length validation
to remain consistent with the sign up flow.
> Enforce validation on supplier edit contact deatails

- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/suppliers/details.html
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
Trello ticket: https://trello.com/c/l2xh4cR3/63-confirm-supplier-details-4-return-to-your-framework-application-link
The link and hint text:
>  Show a back to framework application link if framework application info in session

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
Allow suppliers to edit some company details (vat number, registration
number, registration name) until they specifically confirm they are all
correct. In the theoretically impossible situation where a supplier has
confirmed their details but one/more of these pieces of information are
missing, they will still be able to provide it as a one-off.
* https://github.com/alphagov/digitalmarketplace-api/pull/762
https://trello.com/c/NaNjMOHc/61-confirm-supplier-details-2-frontend-logic-changes
> Allow editing until confirmation

- app/main/views/suppliers.py
https://trello.com/c/qLOqQYy0/226-unable-to-format-log-message-log-messages-not-particularly-useful
Was referring to a parameter `errors` but providing a parameter `rnumber_errors` instead, causing a confusing error when this is issued.
> edit_supplier_registration_number view: fix warning log message

- app/main/forms/auth_forms.py
- app/main/forms/suppliers.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_suppliers.py
For this tech debt ticket: https://trello.com/c/StDVGuoI
Also, this PR on utils: https://github.com/alphagov/digitalmarketplace-utils/pull/372
Contact name wasn't being validated for length.
The email field can use the EmailValidator we have in utils, with an
updated message.
We no longer use the LoginForm or the ChangePasswordForm. This
functionality has moved to the user app.
Also, the EmailAddressFrom can be refactored to use the common
`EmailField` field from utils. This comes with a free regex validator.
> Fix supplier forms validation

- app/status/views.py
- requirements-app.txt
- requirements.txt
The status endpoint for all of the apps is highly redundant across
repositories so I've moved it to dm-utils. We now only need to call this
method from the view stub in each app and pass in a couple of resources
(mainly the current_app and any api clients) to get a consistent status
JSON blob back.
https://trello.com/c/BBvu6eUk/383-ensure-healthcheck-endpoint-fails-if-low-disk-space
> Use centralised status method

- app/main/helpers/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/details.html
- requirements-app.txt
- requirements.txt
- tests/app/main/helpers/test_suppliers.py
- tests/app/main/test_suppliers.py
For this ticket: https://trello.com/c/gjl4LXzu/60-confirm-supplier-details-3-the-green-button
Adds in button to confirm supplier details.  The button is shown once all details have been provided, and disappears after it's been clicked once to confirm the details are correct.
It looks like this:
I've also reworked the logic of deciding if supplier details are complete - previously we had it contingent on whether country is UK or not whether you need Companies House number or some other registration number, but actually UK suppliers could have an "other" registration number.  So we just require one or the other number, not dependent on the country.
> Confirm supplier details big green button

- app/templates/suppliers/details.html
Visual regression tests identified some extra spacing introduced here at the bottom of the page when there was no button or wording to show.
Including the new grid-rows only when there's something to put in them should fix the issue.
> Only add grid rows if they have content

- app/templates/suppliers/details.html
Visual regression tests identified some extra spacing introduced here at the bottom of the page when there was no button or wording to show.
Including the padding on the first grid-row only when there's something to put in them should fix the issue.
> Only add padding to top grid row if there are rows below

- app/templates/suppliers/_frameworks_open.html
- app/templates/suppliers/_frameworks_pending.html
- app/templates/suppliers/dashboard.html
- package.json
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
- yarn.lock
Trello ticket: https://trello.com/c/e1Gk2eTF/12-fix-styling-for-framework-banners-on-account
Everything done as per the screenshot I think except the headers are `h3`, not `h2`,  as changing them would add a layer of complexity (The header element lives in the macro and is used for many different temporary messages across digital marketplace).
____
____
____
> Change how open framework banner is displayed on dashboard

- app/templates/suppliers/_frameworks_open.html
As per comment from QA on the Trello ticket: https://trello.com/c/e1Gk2eTF/12-fix-styling-for-framework-banners-on-account
> Add deadline to start framework application banner

- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
This changed recently to /suppliers/create/start - we should have redirected the old URL when we did that.
Also adds some additional tests for the sign-up flow pages that should have been there but weren't.
> Add permanent redirect for /suppliers/create route

- app/main/views/frameworks.py
- app/main/views/login.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/main/views/users.py
- app/templates/_base_page.html
- app/templates/auth/submit_email_address.html
- app/templates/flashmessages/join_open_framework_notification_mailing_list_success.html
- app/templates/frameworks/contract_start.html
- app/templates/frameworks/contract_variation.html
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- app/templates/frameworks/updates.html
- app/templates/services/_base_service_page.html
- app/templates/services/list_services.html
- app/templates/suppliers/dashboard.html
- app/templates/suppliers/join_open_framework_notification_mailing_list.html
- app/templates/users/list_users.html
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Trello https://trello.com/c/H7upcsyQ/303-flash-messages-suppliers-app
Depends on https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/425/
I *think* I properly converted all of the messages to use the equivalent content that would have been triggered using the previous symbolic messages, though of course it's sometimes hard to know when it comes to inter-app messages.
Added what I think is my preferred way of testing flash messages - `get_flash_messages()` - simple and allows a lot of flexibility for predicates. I like it for similar reasons I like using `Mock`'s `call_args_list`.
> flash messages: port to centralized implementation from frontend toolkit

- config.py
We want to load test our infrastructure before G-10 applications open.
We're planning to use Gatling to run some scenarios with high user
levels. If we have csrf protection enabled this will prevent the tests
from working.
We _could_ set the tests up to try and parse the csrf token from the body 
of the responses received by Gatling and then include it in the following
POST request. This feels fragile though.
> Disable csrf protection on staging for load tests

- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- app/templates/suppliers/dashboard.html
- package.json
- tests/app/helpers.py
- tests/app/main/test_notifications.py
- yarn.lock
PRE REQUISITE:  https://github.com/alphagov/digitalmarketplace-user-frontend/pull/43
Add the user research banner to the account page using the existing GOV.uk pattern. Allow for links to 'sign up to mailing list' page
As a user I should be presented with the banner to sign up to the user research mailing list when I log in if: I have not already closed it and I have not already signed up for this.
This is the first point of contact for getting users to sign up to the mailing list.
The close link should set a cookie value of 'seen_this_banner_thing' to true so we don't show it again
The sign up link should link to the new sign up page.
https://trello.com/c/OJ9lFk1M/129-add-banner-to-account-page
> add banner to account page

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/templates/frameworks/contract_review.html
- app/templates/frameworks/contract_start.html
- app/templates/frameworks/signer_details.html
- tests/app/main/helpers/test_frameworks.py
As of G-Cloud 10 we are using the new key `supplierRegisteredName` to hold the same data that `nameOfOrganisation` previously held.
This updates the frontend to be happy with either of the keys, so we can handle both G-Cloud 9 and G-Cloud 10 flows concurrently.
> BUGFIX: nameOfOrganisation key doesn't exist for newer frameworks

- app/templates/_base_page.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/H7upcsyQ/303-flash-messages-suppliers-app
Cleanup of the remaining `flag` type of flash messages. 
Once the User FE app is deployed with the changes in https://github.com/alphagov/digitalmarketplace-user-frontend/pull/50, the `flag` message won't be needed and we can use the generic toolkit `flash_messages.html` instead.
> Use flash_messages toolkit template to render flash messages

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
For this trello card: https://trello.com/c/UO08QNT9
The process for sending clarification questions doesn't involve replying
to the received email. To avoid any confusion the FROM address is being
changed to 'do-not-reply@...'
> Update FROM address for clarification questions

- app/main/views/suppliers.py
- requirements-app.txt
- requirements.txt
An update to FlaskWTF now causes `csrf_token` to appear in WTForm's
`form.data`. Our API doesn't like this so we need to strip it out when
we use the entire `form.data` as opposed to `form.<question>.data`. A
small utility in dm-utils will allow us to do this easily if end up
needing it in other apps.
> Remove CSRF token from form data

- app/__init__.py
- app/main/forms/auth_forms.py
- app/main/forms/frameworks.py
- app/main/forms/suppliers.py
- requirements-app.txt
- requirements.txt
- tests/app/main/helpers/test_suppliers.py
This reverts commit bc2df3289545cbb16cebb628fb1a821b13792d72.
We are going back to Flask-WTF==0.12 to keep our CSRF tokens compatible across apps until we can work out how to smoothly upgrade.
Will need to freeze-reqs after the utils PR goes in: https://github.com/alphagov/digitalmarketplace-utils/pull/382
> Revert "Bump Flask-WTF to match utils requirement"

- app/main/views/frameworks.py
- app/main/views/services.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Without these variables, the banner would show regardless of the
suppliers state. That is bad.
> Check contact details and declaration status for warning banner

- app/assets/javascripts/analytics/_events.js
- app/templates/services/previous_services.html
- package.json
- spec/javascripts/manifest.js
- spec/javascripts/unit/AnalyticsSpec.js
- yarn.lock
This has been ported over the buyer app so we can track service copying
when G-10 opens. Ideally this code should be in a shared place, the
frontend-toolkit. This is on Dilwoars list of things to do.
To make it more complicated we intentionally don't share apps
`_events.js` files. See here:
https://github.com/alphagov/digitalmarketplace-frontend-toolkit/commit/1d88cb8c6454c23fe89f96d901320f5935948504
> Add tracking to copying services

- app/templates/frameworks/_guidance_links.html
- package.json
- yarn.lock
Pull in latest frameworks which directs a declaration question to
correctly use the #reporting anchor on a framework dashboard.
Also adds the `reporting` element id to the dashboard.
Needs a `yarn install` after frameworks is merged.
> Update reporting anchor

- requirements-app.txt
- requirements.txt
Slight misunderstanding - the previous bump did *not* include the wtforms upgrade. this one does, and as such is the merge that must be released in sync with other frontends.
> digitalmarketplace-utils: bump to 36.2.2

- app/__init__.py
- app/main/forms/auth_forms.py
- app/main/forms/frameworks.py
- app/main/forms/suppliers.py
- tests/app/main/helpers/test_suppliers.py
The latest dependency bumps introduced a delightful 900+ deprecation warnings 😸 Thankfully these are easily fixed.
- Rename `CsrfProtect` to `CSRFProtect`
- Rename `flask_wtf.Form` to `flask_wtf.FlaskForm`
- Use `@application.errorhandler(CSRFError)` instead of `@csrf.error_handler`
> Fix deprecation warnings

- app/main/views/frameworks.py
- config.py
- tests/app/main/test_frameworks.py
Some of our emails get sent from `do-not-reply@digitalmarketplace...`.
If a user emails this, they get directed to email enquiries. We should
just directly set the reply-to address as enquiries.
Guidance: https://www.gov.uk/service-manual/technology/how-to-email-your-users#allow-users-to-reply-to-you
> Remove do-not-reply

- app/main/views/services.py
- tests/app/main/test_services.py
See this 2nd line ticket: https://trello.com/c/zb8Ee7EW
We currently don't check that a service has been found when a supplier
edits it. If one isn't returned from the api we end up getting a 500.
> Return 404 if no service found when editing

- app/main/views/suppliers.py
- app/main/views/users.py
- tests/app/main/test_notifications.py
- tests/app/main/test_suppliers.py
- tests/app/main/test_users.py
We currently use a paginated endpoint to retrieve users who are
contributors on a supplier account, but have no facility for getting to
page 2 or higher. A query came into DM support asking why some users
appeared to be missing from the contributors list.
This fix uses the `find_users_iter` method of the apiclient to return
all users associated with the supplier account. This fixes the immediate
problem.
I have created a follow-up product debt ticket to address the fact that
this page can now have an excessively long list and that we should
consider adding proper pagination to the view, as we have elsewhere on
the marketplace. We should also consider whether we want to alphabetise
or sort the list in some sensible way.
The original 2ndline ticket is here: …
> List all contributors

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_users.py
When a supplier registers interest in applying to join a specific
framework, we email all users associated with that supplier - in theory.
Unfortunately we only emailed the first page of users associated
with that supplier. We now have a supplier with over 100 users, so we
should retrieve all pages of results for users when sending the email
out. This page will become less performant over time and there isn't an
obvious fix beyond increasing the page size or running this task in the
background.
Some of the tests for deactivating supplier users incorrectly mocked out
`find_users`, which is not called as part of the view.
`test_cannot_deactivate_nonexistent_id` was missing a mock for
`get_user`, which meant it wasn't really testing the view correctly.
This mock has been added and an …
> Email all supplier users

- app/main/views/suppliers.py
- package.json
- tests/app/main/test_suppliers.py
- yarn.lock
For this trello ticket: [https://trello.com/c/7P1cRFqt](https://trello.com/c/7P1cRFqt)
The content was wrong and needed changing. This has been done in a separate PR on the frameworks repo and is already [merged](https://github.com/alphagov/digitalmarketplace-frameworks/pull/522)
We were ordering frameworks by their slug and then reversing. This was
so that they were ordered by family, newest first. This broke down
when we got to g-cloud-10 as lexicographically before g-cloud-9.
Ordering first by framework, then by id has the desired effect.
Screenshot of new content
> Update content for become a supplier messages

- app/main/helpers/frameworks.py
- tests/app/main/test_services.py
`framework_framework` is an unnecessarily obtuse variable name and is
not overly descriptive of what it actually means. When used, this
describes the 'family' of framework being referenced. For example,
G-Cloud 10 is in the 'G-Cloud' family of frameworks. Digital Outcomes
and Specialists 2 is in the 'Digital Outcomes and Specialists' family.
Let's change all the references of `framework_framework` to
`framework_family`
https://trello.com/c/iqFcVKpd/14
> Rename framework_framework variable

- app/main/errors.py
- app/main/views/services.py
- app/templates/errors/400.html
- tests/app/main/test_services.py
Unlike the buyer or user frontends, the supplier frontend didn't have a
custom error page, or even any error handling at all, for 400s. This
meant that any time `abort(400)` was being called the user would get
a janky horrible error page.
This allows a custom error message to also be passed through which wil
be displayed to the user.
> Add error page for 400s

- app/templates/frameworks/edit_declaration_section.html
QA noticed that validation is missing from declaration pages. This adds
it back.
https://trello.com/c/RSYEM3FL/448
> Add validation masthead to declaration

- app/main/views/frameworks.py
- app/templates/frameworks/_agreement_returned_legal.html
- config.py
- tests/app/main/test_frameworks.py
This feature is now live so the flag is no longer required.
https://trello.com/c/g1ARDY2f/472-contractvariation-feature-flag-can-be-removed-from-supplier-fe
> Remove contract variation feature flag

- app/main/views/suppliers.py
All pages that render `already_completed.html` need to inject the email
address from config.
Missed these in https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/892
https://trello.com/c/k0NZ5CHF/174
> Inject email address for all pages

- tests/app/main/test_frameworks.py
- tests/app/main/test_login.py
- tests/app/main/test_notifications.py
- tests/app/main/test_users.py
Part of the ongoing work to refactor the front end tests.
- Remove spurious `with self.app.app_context` context managers
- Move `data_api_client` patching to test setup methods (and shared return values for some of its methods, where sensible), to be consistent with our other test classes
- Minor whitespace tidying
Part 1 covers:
- `test_frameworks`
- `test_login`
- `test_notifications`
- `test_users`
Part 2 will cover:
- `test_services`
- `test_suppliers`
- Helper/validation functions.
Recommend ticking the 'hide whitespace changes' when reviewing!
> Refactor Supplier FE tests (part 1)

- app/main/forms/suppliers.py
- tests/app/main/test_suppliers.py
This has been done for consistency: labAddressPostcode field
is already validated in such a way.
Connected API pull request: https://github.com/alphagov/digitalmarketplace-api/pull/809
Trello tocket: https://trello.com/c/kOGpfxcw/475-supplier-fe-postcode-field-validation-is-more-lax-than-api-and-varies-between-two-forms
> Registered postcode can't be longer than 10 characters now

- tests/app/helpers.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_notifications.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
See part 1: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/894
- Move `data_api_client` patching to setup methods
- Remove unnecessary `app.app_context` and `self.app.test_client` context managers
- Organise `helpers/test_frameworks` into classes (and use consistent api patching)
- Whitespace tidying
Also fixes a typo in a test helper method param: 
`user_researh_opted_in` --> `user_research_opted_in`
> Refactor Supplier FE tests (part 2)

- app/main/forms/suppliers.py
- app/templates/suppliers/edit_vat_number.html
- tests/app/main/test_suppliers.py
Users were getting confused because the rest of the EU has VAT numbers that won't validate in this field.
> Constance VAT updates

- app/main/forms/suppliers.py
- tests/app/main/test_suppliers.py
This is because we found out that some US postcodes have as much
as 13 characters
Trello ticket: https://trello.com/c/kOGpfxcw/475-supplier-fe-postcode-field-validation-is-more-lax-than-api-and-varies-between-two-forms
API pull request: https://github.com/alphagov/digitalmarketplace-api/pull/812
> Increase allowed postcode length to 15 characters

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/dashboard.html
- app/templates/partials/service_warning.html
- app/templates/suppliers/already_completed.html
- app/templates/suppliers/details.html
- application.py
- requirements-app.txt
- requirements.txt
- tests/app/helpers.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
Suppliers need to confirm that the company details they've declared in
their account remain accurate over time as they apply to new iterations
of frameworks on the Digital Marketplace.
When suppliers first set up their account, they confirm that some
immutable attributes are correct: registered name, company registration
number, VAT number and DUNS number. Once these have been confirmed as
correct, they are locked down in the account and cannot be edited
without talking to support. Generally, these will only be updated by
support if there has been a mistake in entering the details. If the
details have legitimately changed, the supplier will need to create a
new supplier account on the Marketplace to complete their application.
After confirming their details are correct at the account …
> Confirm company details every application

- app/templates/suppliers/already_completed.html
- app/templates/suppliers/details.html
- tests/app/main/test_suppliers.py
After speaking with content again, we've decided that `Change` should be
the definitive link text and we'll add a short heading+sentence at the
bottom of the linked-to page which indicates what to do if their change
is not just about correcting a mistake.
https://trello.com/c/N5xfhxyh/191
> 'Change' company details

- app/main/helpers/frameworks.py
- tests/app/main/test_suppliers.py
The value for application_company_details_confirmed can theoretically be
any of True, False and None, so the checks around this state should be
'if not True' rather than 'if False'
> Application detail confirmation

- package.json
- yarn.lock
For [this trello ticket.](https://trello.com/c/VkAyVrzT)
See [this PR on the frameworks repo.](https://github.com/alphagov/digitalmarketplace-frameworks/pull/531)
Three new specialist roles have been added.
> Pull in updated frameworks for new DOS3 specialists

- app/main/views/services.py
- app/templates/services/service.html
- tests/app/main/test_services.py
Trello: https://trello.com/c/R3DsCXFa/22-use-frameworkfamily-frameworkfamily-in-apps-apiclient-rather-than-frameworkframework-frameworkframework
Part of the ongoing work to deprecate `frameworkFramework` in favour of `frameworkFamily`.
> Replace frameworkFramework with frameworkFamily

- requirements-app.txt
- requirements.txt
See [this PR on the apiclient for more details on what this brings in.](https://github.com/alphagov/digitalmarketplace-apiclient/pull/152)
It adds retries to the base apiclient. Hopefully to catch those pesky 503s.
> Pull in v19.0.0 if apiclient

- requirements-app.txt
- requirements.txt
https://trello.com/c/LD2eVPTY/368-supplier-user-can-be-created-but-no-email-sent
https://trello.com/c/7m7tPP83/379-email-validation-should-we-use-notifys
This should make our email validation more strict for supplier signup.
> digitalmarketplace-utils dependency: bump to 41.0.0

- app/main/views/frameworks.py
- app/templates/emails/follow_up_question.html
- tests/app/main/test_frameworks.py
For [this trello card.](https://trello.com/c/7lr17Qxo)
CCS's software strips the 'from' email address from follow up questions.
They need to be able to reply to them. We can include the users email
address in the body of the template to make sure they have it.
Rendered template before:
Rendered template after:
> Include user email in follow up question email

- app/main/__init__.py
- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/errors/applications_closed.html
- package.json
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- yarn.lock
For [this trello ticket.](https://trello.com/c/Msvn4HAz)
When applications for a framework close some views are no longer
available. This decorator is applied to those routes to provide users
with meaningful feedback and some extra logging for us.
The apiclient that's passed to the outer wrapper of the decorator is a
callable. This is because the decorator is evaluated at module import
time, which makes mocking the apiclient difficult. By providing it as a
callable it's evaluated at runtime and a mock can be patched in.
The custom error template includes content that is in the frameworks
repo. Its content that describes the expected following framework. If
that hasn't been defined, we show a reduced error message.
> Protect application editing routes with decorator

- app/__init__.py
- config.py
- requirements-app.txt
- requirements.txt
Trello https://trello.com/c/ZH9trgjH/419-snyk-alert-for-flask-010x-vulnerability
https://github.com/alphagov/digitalmarketplace-utils/pull/447
Another unremarkable conversion.
> digitalmarketplace-utils: bump to 43.0.0, remove featureflags references

- app/main/helpers/frameworks.py
- app/main/views/suppliers.py
- package.json
- requirements-app.txt
- requirements.txt
- tests/app/main/helpers/test_frameworks.py
- yarn.lock
Trello: https://trello.com/c/euSnpBnN/65-update-flask-login
- Update the Flask Login version
- Pull in related FE toolkit changes
- Fix occurrences of `current_user.is_authenticated()` --> `current_user.is_authenticated`
- Fix imports (we should not really have been importing `current_app` from `flask_login` anyway)
> Supplier FE: Update Flask Login to v0.4.1

- app/main/forms/auth_forms.py
- app/main/forms/frameworks.py
- app/main/views/frameworks.py
- app/templates/auth/submit_email_address.html
- app/templates/frameworks/contract_review.html
- app/templates/frameworks/contract_variation.html
- app/templates/frameworks/reuse_declaration.html
- app/templates/frameworks/signer_details.html
- app/templates/services/previous_services.html
- requirements-app.txt
- requirements.txt
This is part of the work for [my ticket](https://trello.com/c/AQVm3WXZ) to refactor the forms in supplier-frontend.
As this app has a very large number of forms, at @katstevens's suggestion I have split the work into two PRs part 1 and part 2 (to follow).
This PR deals with all the forms in the `app/main/forms/frameworks.py` and `app/main/forms/auth_forms.py` files. These are fairly straightforward forms which have mainly just been cleaned up using some of the new features from dmutils.
Notice I had to bring in a new version of dmutils to get some bugfixes.
> Refactor supplier-frontend forms, part 1

- app/templates/frameworks/contract_start.html
If the pdf is republished for any reason, the direct link breaks. Much
better to link to the splash page, which also gives the user more
options.
> Link to framework agreement splash page instead of pdf

- config.py
Flask was complaining that our cookie domain was invalid, which resulted in a lot of warning messages in our pytest output.
It turns out this was because we were setting the `SERVER_NAME` config variable in the Test config, which as far as I can tell is unnecessary; none of our other apps do it, and removing the setting didn't break any tests.
This PR closes https://trello.com/c/jUtB90p3/157-supplier-frontend-pytest-emits-a-lot-of-warnings-about-cookie-domains
> Fix cookie warnings

- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
Bugfix [for this trello ticket.](https://trello.com/c/7JftBnpe)
This is a temporary hot fix and will need proper design for a future proof
solution.
As DOS2 has expired it's no longer shown on the supplier dashboard. This
is a problem, as there are still active DOS2 opportunities that DOS2
suppliers can, and will for a couple of weeks, apply to.
Suppliers need to be able to access the details of the opportunities
they've applied to.
> Show expired DOS2 on supplier dashboard

- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
The supplier dashboard page currently shows DOS2 even though it's
expired. This is a temporary fix. The reason it was brought back was so
suppliers could see the opportunities they'd applied to. The links for
viewing their services and viewing documents however, return 404's as
the framework is expired.
Making those links work is probably the wrong thing to do, and we've
only seen a user need for suppliers to access their opportunities. This
PR removes the broken links.
> Remove services and documents links from DOS2

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
A recent support ticket has come in from a supplier wishing to view the contract variation for DOS 2.
Talking to product, it was agreed that suppliers should be able to view contract details even after a framework has expired.
Ideally a full solution would involve going through the framework pages and looking at what is accessible at what framework state, but for now to enable a quick fix for the user this PR will cover the contract variation case specifically.
> Allow viewing contract variation for expired framework

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
Reverts alphagov/digitalmarketplace-supplier-frontend#949 because this also allows suppliers to accept contract variations
> Revert "Allow viewing contract variation for expired framework"

- app/main/views/frameworks.py
- config.py
- tests/app/main/test_frameworks.py
I'm aiming to [replace mandrill throughout supplier-frontend](https://trello.com/c/jrpQHpGh/301-replace-mandrill-with-notify-in-frameworkupdatesemailclarificationquestion-route-on-supplier-fe), and this is the last thing that needs to be done. After this there'll be a pull request to utils to remove the client, but for now here's the last replacement of mandrill with notify.
I've updated an assertion method in the tests, and just for fun I've moved s3 patches to where they're needed, rather than dropping them on the whole class.
Huge thanks to @katstevens for pairing with me on this
> Replace mandrill with notify

- app/main/__init__.py
- package.json
- yarn.lock
Trello: https://trello.com/c/JPSjopsY/337-create-g11-framework-on-preview-and-set-to-coming
We explicitly load the content per framework on the Supplier FE's app init. It's quite verbose but the last time we looked at making this better, it proved too annoying to fix (https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/768).
> Prepare Supplier FE with G11 content

- app/main/helpers/validation.py
This should fix the failing functional tests on Preview.
The supplier's G11 declaration needs to be validated against a schema. The declaration is currently the same for G9, DOS2, G10 and DOS3 (which all use `DOS2Validator`) but this may change in the future.
> Add G11 declaration validator

- app/main/views/services.py
- tests/app/main/test_services.py
https://trello.com/c/MQlYqizw/
This wasn't so much a "double slash" problem - double slashes are (should be) squashed by our router so shouldn't be an issue. What it in fact _is_ is a missing framework slug element of the path. This is because the view was using `posted_data` as a substitute for `service_data` being passed to the template - but it's just not sufficient, missing most fields. This happened only on the "error" page because these urls have their `GET` and `POST` behaviours implemented as separate views, and the error case is the only time the `POST` view ends up rendering the page. It should be no surprise to you that this & other reasons is why I vastly prefer the "shared view" pattern instead.
The tests around this were also woefully under-assertive - nothing testing a …
> live service editing: fix update_section view's use of service data to ensure breadcrumbs work properly

- app/main/helpers/validation.py
- app/main/views/services.py
- requirements-dev.txt
- tests/app/main/test_users.py
Supersedes the current open PyUp PRs for this repo.
`flake8` now supports per-file-ignores well enough for our purposes. This means we can remove the extra `flake8-per-file-ignores` dependency.
The new version of flake8 suggested some indentation changes, which I agreed with.
> Update test dependencies

- app/main/forms/frameworks.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_services.py
Trello: https://trello.com/c/itTrzlID/363-g11-declaration-re-use-bug
The declaration reuse form had an unnecessary validator on it, causing a bug where the supplier could not proceed if they did not want to copy their declaration. 
The same issue was on a DOS validator for copying services, so I've updated that too.
Also bumps our 3 DM libraries to get rid of some deprecation warnings, and get rid of the unused Mandrill dependency.
> Declaration reuse bug

- app/main/views/frameworks.py
- config.py
- tests/app/main/test_frameworks.py
For the purpose of https://trello.com/c/49yR7N9O
These should make it easier to write functional tests for this process. Note the critical emails use `allow_resend=True` to prevent any (however unlikely) reference collisions preventing an email getting through.
> clarification/follow-up questions: use custom-generated references for emails

- package.json
- yarn.lock
Trello: https://trello.com/c/x5GVLSkq/384-implement-changes-for-legislation-changes-in-application-questions
Pulls in the fix from https://github.com/alphagov/digitalmarketplace-frameworks/pull/551, excluding updated service questions from the 'copy services' functionality.
> Pull in frameworks v14.0.1

- package.json
- yarn.lock
Trello: https://trello.com/c/5CzbmwiW/407-bug-fixes-for-the-supplier-declaration-journey
Pulls in some updated dates, validation etc. See https://github.com/alphagov/digitalmarketplace-frameworks/pull/553 for details. The breaking change for Elasticsearch should not affect this app.
> Pull in G11 content fixes

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/edit_supplier_organisation_size.html
- app/templates/suppliers/edit_supplier_trading_status.html
- app/templates/suppliers/edit_what_buyers_will_see.html
- app/templates/suppliers/registered_address.html
- tests/app/main/test_suppliers.py
Here's some refactoring I did of some of the forms in the supplier frontend.
The changes are part of what I was doing https://github.com/alphagov/digitalmarketplace-supplier-frontend/tree/ldeb-107-wtforms-dmfields-supplier-forms, but packaged nicer.
I want these changes to be in the supplier frontend now because I intend to reuse (some of) the code for the admin frontend, and it would be helpful to be able to point to the supplier frontend code in `master` as an exemplar.
> Refactor forms

- app/main/forms/suppliers.py
- package.json
- yarn.lock
Reverts https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1006 as it was causing functional test failures (still unsure why, but not really enough time to investigate - will create a tech debt ticket).
Also fixes a minor validation quirk - see comment in the code for details. Again, time constraints mean I haven't quite got to the root of why this is happening, but checking against staging reveals it was OK before the recent refactor to combine the country field with the other address fields into one form.
> Registered country fixes

- .flake8
- app/main/helpers/validation.py
Trello: https://trello.com/c/76VkxnU3/425-modern-slavery-validation-messages
The logic for required fields on the Modern Slavery section should go:
`Turnover: yes` + `Reporting requirements: yes` = statement required, explanation text not required
`Turnover: yes` + `Reporting requirements: no` = statement not required, explanation text required
`Turnover: no`: nothing else required
The extra logic triggered the flake8 complexity warning, I ignored it for the validator in the end (but did move out the declaration fields to an attribute of the validator class, which seemed neater).
The tests for the validator are a bit out of date, it might be good to update those later.
Screengrab:
> Modern slavery validation

- app/templates/frameworks/_session_timeout.html
Updated the message with suggestions from @pocketstefan.
> Change content of session timeout warning

- app/main/views/services.py
- app/templates/frameworks/_session_timeout.html
- tests/app/main/test_services.py
I missed a few views that were using the page template :embarassed:.
This PR adds the `session_timeout` variable to the views I missed.
It also adds some default text to make sure that in future the output will always make sense.
> Fix session timeout warning

- app/main/forms/frameworks.py
Trello: https://trello.com/c/I9MdAoMl/666-users-having-problem-copying-declarations-question
Weird bug where the form widget (or lack thereof?) wasn't allowing a True value to be posted.
This changes the presentation of the form to be a Yes/No question, will run it past product/content before merging.
> Add DMSelectionButtonBase widget to declaration copy form

- package.json
- yarn.lock
Trello: https://trello.com/c/wgdqi2gJ/668-g-11-declarations-questions-update-clarification-deadline
The clarification question deadline needed updating on one of the declaration questions.
> Pull in G11 content updates

- package.json
- yarn.lock
Trello: https://trello.com/c/2IUa5FqD/676-launchcloud-error-with-g-cloud-11-application-process
Don't copy across the `managementAccessAuthentication` field when copying services (as the value has changed and it breaks validation).
> Pull in frameworks 15.0.5 with copy-services fix

- app/assets/javascripts/application.js
When we included the GOV.UK Design System we inadvertantly included a
details polyfill that conflicts with our own, causing details elements
to stop working on Internet Explorer.
Although we could use the details polyfill from the design system, it
would involve changing the styling of our checkbox tree element, which
would be inadvisable during the framework application period.
Instead we just remove the javascript for the design system; it turns
out we don't need any of it currently.
In future we might need to include javascript for the design system
module by module rather than using `all.js`.
This has been tested locally with `make test` and functional tests.
> Fix details polyfill for service categories question

- app/main/views/frameworks.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
Trello: https://trello.com/c/F4fl895z/683-modern-slavery-statement-bug
This somehow missed our manual QA 🤦‍♀️ Tested the fix locally and it works for me.
The equivalent download view for service documents is here: https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/app/main/views/services.py#L498 (test structure is copied from here: https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/tests/app/main/test_services.py#L2291).
> Download declaration docs from S3 via asset url

- app/main/views/suppliers.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/pzAoSoTC/434-mailchimp-resubscribe-for-users-who-have-unsubscribed
Pulls in https://github.com/alphagov/digitalmarketplace-utils/pull/509 and https://github.com/alphagov/digitalmarketplace-utils/pull/511 (breaking change to subscribing users to Mailchimp lists).
The response has changed for both success and error statuses. We can now differentiate between errors where the user has already subscribed (i.e. no action required), where the user is providing a problematic email address (i.e. action should be to use a different email address) or where there is an unexpected error (do nothing for now).
Also added new flash messages type to cover this extra action (still need content approval for one of the two).
> Handle new Mailchimp responses

- app/assets/scss/application.scss
@katstevens noticed entries like this
```
2019-04-03T15:28:59.13+0100 [APP/PROC/WEB/1] ERR 2019/04/03 14:28:59 [error] 65#65: *1651608 access forbidden by rule, client: <REDACTED>, server: www.*, request: "GET /admin/static/fonts/bold-a2452cb66f-v1.woff2 HTTP/1.1", host: "www.digitalmarketplace.service.gov.uk", referrer: "https://www.digitalmarketplace.service.gov.uk/suppliers/static/stylesheets/application.css?f920dc2f15bf65d7d7b723e027092dbc"
```
in the router log recently, this change might help
> Use self for GOV.UK Frontend static assets

- requirements-app.txt
- requirements.txt
See fix for changes in the Mailchimp error response: https://github.com/alphagov/digitalmarketplace-utils/pull/514
The Supplier FE's use of the `DMMailchimpClient` is unchanged. The difference is that the client now passes through all otherwise unclassified 400s as 'invalid_email' so that the frontend can display an appropriate error message.
The utils bump also brings in the fix for Werkzeug proxy headers. For future reference, to get `make freeze-requirements` to behave, I had to do three freezes:
- pin Werkzeug to 0.15.1 (then freeze)
- bump utils to 48.0.3 (freeze)
- remove the Werkzeug pin (freeze)
> Pull in Mailchimp fix, unpin Werkzeug

- package.json
- yarn.lock
Trello: https://trello.com/c/1YUXLv7P/473-remove-unnecessary-clause-from-declaration-question
Pulls in https://github.com/alphagov/digitalmarketplace-frameworks/pull/565 to reinstate the old answer option for validation purposes.
> Pull in frameworks 15.3.2

- package.json
- yarn.lock
Reverts attempted content changes for G11 declaration.
> Bump digitalmarketplace-frameworks dependency to v15.3.3

- app/__init__.py
- app/metrics.py
- requirements.txt
- tests/app/helpers.py
- tests/app/main/test_metrics.py
* Add metrics
* Add tests
https://trello.com/c/7NhpkDWC/801-metrics-on-buyer-and-supplier-we-need-to-find-evidence-of-what-is-causing-the-slow-requests
> 801-metrics-on-buyer-and-supplier-we-need-to-find-evidence-of-what-is-causing-the-slow-requests

- Dockerfile
- requirements-app.txt
- requirements.txt
Part of https://trello.com/c/skD666lL
This should give us a bit more log detail for certain things possible healthcheck-failure related.
> bump digitalmarketplace-utils dependency to 48.3.0,  docker base image to 4.5.0 

- app/main/helpers/services.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
Trello: https://trello.com/c/acTQwafM/503-improve-getdrafts-helper
Makes use of the `find_draft_services_iter` API client method. The Supplier FE only gets draft services using this helper, and always iterates through them (twice!) to split them into submitted and non-submitted. 
The `iter` method returns a slightly different response so the tests have all had their mock return values updated.
No functional changes apart from (hopefully) efficiency. 
TBC: how to measure this properly...
> Speed up draft services helper

- Dockerfile
https://trello.com/c/PyDaRXEj
https://trello.com/c/skD666lL
https://github.com/alphagov/digitalmarketplace-docker-base/pull/53
This _should_ make instance shutdowns more graceful.
> Bump docker base image to 4.5.1 🔥

- Dockerfile
https://trello.com/c/skD666lL/
https://trello.com/c/PyDaRXEj/
See https://github.com/alphagov/digitalmarketplace-docker-base/pull/54
> bump docker base image to 4.5.2

- Dockerfile
https://trello.com/c/PyDaRXEj
https://trello.com/c/skD666lL
...effectively bringing it back to state as of 4.5.0
> bump docker base image to 4.5.3

- app/templates/suppliers/_frameworks_pending.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/HR9c6JJy/515-remove-blog-link-in-closed-applications-message
The blog closed in October 2018. Let's remove the link to it.
> Remove link to defunct DM blog

- app/main/__init__.py
- app/main/helpers/validation.py
- package.json
- tests/app/main/helpers/validation/test_g8_declaration.py
- yarn.lock
Trello: https://trello.com/c/kTVN6PlQ/532-clone-dos4-content
- Pulls in latest frameworks package and loads the DOS4 content in `__init__`
- Renames the `DOS2Validator` (used by all post-G8 frameworks) to something more sane, `SharedValidator`. 
- Adds tests for all that custom behaviour in the `get_required_fields` method (not enough time to do a proper refactor of this - we have a tech debt ticket already)
I'm going to update the section of the manual (https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/adding-frameworks.html#add-a-declaration-validator) with these changes.
> DOS4 declaration validator

- package.json
- yarn.lock
Trello: https://trello.com/c/uiyf7Wuk/115-dates-for-dos-4
Contains provisional dates from CCS (application deadline, clarification question deadline, go-live month).
> Pull in DOS4 dates

- package.json
- yarn.lock
See https://github.com/alphagov/digitalmarketplace-frameworks/pull/577
Unlikely to be the last content change needed, but at least this one is easily fixed.
The major version bump should only affect the content on the Buyer FE.
> Pull in frameworks 16.0.1

- app/main/__init__.py
- requirements-app.txt
- requirements.txt
https://trello.com/c/RW2tzjbM
A reworked version of https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1067
The content loader isn't threadsafe, so the easiest avenue towards thread-enabling an app is probably to supply each thread/context with its own copy of the content loader. Rather than constructing a new `ContentLoader` from scratch for each thread, allow the initial importing process to construct a "master" `ContentLoader` which we seal in a closure. The only things that can escape this closure are deep copies which should not share any mutable objects with each other and therefore be sufficiently
independent.
Each thread will make its own deep copy of this master content loader when it first needs one - a comparatively cheap operation.
> content loader: implement this as a thread/context-local (deepcopy edition)

- app/main/views/frameworks.py
- app/templates/frameworks/updates.html
- tests/app/main/test_frameworks.py
Trello: https://trello.com/c/3U1ORXqu/568-dos4-clarification-question-content-improvements
We're removing the post-clarification-deadline 'followup' question functionality. Instead we are directing suppliers to the Help page where they can contact support. This new process has been agreed with CCS.
Stefan has also supplied some new content that should help reduce the number of questions we receive (see ticket).
> Clarification question changes for DOS4

- package.json
- yarn.lock
https://trello.com/c/hJQFvCUe/569-dos4-service-question-error-banner-breaks-with-question-containing-link
- Pulls in fix for links appearing in validation mastheads (https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/472)
- Pulls in other bugfixes in the content, found during testing
> Pull in latest FE toolkit and frameworks content for DOS4

- app/main/helpers/validation.py
- package.json
- tests/app/main/helpers/validation/test_shared_validator.py
- yarn.lock
https://trello.com/c/Bw46fBz5/559-declaration-questions-for-mitigatingfactors-have-no-maxlengthinwords
We don't yet use JSON schema validation for declaration questions 😿 (there's already a tech debt ticket for that...)
I started a new test module for the `SharedValidator` so we don't have to keep tweaking G7/G8/DOS 1 submissions.
Tests will fail until https://github.com/alphagov/digitalmarketplace-frameworks/pull/581 is merged.
> DOS4 declaration word limit

- package.json
- yarn.lock
https://trello.com/c/BZ1PRdXo/567-update-text-what-it-means-to-be-on-digital-outcomes-and-specialists-4
Thought this was included in the last Supplier FE pull request, but it got missed. Adds in hardcoded list style: https://github.com/alphagov/digitalmarketplace-frameworks/pull/582
> Pull in DOS4 frameworks content 16.0.6

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
https://trello.com/c/2oq3Py0C/586-include-supplier-name-in-framework-clarification-question-email-to-ccs
It's difficult for suppliers to find the published answer to their question in the long PDF docs. Giving them a 'unique', dated reference ID to search by should help them do this while keeping the questions anonymous. See ticket for more context.
We've agreed the format with CCS: `YYYY-MM-DD-ABC123` where `ABC123` is a 'unique' hash.
'Unique' is in quotes for reasons commented in the PR itself - it should be sufficient for now.
The relevant Notify templates have been updated.
> Include a clarification question reference for suppliers

- app/main/views/frameworks.py
Could save our butts in a pinch.
> framework_updates_email_clarification_question: log supplier_reference before sending

- app/main/views/frameworks.py
It leads to confusing overall ids as we use dashes as the section separators.
> clarification question ids: don't allow dashes in hashed section

- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/services/service.html
- app/templates/suppliers/create_duns_number.html
- config.py
- tests/app/main/test_suppliers.py
- tests/app/test_application.py
https://trello.com/c/3om47rfx/601-update-remaining-instances-of-enquiriesdigitalmarketplaceservicegovuk-to-the-new-support-address
Centralises the support email rather than hardcoding it in:
- Service template error message
- DUNS number template error message
- Error messages when signing up for the supplier mailing list
Also updates some of the existing config emails.
> Support email update

- app/templates/frameworks/updates.html
trello: https://trello.com/c/ny3D7iox/213-supplier-communications-page-links-have-missing-a-tags
> closing an open anchor and aligning whitespaces

- app/main/helpers/services.py
- app/main/views/services.py
- tests/app/main/helpers/test_services.py
- tests/app/main/test_services.py
https://trello.com/c/IvrgIUND
This was quick & simple enough. Was going to do a total "audit" of places we were screwing this up by searching the prod database's audit table for non-`@`-containing `updated_by`s but realized we don't use email addresses in most of our script/manual updates.
> consistently use current_user.email_address for updated_by in API requests

- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
https://trello.com/c/sMuf2MLA/1156-fix-dos3-opportunities-on-supplier-fe
This bit of hardcoded logic got missed - suppliers who were on DOS3 need to be able to see their applications for opportunities still 'in flight'. 
I vow to not let this happen next year for DOS5 😿
> Update harcoded DOS2 link to be DOS3

- app/assets/javascripts/_stop-scrolling-at-footer.js
- app/assets/javascripts/application.js
- package-lock.json
- package.json
https://trello.com/c/aQbqH2uC/1196-vulnerability-fix-weekly-tracking
Addresses https://app.snyk.io/vuln/npm:jquery:20150627 and https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006 as highlighted by Snyk.
We no longer need to support IE7/8. 
There's one breaking change affecting the Supplier FE: `.load(fn)` has been deprecated (see [Changelog](https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed)) so and needs to be replaced with `.on('load', fn)`. 
The occurrence was in one of the old govuk_frontend_toolkit modules, so I've copied that file to `/assets` and made the change to the old `$(global).load(function (), ...)` call.
The checkbox-tree component itself is only used in the supplier framework application journey (when selecting service categories), so the …
> Upgrade Jquery to 3.x

- .travis.yml
- requirements-app.txt
- requirements-dev.txt
- requirements.txt
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Bumps content loader, utils, test utils and API client
- Adds 3.7 and 3.8 to Travis config
- Bumps lxml
> Enable Travis checks for Python 3.7 and 3.8

- app/main/views/frameworks.py
- app/main/views/services.py
- requirements-app.txt
- requirements.txt
https://trello.com/c/ooTuJDCw
Significant performance gains here. Partly from the content loader bump as it contains some opaque optimizations, but mostly stemming from these additions. These are all in places where it can be seen that the original object reference is discarded afterwards, so it can be considered safe.
> content loader: use new `inplace_allowed` options in .filter() and .summary() methods where appropriate

- app/templates/suppliers/details.html
https://trello.com/c/ExfE9b2d/188-3-update-breadcrumbs-to-use-govuk-frontend-component-in-supplier-frontend
Bug spotted while QAing the ticket above - one of the templates uses a different context variable for the current framework.
Before:
After:
> Fix breadcrumbs for company details page

- config.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
https://trello.com/c/4mGcaQuR/225-2-add-error-page-templates-to-supplier-frontend
Only a couple of xpath updates needed for the tests. 
I've checked that the custom error page in `app/templates/errors/applications_closed.html` still displays OK 👍
> Use digitalmarketplace-govuk-frontend error templates

- app/assets/scss/application.scss
- app/assets/scss/overrides/_temporary-messages.scss
Ticket: https://trello.com/c/lbW5IQFx/
We have an issue where text within a temporary message style banner (dark blue box with white text) was coloured black, resulting in very low contrast that is hard to read. It seems that for some reason the styles for govuk-body and govuk-link were being treated as more specifict than the styles for content within a temporary message.
This commit adds an Sass override that adds more specific CSS, restoring the colours as defined in the Digital Marketplace Frontend Toolkit.
> Fix styles for banner using temporary message styles

- app/templates/suppliers/create_your_account_complete.html
@NoraGDS spotted that the page heading for this page disagreed with the
page title and breadcrumb.
> Fix page heading for page "Activate your account"

- package-lock.json
- package.json
Ticket: https://trello.com/c/i4eJBbNC/274-replace-content-supplier-a-z-with-supplier-a-to-z
Updates digitalmarketplace-govuk-frontend from 0.3.1 to 0.4.1, pulling in the new footer.
> Update link text for 'G-Cloud supplier A to Z' for footer link

- app/assets/scss/overrides/_temporary-messages.scss
- app/templates/suppliers/_frameworks_coming.html
- gulpfile.js
- tests/app/main/test_suppliers.py
Ticket: https://trello.com/c/lbW5IQFx/
Copied from alphagov/digitalmarketplace-buyer-frontend#982
The framework pending message (if you've started a framework application but not completed it) also has the black text on dark blue background problem; using @katsteven's fix worked a treat :)
Also I cleaned up a temporary message component instance from 2015, and made a small tweak to our gulpfile to make it more dev friendly.
> Fix styles for temporary message text

- package-lock.json
- package.json
https://trello.com/c/VLjBsVoc/257-service-question-change-make-servicedefinitiondocumenturl-mandatory
Make service definition document mandatory
Update package.json for new mandatory service definition doc
https://github.com/alphagov/digitalmarketplace-frameworks/pull/602
> 257-service-question-change-make-servicedefinitiondocumenturl-mandatory

- app/main/helpers/validation.py
https://trello.com/c/ypNRnhEP/259-update-declaration-validation-code-in-supplier-fe-2
- Explicitly set `g-cloud-12` to use the `SharedValidator`. This is in case we want to switch to a custom validator at a later point (e.g. to deal with any dependency change in the first two questions)
- Use the `SharedValidator` as the default, so future frameworks won't immediately break
> Add shared validator for G12

- app/templates/suppliers/dashboard.html
- tests/app/main/test_suppliers.py
trello: https://trello.com/c/X1LuXpy4/313-add-link-to-cookie-settings-page-on-user-dashboards-1
I'd rather change the paragraph elements on the side into a list. Let me know.
> cookie settings link at dashboard and test for it

- app/templates/suppliers/create_confirm_company.html
- app/templates/suppliers/create_new_supplier.html
See ticket:
https://trello.com/c/O0KrgXHE/317-transfer-content-and-design-changes-from-prototype-to-preview-for-g12
> 317-1-transfer-content-and-design-changes-from-prototype-to-preview-for-g12

- app/templates/_base_page.html
- app/templates/suppliers/create_company_summary.html
- app/templates/suppliers/create_confirm_company.html
https://trello.com/c/XxuH7Q9z
New look:
> supplier creation templates: replace use of summary tables with new govukSummaryList

- app/templates/_base_page.html
- app/templates/suppliers/create_company_summary.html
- app/templates/suppliers/create_confirm_company.html
Revert alphagov/digitalmarketplace-supplier-frontend#1186 until I've fixed the FTs to cope with summary lists a bit better.
> Revert "supplier creation templates: replace use of summary tables with new govukSummaryList"

- package-lock.json
- package.json
https://trello.com/c/WyCs0t4g/302-3-review-and-update-answerrequired-error-messages-for-g-cloud-12-questions-in-frameworks-repo
Pulls in new G12 error messages that help us better meet the WCAG guidelines.
See https://github.com/alphagov/digitalmarketplace-frameworks/pull/606 for a list of changes.
> Pull in G12 error message updates

- app/templates/_base_page.html
- app/templates/suppliers/create_company_summary.html
- app/templates/suppliers/create_confirm_company.html
Reverts alphagov/digitalmarketplace-supplier-frontend#1188, which itself is a reversion of #1186 - the FTs are pretty much ready to go for this now (https://github.com/alphagov/digitalmarketplace-functional-tests/pull/739)
> Revert "Revert "supplier creation templates: replace use of summary tables with new govukSummaryList""

- package-lock.json
- package.json
https://trello.com/c/Rtcc6oi6/316-add-link-to-guidance-on-making-accessible-pdfs-on-application-5-places
Adding guidance links for suppliers who are uploading PDFs.
See https://github.com/alphagov/digitalmarketplace-frameworks/pull/608 for examples.
~[WIP until the frameworks PR is merged]~ Now ready.
> Pull in PDF guidance on G12 questions

- app/assets/scss/application.scss
- app/assets/scss/overrides/_task-list.scss
- app/main/views/frameworks.py
- app/templates/_base_page.html
- app/templates/frameworks/_framework_actions.html
- app/templates/frameworks/dashboard.html
- app/templates/frameworks/submission_lots.html
- tests/app/main/test_frameworks.py
https://trello.com/c/W9biikjw/352-implement-framework-application-dashboard-design-changes
Following design review from @joelanman. 
- SCSS and template structure are taken from the Notify task-list component (see ticket).
- Removing some of the content simplified the logic on the template
- Note that the URL for 'Make your supplier declaration' is still different depending on whether they've already started it or not.
- I've removed the 'success' banner from the main dashboard template, and moved it into the `_framework_actions` template (as it only gets shown during an open framework)
- I've tweaked the success banner content to try and clarify to suppliers that their application will still be submitted if at least 1 service is complete, even if they have remaining unsubmitted draft …
> Simplify framework dashboard

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
Bug found during G12 QA: if a supplier goes back and edits the Modern Slavery statement (multiquestion) section, then re-submits, it gives an error that the existing file hasn’t been uploaded. This is because the form macro doesn't set the value on the file upload input (for good reason - it's a security hole).
Therefore we need to address this on the validation side. I can recreate it with the new unit test. It's a complete hack, given the short timescale - better suggestions very welcome!
> Handle pre-existing file uploads in declaration data

- app/templates/services/edit_submission_section.html
Oops. these links were the wrong way round.
> edit_submission_section template: fix switched breadcrumb links

- app/templates/frameworks/updates.html
Bugfix: the guidance link above the Clarification Question form points to DOS guidance (hardcoded from last year).
I've changed this to use the dynamic guidance link we use elsewhere on the Supplier FE.
> Use dynamic guidance link instead of hardcoded DOS link

- config.py
https://trello.com/c/085wlnUP
This was presumably disabled to allow gatling scripts to run, but we now have a mechanism in place that allows gatling to work properly with csrf.
> config: re-enable WTF_CSRF_ENABLED for staging

- app/assets/scss/application.scss
- app/assets/scss/overrides/_list-entry.scss
https://trello.com/c/Ydy4QR9G/
When the screen width was small enough for the 'Remove' button to wrap onto a new line, the button was previously overlapping the text input, causing the list entry row to be removed when a user was trying to click onto it.
Overriding the GOVUK Frontend button positioning only for `list-entry` secondary action buttons  fixed the problem on Chrome.
> Fix list entry secondary button positioning

- package-lock.json
- package.json
- requirements-dev.txt
- requirements.txt
Pulls in digitalmarketplace-frameworks 17.8.2 with alphagov/digitalmarketplace-frameworks#615.
Also had to update PyYAML to make PyUp SafetyCI happy.
> Update G-Cloud 12 dates

- app/templates/macros/pricing-input/content-loader-macro.j2
- app/templates/macros/pricing-input/macro.njk
- app/templates/macros/pricing-input/pricing-input.yaml
- app/templates/macros/pricing-input/template.njk
- app/templates/macros/toolkit_forms.html
- tests/app/main/test_services.py
https://trello.com/c/yld9eBvJ/6-3-rebuild-pricing-form-template-using-govuk-design-system-components-in-supplier-frontend
A new pricing input macro `dmPricingInput` has been created in the supplier frontend. I haven't added it to digitalmarketplace-govuk-frontend because it is only used in the supplier frontend. The template is based on the [date input component in govuk-frontend].
Another separate macro has also been created, `clPricingInput` (suggestions on a better name welcome), to take input from the content loader and create a form. It was split into two macros in this way partly to keep the implementation of `dmPricingInput` clean, and also as an experiment into how we can create content loader macros for other form components in future.
Things I decided not to implement:
- message …
> Rebuild pricing input component using GOV.UK Design System components

- app/main/helpers/services.py
- app/main/views/services.py
- tests/app/main/helpers/test_services.py
- tests/app/main/test_services.py
https://trello.com/c/WBjRZd14/80-2-frameworks-repo-copyservices-list-exclude-rather-than-include-fields
Implements the changes in https://github.com/alphagov/digitalmarketplace-api/pull/1038.
If a `questionsToExclude` list is provided in the frameworks metadata, use that instead of the `questionsToCopy` list (which is to be deprecated).  For G12 we are still using the `questionsToCopy` list.
Notes to reviewers: 
- I tried splitting this into smaller commits, but without refactoring a bunch of stuff I couldn't get each commit in a state where the tests were passing.
- The bulk-copy API endpoint expects a list of questions, not a set or tuple, so I've changed the test data returned from the mock metadata call to reflect this.
~Functional tests PR coming shortly!~ Functional tests now merged …
> Copy services using questions_to_exclude list

- app/assets/scss/application.scss
- app/main/views/frameworks.py
- app/templates/frameworks/_submitted_services.html
- app/templates/frameworks/services.html
- app/templates/frameworks/submission_lots.html
- tests/app/main/test_frameworks.py
https://trello.com/c/PbSiUZeG/1800-allow-g12-suppliers-to-view-incomplete-applications-post-deadline
Makes changes to three views in the framework application process:
- Framework dashboard (summary of application)
- Framework submission lots (summary of services on all lots)
- Framework submission services (list of submitted/unsubmitted services for a lot)
Suppliers who completed an application can already view the details of what they submitted (declaration and services).
These changes allow suppliers who did not complete an application to view details of their partial application.
On the framework dashboard:
- Add links to services (if any have been created)
- Add links to declaration (if started)
- Display appropriate content if either services or declaration are not available
On the …
> Suppliers can view incomplete applications post-deadline

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
On the supplier's framework dashboard, in order to show the 'last updated' dates on the framework legal documents, we traverse the entire framework directory in the S3 comms bucket. 
For local developers, this means *everything* in the dev-uploads bucket is parsed, which could be hundreds of documents (from functional tests). The longer the framework runs, the more documents will be in the bucket, and the slower it will get.
This PR narrows down the scope to just the communications folder (legal docs and clarification updates), which should be a fixed number of files throughout the lifetime of the framework.
This change won't affect Preview/Staging/Production as submission documents go to a separate bucket. There are potential improvements to be made here too, but they're more involved. …
> Improve framework dashboard load time for local envs

- .secrets.baseline
Adds secrets baseline as per
https://github.com/alphagov/gds-pre-commit/
https://trello.com/c/jbk1Il5K/1851-install-gds-pre-commit-and-commit-secretsbaseline-to-repos
I was initially getting some weird behaviour where `detect-secrets` would not work if virtualenv was enabled. Or the global `detect-secrets` did not produce the file in the same format expected by the pre-commit hook. To workaround this I ran:
`pip3 install detect-secrets==0.13.1` as suggested by @heathd. 
this installs the same version used by the pre-commit hook into pyenv environment.
When generating the baseline I used
`detect-secrets scan --exclude-files package-lock.json > .secrets.baseline`
this avoids many false positives associated with package integrity hashes.
> add secrets baseline

- app/templates/suppliers/create_company_details.html
https://trello.com/c/XGSVuDnG/
We need to explicitly disable autocomplete for this field - Chrome appears to be inferring that this is a Title field because the following field is Contact Name.
[Chrome does not support `autocomplete="off"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) so I've gone for a dummy value instead.
> Prevent Chrome autofilling company name

- app/templates/frameworks/_framework_agreement_legal_text_g-cloud-12.html
- app/templates/frameworks/sign_framework_agreement.html
- tests/app/main/test_frameworks.py
Follow-up after #1239
adds test for legal text.
Thought it better to add these as unit tests than adding to https://github.com/alphagov/digitalmarketplace-functional-tests/pull/788
> Add tests for legal text

- app/assets/scss/application.scss
- app/assets/scss/overrides/_pending-services-table.scss
- app/templates/suppliers/_frameworks_standstill.html
- tests/app/main/test_suppliers.py
https://trello.com/c/xGMqeI71/1895-ccsrequests-g-cloud-12-service-visibility-query
We want suppliers to be able to see their framework documents before signing. This commit changes the card so that there is always a "view your documents" link.
> Add link to framework documents to pending services card

- package-lock.json
- package.json
https://trello.com/c/TgUYx7Fx/1909-ccsrequests-re-g-cloud-12-framework-agreement-error
A new version of the G-Cloud 12 framework agreement was published on GOV.UK, we need to update our links.
> Bump digitalmarketplace-frameworks from 17.12.0 to 17.12.1

- app/assets/scss/overrides/_task-list.scss
- app/templates/frameworks/_framework_actions.html
Trello: https://trello.com/c/WlpUAQZe/327-1-update-supplier-fe-content-for-dos5-application-journey
Ultimately, we will migrate over to Design System 3 and use the native task list pages (see https://design-system.service.gov.uk/patterns/task-list-pages/). In the interim, though, update the button colours to make them look more like the design system.
New:
Old:
> Make task buttons resemble the design system

- app/main/__init__.py
- app/templates/suppliers/already_completed.html
- app/templates/suppliers/create_company_details.html
- app/templates/suppliers/dashboard.html
- app/templates/suppliers/details.html
- app/templates/suppliers/edit_company_registration_number.html
- app/templates/suppliers/edit_registered_name.html
- app/templates/suppliers/edit_supplier_organisation_size.html
- app/templates/suppliers/edit_supplier_trading_status.html
- app/templates/suppliers/edit_what_buyers_will_see.html
- app/templates/suppliers/registered_address.html
- tests/app/main/test_suppliers.py
It broke the functional tests and un-breaking them is non-trivial. Reverting for the moment.
Reverts alphagov/digitalmarketplace-supplier-frontend#1248
> Revert "Add DOS 5 and start applying accessibility improvements"

- app/main/__init__.py
Trello: https://trello.com/c/WlpUAQZe/327-1-update-supplier-fe-content-for-dos5-application-journey
This should unblock testing of the DOS 5 content changes.
> Load DOS 5 manifests

- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- app/templates/suppliers/_frameworks_standstill.html
- requirements.in
- requirements.txt
- tests/app/main/test_suppliers.py
https://trello.com/c/ZUgsBovZ/361-2-prep-and-test-buying-journey-for-g12-on-preview
When a framework is live, we want users to be able to view their services and documents, even if they have an agreement signature outstanding.
> Show services and documents links on dashboard

- app/main/forms/frameworks.py
- app/templates/frameworks/sign_framework_agreement.html
- tests/app/main/test_frameworks.py
Another couple of fixes from: https://trello.com/c/NutOcwCP/342-2-placeholder-triage-and-fix-e-signature-issues
* Updated error message suggested by @NoraGDS 
* Make form two thirds column
> e-signature signing page tweaks

- package-lock.json
- package.json
Trello: https://trello.com/c/yWkgqyPL/325-2-update-dos5-application-content-in-the-frameworks-repo
This will pull in various bits of DOS 5 content, so we can start testing them in preview.
> Take latest version of frameworks dependency

- app/main/helpers/validation.py
- tests/app/main/helpers/validation/test_dos5_declaration.py
Trello: https://trello.com/c/Oqg9AUup/328-3-update-conditional-logic-for-declaration-question-q53-for-dos5
For DOS 5, we've renamed `primaryContactEmail` to `contactEmail`. Add a new validator for DOS 5 (+?) to handle this renamed field.
Also add validation for the new percent question - it's a number between 0 and 100. We need a new validator because the existing one used for the DUNS number validates numbers with a fixed length, which is not right for a percentage.
> Validate declaration questions for DOS 5

- package-lock.json
- package.json
Ticket: https://trello.com/c/Bt72BXJZ/430-update-error-messages-for-dos-5
Pulls in the changes to error messages.
- [Commits](https://github.com/alphagov/digitalmarketplace-frameworks/compare/v17.17.6...v17.17.7)
> Bump digitalmarketplace-frameworks from 17.17.6 to 17.17.7

- package-lock.json
- package.json
bump frameworks version to pick up changes from: https://github.com/alphagov/digitalmarketplace-frameworks/pull/649﻿
https://trello.com/c/rYwa42rs/1954-error-messages-dos5
> bump frameworks version

- config.py
- requirements.in
- requirements.txt
For development instances we want developers to be able to use a tool like [localstack] instead of real AWS endpoints. The Flask configuration variable DM_S3_ENDPOINT_URL can be used (if set) by dmutils.s3.S3 to connect to a localstack instance (see alphagov/digitalmarketplace-utils#580).
This commit adds DM_S3_ENDPOINT_URL to the Development configuration only, and makes it dependant on an environment variable, DM_S3_ENDPOINT_PORT (so we can set the port only, or the port and hostname, using envvars).
[localstack]: https://github.com/localstack/localstack
> Add DM_S3_ENDPOINT_URL to Development config

- app/main/helpers/frameworks.py
- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
Fulfil [Kat's vow](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1123). We need to show the previous DOS framework so that suppliers can see their applications on the previous DOS framework. Previously, we did this by hard coding the last DOS framework in the code.
Now do it by choosing the expired DOS framework with the latest expiry date. This will save us from needing to remember to update this manually when we make DOS 5 live.
> Un-hard-code previous DOS framework

- .gitignore
- .secrets.baseline
- Makefile
- app/__init__.py
- app/main/helpers/validation.py
- app/status/views.py
- config.py
- mypy.ini
- requirements-dev.in
- requirements-dev.txt
This PR adds [`mypy`](http://mypy-lang.org/) static type checking to the checks performed on `make test` and on Travis CI (but not on commit).
I've also fixed/ignored the issues mypy picked up as appropriate.
I copied the approach from [dmrunner](https://github.com/alphagov/digitalmarketplace-runner/pull/51), which we did first.
> Use mypy to test typing

- app/main/helpers/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_coming.html
- config.py
- tests/app/main/helpers/test_suppliers.py
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/KikQx3R2/593-as-a-g12-recovery-supplier-i-can-see-something-other-suppliers-cannot
We had an outage during G12 closing. Some suppliers will be involved in a recovery process to account for the outage causing them to fail to submit their services in time.
We have previously provided a list of the affected supplier IDs via the environment - see https://github.com/alphagov/digitalmarketplace-credentials/pull/359 and https://github.com/alphagov/digitalmarketplace-aws/pull/797. This PR proves that this all works by displaying a placeholder to the affected suppliers.
Currently, the only supplier so configured is our test supplier, so this will not be shown to any real users and is therefore safe for production. The two tests check this.
> Distinguish G12 recovery suppliers

- .github/workflows/test.yml
Spotted this issue when reviewing https://github.com/alphagov/digitalmarketplace-scripts/pull/588 the second variable wasn't being resolved which made the cache key non-unique across matrix runs.
> fix cache key by using correct variable

- .secrets.baseline
- app/templates/_base_page.html
- app/templates/frameworks/_agreement_returned_legal.html
- app/templates/frameworks/_guidance_links.html
- app/templates/frameworks/updates.html
- package-lock.json
- package.json
- tests/app/main/test_frameworks.py
https://trello.com/c/tUd7Ck2w/275-5-replace-document-links-with-attachment-component-in-frontend-apps
This PR uses the new Attachment component to display document downloads on these two pages:
`suppliers/frameworks/<framework>`
`suppliers/frameworks/<framework>/updates`
We currently don't offer a way to acquire more accessible versions of our documents. This makes it easier for users to request them, and provides a way to show more metadata about files once we have a way to extract that information on the backend.
* We don't currently provide much metadata beyond file type and last modified date
* On the updates page, we're currently using the file extension to pass in type, when we should ideally be using MIME types like `application/pdf`
* Using a Details component (for the contact …
> Add attachment component to Frameworks dashboard and updates pages

- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- tests/app/helpers.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/B05l52YO/612-2-as-a-g12-recovery-supplier-i-can-see-how-many-draft-g12-services-i-have
In [the last PR](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1288), we gave supplier-frontend knowledge of which suppliers are part of the G12 recovery.
Allow these suppliers to see the 'Your services' page for G12, which shows all their draft services for G12.
We've not tested whether the links on the page work - the next story will cover sorting them out.
> Show G12 recovery users their number of draft services

- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/_base_page.html
- tests/app/main/test_frameworks.py
- tests/app/main/test_suppliers.py
Ticket: https://trello.com/c/Vp3FZhKc/289-replace-flash-messages-with-digital-marketplace-govuk-frontend-alert-component-in-supplier-frontend
We want to use the dmAlerts macro instead of the old flash-messages 
template, as dmAlert is based on GOV.UK Design System styles and guidance.
> Replace flash messages with alerts

- app/main/views/services.py
- app/templates/partials/g12_recovery_information.html
- app/templates/suppliers/dashboard.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/n2Eop9FB/644-2-as-a-supplier-i-know-when-the-deadline-is
We show this banner to suppliers involved in the G12 recovery - and none others. It will help them understand when the deadline is for the recovery process and what they need to do.
Content is not final - just putting the banner into place for the moment.
Hard-code the closing date. This is fine because we're going to remove all this code after the recovery process is complete, so it doesn't need to be re-usable.
Add tests to check that this shows up iff the supplier is a recovery supplier.
> Add G12 recovery banner to supplier dashboard

- app/main/helpers/suppliers.py
- app/main/views/suppliers.py
- app/templates/partials/g12_recovery_information.html
- tests/app/main/helpers/test_suppliers.py
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/n2Eop9FB/644-2-as-a-supplier-i-know-when-the-deadline-is
The G12 recovery process is for suppliers who were affected by the outage during G12 closing. We will give these suppliers an opportunity to submit the services that the outage disrupted.
In https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1297, we created a banner that we will display to suppliers involved in the G12 recovery - and none others. It will help them understand when the deadline is for the recovery process and what they need to do.
This PR updates the banner with the content from @NoraGDS 
(Note that the deadline is currently hardcoded to a placeholder in 2525. We'll need to update when we know the actual date.)
> Update content in G12 recovery banner

- app/templates/suppliers/_frameworks_coming.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/NhWv5iIk/647-1-remove-extraneous-g12-recovery-stuff
We now have the G12 banners, so we no longer need the placeholder to prove that the G12 allow-list is working.
This partially reverts 51be819e134c0e24f57f0b32de7e8eda9dbc27e6.
> Remove G12 recovery placeholder

- app/main/views/services.py
- app/templates/services/list_services.html
- app/templates/services/service_submission.html
Trello: https://trello.com/c/n2Eop9FB/644-2-as-a-supplier-i-know-when-the-deadline-is
The G12 recovery process is for suppliers who were affected by the outage during G12 closing. We will give these suppliers an opportunity to submit the services that the outage disrupted.
Show [the banner telling suppliers how long they've got](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1298) on two new pages: 'Your G-Cloud 12 services' and the submission summary
> Show G12 recovery banner on service pages

- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/NhWv5iIk/647-1-remove-extraneous-g12-recovery-stuff
This reverts commit ed72149f6687691ea4ecbcbee16e28236059021a from https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1292.
We have since chosen to add the draft services to the 'Your G-Cloud 12 services' page instead of having a stand-alone page for the draft services. So we can now remove this link, which is not needed.
> Revert "Show G12 recovery suppliers link to 'add services'"

- app/assets/scss/_list_all_services.scss
- app/assets/scss/application.scss
- app/main/views/services.py
- app/templates/services/list_all_services.html
- tests/app/main/test_services.py
https://trello.com/c/0igPI9kJ/
The G12 recovery process is for suppliers who were affected by the outage during G12 closing. We will give these suppliers an opportunity to submit the services that the outage disrupted.
We want G12 recovery suppliers to be able to see all live and draft (submitted or unsubmitted) services on one page; this PR adds a new route `/suppliers/frameworks/g-cloud-12/all-services` which does this. The typical list services route `/suppliers/frameworks/g-cloud-12/services` will redirect to this page if required, so we have fewer links and breadcrumbs to update.
> Add page to view all services for G12 recovery suppliers

- app/main/helpers/suppliers.py
- tests/app/main/helpers/test_suppliers.py
Trello: https://trello.com/c/n2Eop9FB/644-2-as-a-supplier-i-know-when-the-deadline-is
We don't yet know when the deadline is, so set it to a dummy date in the far future. However, this means that the number of days remaining decrements every day and breaks the visual regression tests.
Switch to a dummy date in the far past. The banner will now always read '0 seconds remaining'.
Also fix a bug I found with dates more than 1 day in the past.
> Set the G12 recovery deadline in the past 

- app/main/views/suppliers.py
- app/templates/suppliers/_frameworks_live.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/NhWv5iIk/647-1-remove-extraneous-g12-recovery-stuff
Reverts https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1302
I was over-eager when reverting. Yes, I removed the 'Add a service' link, which was what I meant to do. However, I also removed the special case handling of the other links. This ensures that G12 recovery suppliers see the link to 'Your G-Cloud 12 services' even if they have no live G12 services.
#1301 depends on this link existing. So revert the revert so that the link to 'Your G-Cloud 12 services' appears for all G12 recovery suppliers once more.
Then perform a surgical removal of only the 'Add a service' link. Update the tests to check all G12 recovery suppliers can still see the other links.
> Remove 'Add a service' link without also removing other links

- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/e3KDduMm/652-fix-broken-links-for-g12-recovery-suppliers-without-live-services
Previously, we were showing this link to G12 recovery suppliers who were not on the framework. If these suppliers tried to follow the link, they would get an error page.
We still want to pretend to be on the framework for the purposes of getting the right things displayed elsewhere. However, by doing the hack just a little later, we can avoid messing up the determination of whether the supplier needs to sign the framework agreement.
Extend the test to test this.
> Stop showing broken link to sign agreement

- app/templates/frameworks/sign_framework_agreement_confirmation.html
https://trello.com/c/75hbcRW8/607-3-implement-dos-5-e-signature
Previously on the e-signature confirmation page the framework name was clipping as it the `nowrap` style prevented it from wrapping. For now this just removes this so it doesn't clip. Although it will wrap for G-Cloud-12.
**Before**
**After**
> Stop DOS5 text clipping

- .github/workflows/test.yml
- requirements-dev.in
- requirements-dev.txt
With this change we no longer need to install lxml dependencies in ubuntu
> bump lxml and remove apt get dependenices from github action

- app/templates/partials/g12_recovery_information.html
From https://trello.com/c/Kox43DLs/653-1-space-the-banner-text
Before
After
> Add extra line break in G12 recovery banner

- app/templates/services/service_submission.html
- tests/app/main/test_services.py
We're going to stop G12 recovery suppliers from creating new draft services other than the ones they've already submitted in previous recovery phases, so we need to prevent a supplier from accidentally deleting a draft and needing to contact support to get it re-added.
This PR hides the 'Remove draft service' button on the service submission page for G12 recovery suppliers. I've checked other pages and can't see any other method for a supplier to delete a draft service, so I think hiding this button is enough to finish the below story.
https://trello.com/c/1Jgs4nZ4/684-1-stop-users-being-able-to-delete-draft-services
> Hide 'Remove draft service' button for G12 recovery suppliers

- app/main/helpers/frameworks.py
- app/main/views/frameworks.py
- app/main/views/suppliers.py
- app/templates/frameworks/_agreement_returned_legal.html
- app/templates/frameworks/_framework_actions.html
- app/templates/suppliers/_frameworks_live.html
- app/templates/suppliers/_frameworks_standstill.html
https://trello.com/c/75hbcRW8/607-2-implement-dos-5-e-signature
@NoraGDS spotted we should be using the contract title variable on the frameworks dashboard, as it now varies between frameworks.
> use contract title on dashboard

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
Ticket: https://trello.com/c/QBCaiojj/698-fix-mark-as-complete-redirect-in-g12-recovery-flow
For G12 recovery suppliers we need to fix breadcrumbs that link to the "Services" and lot page, and also change where the user ends up after marking a service as complete.
This commit does this in a fairly brute-force way, by making those urls always redirect to the `all_services` route; however I think this should be fine because they will not need to see the pages we are redirecting away from anyway.
> Change submissions and service submissions pages to redirect to all services page for G12 recovery suppliers

- app/main/views/services.py
Part of https://trello.com/c/13Ryt5o5/
The G12 recovery all services page should have three tables, currently called "Draft services", "Complete services", and "Live services". We want "Complete services" to show submitted draft services that are not live, so we need to filter out submitted draft services that have been published. This commit does that.
> Fix G12 recovery all services view to remove live services from completed services

- app/main/views/suppliers.py
- requirements.in
- requirements.txt
Trello: https://trello.com/c/bZ4XlASA/617-1-log-directplusclient-errors-instead-of-swallowing-them
At the moment, we allow users to create an account if the D&B API produces an error that is valid JSON, but not if it's not valid JSON. This is odd and inconsistent. And I think it's unintentional - looking at utils, it looks as if the original author didn't know that about the different error for invalid JSON.
Change the behaviour to be consistent by always failing open. The behaviour now fully matches the intents of the comments.
Also pull in alphagov/digitalmarketplace-utils#596, which improves logging of D&B API errors.
> Always fail open if D&B API errors

- .secrets.baseline
- app/main/helpers/suppliers.py
- app/main/views/services.py
- config.py
- tests/app/main/helpers/test_suppliers.py
- tests/app/main/test_services.py
Trello: https://trello.com/c/13Ryt5o5/679-5-as-a-supplier-i-cannot-see-submit-any-draft-services-that-ccs-will-not-consider
As part of the G12 recovery process, users are only able to submit certain drafts. To avoid confusion and unnecessary work, we're going to hide all other drafts from the G12 recovery process for suppliers.
Only show drafts that are in the allow-list - both submitted and un-submitted.
Tests prove that this is working.
This PR is very similar to https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1288.
> Show only selected drafts for the G12 recovery

- app/main/helpers/suppliers.py
- app/main/views/services.py
- config.py
- tests/app/main/helpers/test_suppliers.py
Trello: https://trello.com/c/13Ryt5o5/679-5-as-a-supplier-i-cannot-see-submit-any-draft-services-that-ccs-will-not-consider
We have some lists of IDs that we use as allow-lists. These are needed every time certain pages are loaded.
Previously, we did the string parsing every time. Now, perform the string parsing during app initialisation and store the result. This should remove the performance impact of these new allowlists.
Follows on from https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1325#discussion_r566014562
> Parse list of IDs from config only once

- app/main/helpers/suppliers.py
- config.py
We've recently added functionality to get allow-lists of IDs from environment variables. We pass them in as environment variables, and then convert them from a comma-separated string into a `Set[int]`. However, it seems as if something is [going wrong](https://ci.marketplace.team/job/apps-are-up-preview/257100/smoke_20test_20report/). Either the extraction isn't happening, or the Set somehow gets overwritten with the original string.
My hypothesis is that it's the latter - our app init is somewhat complicated, so it seems plausible. If I'm right, we can fix it by writing to a new key so it won't get overwritten.
If I'm wrong, this won't fix Preview, and I'll just revert everything.
Fixes bug introduced by https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1326
> Extract ID lists to new keys

- app/main/helpers/suppliers.py
- app/main/views/services.py
- config.py
- tests/app/main/helpers/test_suppliers.py
I'm not sure what's wrong, but the caching seems not to be working. When deployed to Preview, our test supplier was incorrectly no longer recognised as a G12 recovery supplier.
So I'm going to revert this to get back to a working state. We can think about whether the caching is necessary and, if so, how to do it correctly.
Reverts https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1326 and https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1327
> Revert caching of lists of IDs from environment variables

- app/main/helpers/suppliers.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/partials/g12_recovery_information.html
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
In our user research we discovered that users expected the banner to change when they had completed all their drafts.
Change the banner to a success message if the user has no unsubmitted G12 recovery drafts (see #1325).
Content on this banner is not final.
There is G12 recovery logic to show a banner on the `/frameworks/<string:framework_slug>/services` route, however I've not updated this as we've now added a new route (`/all-services`, see #1301) for the G12 recovery suppliers to see their services and therefore the banner will never be shown on the `/services` route.
https://trello.com/c/p3BVSpj6/740-2-change-banner-when-all-drafts-complete
> Change G12 banner when all drafts complete

- app/templates/services/list_all_services.html
- tests/app/main/test_services.py
Trello: https://trello.com/c/BbcYnioH/759-2-move-g12-recovery-information-out-of-your-g12-services-banner
In our user research, we found that the banner caused problems for some users on this page. The banner confused users because it linked back to the same page, and caused them to miss the green flash messages.
Remove the banner text and put it into paragraphs above the appropriate tables.
> Remove banner from 'Your G-Cloud-12 services' page

- app/main/helpers/suppliers.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/partials/g12_recovery_information.html
- config.py
- tests/app/main/test_suppliers.py
In #1329 we added logic to the banner so it showed a different message if the supplier had submitted all their draft services. We hadn't decided what the content should be at that time.
In content review, we decided that this behaviour wasn't quite what we wanted.
Update the banner with the final content, and add more logic so the banner tells the supplier how many services they've marked as complete as they go. If the supplier completes all their services, show a third message.
Note the nested `{% with %}` in the template. Putting `"service" if g12_recovery.submitted_drafts == 1 else " services"`
in the string concatenation for `message` caused Jinja to only render the string up to and including service(s). I don't like this solution very much, but it's the only one I was able to get …
> Update G12 recovery banner with final content

- app/main/helpers/suppliers.py
We now have a confirmed closing date for the G12 recovery phase of 2pm on 25th February 2021. Set this so we show the correct date in the reminder banner.
When we set this previously, the countdown in the banner caused the visual regression tests to fail the first time they were run everyday. However, the banner logic was changed in #1331 and our test supplier in Preview and Staging has one G12 draft service marked as complete. This means they'll see the banner content `You have marked 1
service as complete...` and won't get the countdown.
Since #1331 is already released, this commit should not cause any further visual regression test failures.
https://trello.com/c/LyhdZKkZ/724-1-agree-g12-recovery-dates-and-times
This is how the reminder banner now looks for a supplier with no submitted …
> Set G12 recovery closing date

- app/main/views/services.py
Override the G12 closing date with the recovery closing date for recovery suppliers only.
https://trello.com/c/SHoFSoXG/786-1-fix-date-on-submitted-g12-service-summary-pages
The complete service page now looks like:
> Show the correct closing date to G12 recovery suppliers

- app/templates/services/edit_submission_section.html
- app/templates/services/service_submission.html
Trello: https://trello.com/c/k4g4FDoX/787-2-odd-breadcrumbs-on-draft-service-page
The standard breadcrumbs don't work for the G12 recovery, because the user journey is different to normal. Mainly, we have the new 'Your G-Cloud 12 services' page that covers both the services and the lot page from a normal framework. So update the breadcrumbs accordingly.
This will break the breadcrumbs for non-G12 recovery suppliers. That's fine because no framework will be open during the G12 recovery. We will revert this code once the G12 recovery process has closed.
With changes:
> Fix breadcrumbs for G12 recovery

- app/main/views/suppliers.py
- app/templates/suppliers/details.html
- tests/app/main/test_suppliers.py
https://trello.com/c/seJqGqxD/772-2-replace-company-details-page-summary-table-with-summary-list
also fixes https://trello.com/c/7d0040to/233-2-inconsistent-font
Switches company details to use [Summary list](https://design-system.service.gov.uk/components/summary-list/) component.
Some small changes were required to fit within the style of Summary list:
* _Edit_ link text becomes _Change_
* Anchor links for each item are used rather than a shared single link under _What buyers will see_
* Previously if summary was left unpopulated 'Optional' was displayed in plain text. This is no longer possible as the 'Actions' in the Summary list must be links, so I changed it to _Change (Optional)_:
CC @NoraGDS to review these changes.
**I will update the functional tests once this PR is approved.** …
>  switch company details to use Summary List component

- app/main/views/services.py
Ticket: https://trello.com/c/Gv6NtTrs/2173-bug-in-supplier-frontend-on-production
This is causing 500s on production, we don't need it, remove it.
> Remove g12 recovery banner from services pages for other frameworks

- app/templates/suppliers/details.html
- tests/app/main/test_suppliers.py
Fixes https://trello.com/c/0z4CtYQu/2172-bug-in-company-details-page-on-production
When a supplier is created they have no address. This was causing a 500 on the company details page because it was trying to join instances of `None` into a string. This commit fixes this with the Jinja2 filter `select` which drops false-y values from an iterable.
> Fix company details page for new suppliers 

- app/templates/frameworks/start_declaration.html
The combination of `govuk-body` styles mixed with `<br>` tags makes this page look odd:
So let's jettison the `<br>` tags. And as a happy side effect, we can get rid of the custom `framework-dashboard` style as well.
> Remove unnecessary <br> tags

- app/templates/frameworks/reuse_declaration.html
Another case of `govuk-body` styles and `<br>` not working well together. This looks like the last instance of this on the Make a Supplier Declaration journey.
Before:
After:
> Remove unnecessary <br> on Reuse Declaration form

- app/main/helpers/suppliers.py
- app/main/views/services.py
- tests/app/main/test_services.py
Trello: https://trello.com/c/mhab9cpq/826-1-as-a-developer-i-can-stop-suppliers-submitting-draft-services-after-the-deadline
Once the deadline arrives, we want to stop suppliers involved in the recovery from being able to edit and submit their draft services.
Make a simple change to implement this - suppliers will now get 404s if they try to do either after the deadline.
After the deadline, we can tidy up all the other G12 recovery code still lying around.
Supersedes: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1346
> Automatically close G12 recovery at deadline

- .secrets.baseline
- app/assets/javascripts/application.js
- app/main/forms/suppliers.py
- app/main/views/frameworks.py
- app/main/views/services.py
- app/main/views/suppliers.py
- app/templates/_base_page.html
- app/templates/auth/submit_email_address.html
- app/templates/frameworks/edit_declaration_section.html
- app/templates/frameworks/reuse_declaration.html
- app/templates/frameworks/sign_framework_agreement.html
- app/templates/frameworks/updates.html
- app/templates/services/_base_edit_section_page.html
- app/templates/services/previous_services.html
- app/templates/services/service.html
- app/templates/suppliers/create_company_details.html
- app/templates/suppliers/create_confirm_company.html
- app/templates/suppliers/create_duns_number.html
- app/templates/suppliers/create_your_account.html
- app/templates/suppliers/edit_company_registration_number.html
- app/templates/suppliers/edit_registered_name.html
- app/templates/suppliers/edit_supplier_organisation_size.html
- app/templates/suppliers/edit_supplier_trading_status.html
- app/templates/suppliers/edit_what_buyers_will_see.html
- app/templates/suppliers/join_open_framework_notification_mailing_list.html
- app/templates/suppliers/registered_address.html
- tests/app/helpers.py
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
- tests/app/main/test_suppliers.py
As part of migrating our apps to use GOV.UK Design System styles and components, we want to use the [error summary component](https://design-system.service.gov.uk/components/error-summary/) to replace our existing validation banners.
To do this, we add an instance of the error summary component to the app base page template. This ensures that the error summary (if present) is in a consistent location across all pages in the app.
https://trello.com/c/WVjA4w66/771-2-replace-validation-banner-with-govuk-frontend-error-summary-component-in-the-supplier-frontend
> Replace validation banner with GOV.UK Frontend error summary component

- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
In #1340 we replaced the error summary on this page with the GOV.UK error summary. This has the side effect of changing the text in the summary from the question name to the error that needs fixing.
On most pages this is more useful, however the declaration pages have many radio button questions which all need an answer. Each of these questions has the same error message - 'You must answer this question'. It's not helpful for the user to see the same error repeated many times, so the previous behaviour of having the question name in the summary box was more useful.
https://trello.com/c/WVjA4w66/771-2-replace-validation-banner-with-govuk-frontend-error-summary-component-in-the-supplier-frontend
> Change declaration errors to use question name in summary

- .secrets.baseline
- app/assets/scss/application.scss
- app/assets/scss/overrides/_tags.scss
- app/assets/scss/overrides/_task-list.scss
- app/templates/frameworks/_framework_actions.html
- tests/app/main/test_frameworks.py
https://trello.com/c/0q1IRSSf/819-2-rewrite-framework-application-task-list
We want our task lists to look more like the [GOV.UK Design system task list pattern](https://design-system.service.gov.uk/patterns/task-list-pages/).
This means a few CSS and HTML changes.
> Make the Framework Application task list more like the Design System task list

- package-lock.json
- package.json
https://trello.com/c/Hey9OS9t/805-2-mitigate-registers-switch-off
This appears to be the last version which is compatible with the functional tests. 
It appears later versions use different javascript which requires a further interaction after entering a value e.g. click on dropdown value or press return key for the input to be accepted. It is unclear why this was implemented or if it is intentional. I can make an enter keypress to get this to work using Firefox/geckodriver however, I was unable to get it to work using PhantomJS. 
So this PR changes to the latest version as supported by the current tests
> Bump govuk-country-and-territory-autocomplete to 0.5.0

- app/main/__init__.py
- requirements.txt
We've added [the ability to lazily load manifests](https://github.com/alphagov/digitalmarketplace-content-loader/pull/137). Use this for old frameworks to dramatically reduce startup time. This should only affect a small number of user requests, where they'll be about 1s slower. See the previous experiment for numbers: #1348
Keep the newest frameworks eagerly loaded. This is because I think these frameworks receive substantial traffic. So by eagerly loading we avoid slow user requests that are otherwise highly likely. We also want to load these frameworks during app startup so that the app fails to start if the manifests are malformed. We don't typically change old framework data so they're at much lower risk of being broken.
If this works and doesn't break things, we can roll out these …
> Load old manifests lazily for faster app startup

- app/assets/scss/_view-service-link.scss
- app/assets/scss/application.scss
- app/templates/errors/applications_closed.html
- app/templates/frameworks/contract_variation.html
- app/templates/frameworks/declaration_overview.html
- app/templates/frameworks/services.html
- app/templates/services/previous_services.html
- app/templates/services/service.html
- app/templates/services/service_submission.html
- app/templates/suppliers/already_completed.html
- app/templates/suppliers/become_a_supplier.html
- app/templates/suppliers/details.html
- tests/app/main/test_suppliers.py
Ticket: https://trello.com/c/MBn0LIOB/852-2-remove-secondary-action-link-component-from-supplier-frontend
We don't want to use a template for these simple links.
Also remove some unneeded CSS styles.
> Remove uses of secondary action link template

- app/templates/_base_page.html
- app/templates/frameworks/edit_declaration_section.html
- tests/app/main/test_frameworks.py
Replace the toolkit banner with the [banner component](https://github.com/alphagov/digitalmarketplace-govuk-frontend/tree/master/src/digitalmarketplace/components/banner) from the digitalmarketplace-govuk-frontend.
I have run the functional tests against this change and the [relevant scenario](https://github.com/alphagov/digitalmarketplace-functional-tests/blob/master/features/supplier/supplier_applies_to_a_framework.feature#L42) still passes as we don't check for the banner as part of that test.
https://trello.com/c/CQlT1KmX/853-2-replace-notification-banner-on-make-a-supplier-declaration-journey
Previous banner:
New banner:
> Replace notification banner on 'make a declaration' journey

- app/main/views/suppliers.py
- requirements.in
- requirements.txt
- tests/app/main/test_suppliers.py
Closes https://trello.com/c/52Xz6MJM/2184-users-are-able-to-create-supplier-accounts-with-invalid-duns-numbers
This PR updates the supplier frontend to use digitalmarketplace-utils 57.0.0 with changes in alphagov/digitalmarketplace-utils#603.
This will hopefully fix our smoulder tests so that invalid DUNS numbers cannot be used to create a supplier account.
> Update DUNS number validation for digitalmarketplace-utils 57.0.0

- app/main/views/suppliers.py
- tests/app/main/test_suppliers.py
Currently, the status code for a GET request to /suppliers/mailing-list is always 400. Originally, it returned a 200. However, during refactoring (450bca893bb53401945c0401fd2c0e1bb5f343d6), it was changed to a 400. I can see no justification for the change, and suspect it was a mistake.
Change back to a 200 for GETs, since this seems more correct.
> Return 200 response to GET /suppliers/mailing-list

- .secrets.baseline
- app/assets/scss/_action_links.scss
- app/assets/scss/application.scss
- app/assets/scss/overrides/_summary-list.scss
- app/main/views/frameworks.py
- app/templates/frameworks/declaration_overview.html
- tests/app/main/test_frameworks.py
https://trello.com/c/IzTERgai/857-2-replace-your-declaration-overview-summary-table-with-govuk-summary-list
* Summary table replaced with summary list
* Each entry has an individual "Edit" link
* Other behaviour stays the same
* All those Edit links look a bit busy.
* An existing issue: we use URI fragments to anchor to a specific question in the links from this summary list, but there's no other confirmation of where the page is focused - ideally the question we linked to would be highlighted on the next page.
> Replace declaration overview summary table with govukSummaryList

- .secrets.baseline
- app/assets/scss/application.scss
- app/assets/scss/overrides/_radios.scss
- app/assets/scss/overrides/_table.scss
- app/main/views/frameworks.py
- app/main/views/services.py
- app/templates/_base_page.html
- app/templates/frameworks/choose_service_lot.html
- app/templates/frameworks/submission_lots.html
- app/templates/services/choose_service_lot.html
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_frameworks.py
https://trello.com/c/r8CxfKTO/820-5-replace-choose-a-lot-page-in-create-a-service-journey
This splits out the Choose a Lot page into two:
The first page has a list of existing draft and completed services, as well as an action button to add a service.
The second page allows the user to select a lot/service category for their new service.
This flow is ripe for user testing, there's a ticket here: https://trello.com/c/kxH01U71/7-test-new-add-a-service-page
Functional tests: https://github.com/alphagov/digitalmarketplace-functional-tests/pull/861
> New choose a lot page in create a service journey

- app/templates/_base_page.html
- app/templates/suppliers/edit_registered_name.html
- app/templates/suppliers/edit_what_buyers_will_see.html
- app/templates/suppliers/registered_address.html
- tests/app/helpers.py
- tests/app/main/test_suppliers.py
This replaces our Frontend Toolkit text fields with GOV.UK Design System equivalents for the Confirm Company Details journey.
https://trello.com/c/gQM1Rikz/895-2-replace-text-boxes-with-govuk-frontend-text-input-component-in-confirm-company-details-journey
https://trello.com/c/duej3OKP/894-1-replace-large-text-boxes-with-govuk-frontend-charactercount-component-in-confirm-company-details-journey
> Replace text boxes on confirm company details journey

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/edit_supplier_trading_status.html
- tests/app/helpers.py
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/aYM0E0zY/896-2-replace-radios-with-govuk-frontend-radios-component-in-confirm-company-details-journey
As part of moving to Design System 3, we need to replace our use of `toolkit/forms/selection-buttons.html` with `govukRadios` from the design system. This should make this page more accessible.
As part of this, we're also moving away from our customised DMRadioField to the standard wtforms equivalent.
We've added a helper method in `CompanyTradingStatusForm` to get the items in the right format for `govukRadios`. We're not sure this is the right way to do this - we'll refactor as necessary when we come to replace the other radios in the supplier details journey.
> Replace radio on supplier trading status page

- app/main/forms/suppliers.py
- app/main/views/suppliers.py
- app/templates/suppliers/edit_supplier_organisation_size.html
- app/templates/suppliers/edit_supplier_trading_status.html
- tests/app/main/test_suppliers.py
Trello: https://trello.com/c/aYM0E0zY/896-2-replace-radios-with-govuk-frontend-radios-component-in-confirm-company-details-journey
As part of moving to Design System 3, we need to replace our use of `toolkit/forms/selection-buttons.html` with `govukRadios` from the design system. This should make this page more accessible.
As part of this, we're also moving away from our customised DMRadioField to the standard wtforms equivalent.
Follows the example of #1396
---
Old:
New:
> Replace radio on organisation size page 

- app/templates/suppliers/edit_company_registration_number.html
Trello: https://trello.com/c/aYM0E0zY/896-2-replace-radios-with-govuk-frontend-radios-component-in-confirm-company-details-journey
As part of moving to Design System 3, we need to replace our use of toolkit/forms/selection-buttons.html with govukRadios from the design system. This should make this page more accessible.
This question is quite complex, so the template is quite lengthy. However, quite a bit of that is just caused by the govukRadios being a bit more verbose and having more braces.
Similar to #1396 and #1401, though this question doesn't use `DMRadioField`, so this PR only needs to make template changes.
The overall diff is not very helpful - recommend reviewing commit by commit instead.
---
Old:
New:
> Ask for company registration number with govukRadios 

- app/templates/suppliers/edit_company_registration_number.html
Set it to open in a new tab, which should be more helpful for users. Also update the link to point to the current Companies House search page, which is what the old beta page redirected to.
Addresses https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1403#discussion_r605038994
> Improve the link to Companies House

- app/main/forms/suppliers.py
- tests/app/helpers.py
- tests/app/main/test_suppliers.py
https://trello.com/c/AnpNWBC7/893-2-update-error-messages-for-confirm-company-details-journey
Re-word error messages to be closer to those used in Design System examples from https://design-system.service.gov.uk/components/error-message/
@NoraGDS please may you review the wording changes in `app/main/forms/suppliers.py`?
>  update Company Details error messages to be more in line with Design System examples 

- .secrets.baseline
- app/main/views/services.py
- config.py
Trello: https://trello.com/c/XoWXM8lC/85-run-dmrunner-without-credentials
This matches what we use for the real S3 - the old way of doing it in the path is deprecated.
By using localstack S3 subdomains, we now get file upload working correctly. This is because we no longer lose the bucket name when we add the document path, which was the previous behaviour.
This affects supplier-frontend only when run locally in developer mode. It depends on having a recent version of localstack - see https://github.com/alphagov/digitalmarketplace-runner/pull/194. This change means that the functional tests tagged as '@file-upload' now succeed when run locally.
Also, an unrelated small secret baseline update.
> Add support for localstack S3 subdomains

- .secrets.baseline
- app/assets/scss/_question.scss
- app/assets/scss/application.scss
- app/assets/scss/overrides/_radios.scss
- app/main/helpers/validation.py
- app/main/views/frameworks.py
- app/templates/_base_page.html
- app/templates/frameworks/edit_declaration_section.html
- tests/app/main/test_frameworks.py
https://trello.com/c/zXOnW11P/892-2-replace-content-loader-form-macros-in-make-a-supplier-declaration-journey
This PR relies on:
alphagov/digitalmarketplace-content-loader/pull/143
alphagov/digitalmarketplace-content-loader/pull/144
> Replace content loader form macros in Make a Supplier Declaration journey

- .secrets.baseline
- app/templates/partials/service_warning.html
- app/templates/services/service_submission.html
- tests/app/main/test_frameworks.py
- tests/app/main/test_services.py
We want to replace our [Digital Marketplace Frontend Toolkit](https://github.com/alphagov/digitalmarketplace-frontend-toolkit) banners with [Digital Marketplace govuk-frontend](https://github.com/alphagov/digitalmarketplace-govuk-frontend/tree/master/src/digitalmarketplace/components/banner) banners.
Mostly straightforward, but see https://github.com/alphagov/digitalmarketplace-supplier-frontend/commit/ff2c7b6028cef63a3f25c99220f0cda32dceae56 for a potentially iffy like-for-like replacement.
We can now also use the [Design System Notification Banner](https://design-system.service.gov.uk/components/notification-banner/) once we've updated to [govuk-frontend version 3.10+](https://github.com/alphagov/govuk-frontend/releases/tag/v3.10.0). …
> Replace banners in create a service journey

- .secrets.baseline
- app/assets/scss/_updates.scss
- app/templates/frameworks/updates.html
- tests/app/main/test_frameworks.py
Trello: https://trello.com/c/tnbrDQrf/960-1-investigate-broken-tests-in-supplier-frontend-1-day
Previously, this test was broken in two ways:
1. The CSS styles used in the xpaths were no longer in use due to https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1286/
2. The test didn't fail when the xpath search found no matching tables.
So I needed to fix this by updating the xpaths to match the current naming. I then updated the tests to fail if it ever fails to find the two tables - for clarifications and communications.
The two affected tests seemed very similar, so I consolidated them into one.
> Fix tests for updates table

- app/main/views/services.py
- tests/app/main/helpers/test_frameworks.py
- tests/app/main/test_services.py
The `@EnsureApplicationCompanyDetailsHaveBeenConfirmed` annotation already ensures that suppliers have registered interest in a framework and returns a 404 status if not.
So the `if not get_supplier_framework_info(data_api_client, framework_slug):` checks are entirely redundant, since it is imossible for them ever to fail. So we can safely remove them all to remove some unnecessary API requests.
Add a test for this behaviour to the annotation tests. This means that we can safely remove the tests for this behaviour from the individual endpoints.
The history of this is that the annotation was added later (c29a4ee2597b81ce8062b385105479efb5379721). It looks as if they didn't notice that they'd made this check redundant at the time.
Discovered during …
> Remove redundant checks and API requests

- app/main/helpers/services.py
- app/main/views/services.py
There are a number of endpoints that all need to get a draft service in the same way. So it makes sense to create a helper to cut down on unnecessary duplication.
> Commonise getting draft service

- app/main/forms/frameworks.py
- app/main/views/services.py
- app/templates/services/previous_services.html
- tests/app/main/test_services.py
https://trello.com/c/JiuMuQNd/986-1-replace-radios-in-reuse-service-page
As part of moving to Design System 3, we need to replace our use of `toolkit/forms/selection-buttons.html` with `govukRadios` from the design system. This should make this page more accessible.
As part of this, we're also moving away from our customised DMRadioField to the standard wtforms equivalent.
I made a change in behaviour. Previously the page would default to 'no' if you didn't select a response. I couldn't work out how to keep this behaviour with govukradios, and couldn't see any other pages that did this. So it's now mandatory to provide a response on this page, in common with all other similar pages.
Old:
New:
> Replace radio in service reuse page

- app/templates/services/previous_services.html
Spotted a typo in #1437 where the `novalidate` attribute was enclosed in the `action` string - this fixes it.
> Fix previous services form attributes typo

- app/templates/services/list_services.html
- tests/app/main/test_services.py
https://trello.com/c/xcKuSRij/984-2-replace-summary-tables-of-services
We were previously using toolkit/summary-table.html. We want to replace all uses of the toolkit with design system components. This is part of our migration to Design System 3 to improve accessibility.
No changes in behaviour. Some formatting changes, but none that look major.
Old:
New (the first service has a funny name - I was testing that it was still being escaped properly):
> Use govukTable for list of supplier services

- app/templates/services/list_services.html
- tests/app/main/test_services.py
In https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1439, I accidentally removed some logic that is needed for the DOS version of this table to render correctly. This is because some DOS lots are limited to one service, so the service has no name.
Fix the logic to match the previous logic, and then add a test for this scenario
> Fix list of live services for DOS

- .secrets.baseline
- app/main/views/frameworks.py
- tests/app/main/test_frameworks.py
https://trello.com/c/5E22SHaQ/27-ccs-sourcing-admins-cant-view-suppliers-modern-slavery-statements
Declaration documents are stored in the documents bucket, the contents of which are already public. So we don't need to go via supplier frontend to access the files. As far as I can tell, this functionality was added as a bug fix. It copied existing code for viewing files in non-public buckets, seemingly without realising that this was unnecessary (https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1023).
Instead, use the assets URL to construct the URL we save in the declaration in the database. This will mean that other apps can now show these files to non-supplier users without having to do hacky URL-rewriting.
This also has the added benefit that declaration files …
> Change URL stored for declaration documents

- gulpfile.js
- package-lock.json
- package.json
https://trello.com/c/zjkM8Utr/8-3-upgrade-off-gulp-sourcemaps-v3
As of Gulp 4, sourcemap support is built into Gulp. Switch over to this new method (https://gulpjs.com/docs/en/api/src#sourcemaps).
This will help us remove a dependency on gulp-sourcemaps, which is pinning a version of postcss with a known vulnerability.
I've tested this locally, and it doesn't seem to break anything - the sourcemap is still present in the same location.
> Switch to sourcemaps from gulp

- app/assets/scss/overrides/_summary-list.scss
- app/templates/frameworks/services.html
Replace toolkit summary table on draft services page with govuk-frontend v3 elements.
https://trello.com/c/xcKuSRij/24-2-replace-summary-tables-of-services
> Replace summary table on draft services page

- app/templates/frameworks/services.html
https://trello.com/c/xcKuSRij/24-2-replace-summary-tables-of-services
Bugfix after https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1451
Previously we were erroneously showing an empty table before a supplier had completed a service.
> don't show table if no completed services

- app/assets/scss/overrides/_table.scss
- app/templates/services/previous_services.html
These modifiers were only added in govuk-frontend 3.12, so we'll only have access to them once we've upgraded to that version in the future.
In the meantime, we can add an override for the specific class we need here.
> Add govuk-table__caption--m override

- app/assets/scss/overrides/_table.scss
- app/templates/services/previous_services.html
- tests/app/main/test_services.py
https://trello.com/c/xcKuSRij/24-2-replace-summary-tables-of-services
We are replacing Digital Marketplace toolkit components with GOVUK frontend v3 (Design System) components as they have been accessibility tested.
> replace summary table on previous services page with govuk frontend v3 table

- app/main/__init__.py
This allows us to open G-Cloud 13 applications on local environments so we can work on changes. I simply copied the manifests, metadata and messages loaded from G-Cloud 12 - G-Cloud 13 at the moment is almost a complete copy of G-Cloud 12.
Nothing in here is visible to our users until the API framework object is created, so this is safe to deploy.
> Load G-Cloud 13 content

- app/templates/macros/pricing-input/template.njk
In G-Cloud 13 we will only allow unit pricing for lots 1, 2 and 3. There will be a separate lot 4 that handles cloud support billed on a per person basis. Lot 4 doesn't exist yet, so we can remove the option to select per person pricing from the existing lots 1, 2 and 3 and re-introduce it for lot 4 when that's created.
This only affects the list of pricing options that's shown to the user when creating a service, not what the API will accept or any existing services. This page is also only accessible when creating a service, so there will be no user-facing impact.
To see the difference in the list, make sure you have the latest version of the API checked out as well as this branch. Then create a new framework object for G-Cloud 13 and set the status to `open`:
``` …
```
> Remove 'a person' pricing option for G-Cloud services

- requirements-dev.txt
- requirements.txt
The previous version of urllib3 has a known vulnerability. I don't think we're affected, but we should fix it anyway. Unfortunately, urllib3 is a transitive dependency of many other libraries. So to update urllib3, we also need to update the libraries that rely on it.
Exactly the same problem as https://github.com/Crown-Commercial-Service/digitalmarketplace-antivirus-api/pull/123, with exactly the same fix.
> Update urllib3 and linked libraries

- .github/dependabot.yml
Supplier frontend is not fully on the Design System. So we need to carry on using the previous major version (https://github.com/Crown-Commercial-Service/digitalmarketplace-govuk-frontend#using-govuk-frontend-v2).
Fixes the problem of https://github.com/Crown-Commercial-Service/digitalmarketplace-supplier-frontend/pull/1486
> Ignore major version updates for govuk-frontend

- app/main/views/suppliers.py
- app/templates/_base_page.html
- app/templates/suppliers/dashboard.html
- tests/app/main/test_suppliers.py
- Add the banner with the logic
- Add tests for the banner
This is from the ticket [OST-134](https://crowncommercialservice.atlassian.net/browse/OST-134) (6/5)
This is a screenshot of what the login page would look like:
The logic used is the same as in https://github.com/Crown-Commercial-Service/digitalmarketplace-user-frontend/pull/422
> Add the notification banner

- docker-aws/Dockerfile.wsgi
Supplier (and admin) frontend uses an older version of some GOV.UK packages and as such it requires some files to be copied into the build.
> Update Dockerfile.wsgi to copy template files
